-- Helpers for the specs that compare org.nvim with the Emacs Org 9.8.10
-- output checked in under tests/fixtures/emacs/ (generated by
-- scripts/emacs-parity/generate.sh; see its README). The specs only read
-- those files: CI has no Emacs.

local M = {}

M.root = vim.fs.normalize(vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h"))
M.dir = M.root .. "/tests/fixtures/emacs"

--- The generators' fixed time zone and "now" (scripts/emacs-parity/common.el).
M.TZ = "UTC0"
M.NOW = { year = 2026, month = 10, day = 1, hour = 12, min = 0, sec = 0 }

function M.read(path)
  local f = assert(io.open(path, "rb"))
  local s = f:read("*a")
  f:close()
  return (s:gsub("\r\n", "\n"))
end

--- The lines of `s` (a trailing newline doesn't add an empty last line).
function M.lines(s)
  local t = vim.split(s, "\n", { plain = true })
  if t[#t] == "" then
    t[#t] = nil
  end
  return t
end

--- The "=== name" sections of an expected-output file: a list of
--- `{ name = , lines = }` in file order, also indexed by name.
function M.sections(path)
  local out, cur = {}, nil
  for _, l in ipairs(M.lines(M.read(path))) do
    local name = l:match("^=== (.+)$")
    if name then
      cur = { name = name, lines = {} }
      out[#out + 1] = cur
      out[name] = cur
    elseif cur then
      cur.lines[#cur.lines + 1] = l
    end
  end
  return out
end

--- The non-comment lines of a cases file, split on whitespace.
function M.cases(path)
  local out = {}
  for _, l in ipairs(M.lines(M.read(path))) do
    if not l:match("^%s*#") and l:match("%S") then
      out[#out + 1] = vim.split(vim.trim(l), "%s+")
    end
  end
  return out
end

--- Inside a describe: run each test in the generators' zone with "now"
--- frozen at M.NOW (os.time() and os.date() without a time).
function M.freeze_time()
  local date = require("org.date")
  local saved
  before_each(function()
    saved = { tz = vim.env.TZ, time = os.time, date = os.date }
    date.set_tz(M.TZ)
    local real_time, real_date = os.time, os.date
    local now = real_time(M.NOW)
    os.time = function(t)
      if t == nil then
        return now
      end
      return real_time(t)
    end
    os.date = function(fmt, t)
      return real_date(fmt or "%c", t or now)
    end
  end)
  after_each(function()
    os.time, os.date = saved.time, saved.date
    date.set_tz(saved.tz)
  end)
end

---------------------------------------------------------------------------
-- Known, intentional differences
---------------------------------------------------------------------------
-- The ONLY place where outputs are rewritten before comparing. Each entry
-- is a documented difference (:h org-differences, or the keys of
-- :h org-agenda-keys): never add one to make a real bug pass, mark the
-- case as known in its spec instead.
--   emacs = { { pattern, replacement }, ... }  gsub on each Emacs line
--   both = { { pattern, replacement }, ... }  gsub on the lines of both sides
--   drop = { pattern, ... }  lines dropped on both sides
M.NORMALISE = {
  agenda = {
    emacs = {
      -- the hint lines name the key that edits the query: Vim's count
      -- prefix instead of Emacs' C-u (:h org-agenda-keys, "r")
      { "‘C%-u r’", "‘1 r’" },
    },
  },
  lint = {
    both = {
      -- Emacs reports a misplaced heading at a wrong place: the checker
      -- reads match-beginning after org-element-at-point clobbered the
      -- match data (with the match data saved, Emacs gives our places).
      -- Compare the number of reports only (:h org-differences).
      { "^%d+:%d+ (%[misplaced%-heading%])", "?:? %1" },
    },
    drop = {
      -- which languages are known depends on the installation: Emacs
      -- knows those with a babel backend or an installed major mode
      -- (no vim-mode or json-mode in emacs -Q), org.nvim those with a
      -- babel backend or a Neovim syntax/ftplugin (:h org-differences)
      "^%d+:%d+ %[suspicious%-language%-in%-src%-block%]",
      -- Emacs falls back on the current file for any ID
      -- (org-id-find-id-file), so it never reports an unknown ID in a
      -- file buffer; org.nvim does (:h org-differences)
      "^%d+:%d+ %[invalid%-id%-link%]",
    },
  },
}

--- Apply the NORMALISE rules of `area`: returns the Emacs and our lines.
function M.normalise(area, emacs, ours)
  local rules = M.NORMALISE[area] or {}
  local function keep(l)
    for _, p in ipairs(rules.drop or {}) do
      if l:match(p) then
        return false
      end
    end
    return true
  end
  local function rewrite(lines, sets)
    local out = {}
    for _, l in ipairs(lines) do
      for _, set in ipairs(sets) do
        for _, r in ipairs(set) do
          l = l:gsub(r[1], r[2])
        end
      end
      if keep(l) then
        out[#out + 1] = l
      end
    end
    return out
  end
  return rewrite(emacs, { rules.emacs or {}, rules.both or {} }), rewrite(ours, { rules.both or {} })
end

--- A readable diff of two line lists (first difference with context).
function M.diff(expected, actual)
  local n = math.max(#expected, #actual)
  for i = 1, n do
    if expected[i] ~= actual[i] then
      local out = { string.format("first difference at line %d:", i) }
      for j = math.max(1, i - 3), math.min(n, i + 5) do
        local mark = expected[j] == actual[j] and "  " or "! "
        out[#out + 1] = string.format("%s%3d emacs: %s", mark, j, vim.inspect(expected[j]))
        if expected[j] ~= actual[j] then
          out[#out + 1] = string.format("%s%3d ours:  %s", mark, j, vim.inspect(actual[j]))
        end
      end
      return table.concat(out, "\n")
    end
  end
end

--- Compare line lists; `known` (a reason string) marks a documented known
--- failure: it must still differ (so the entry is removed once fixed), and
--- the test is reported as skipped with the reason.
function M.compare(expected, actual, known)
  local d = M.diff(expected, actual)
  if known then
    if not d then
      error("known failure now matches Emacs: remove it from KNOWN (" .. known .. ")", 2)
    end
    error({ skip = "known difference from Emacs: " .. known }, 0)
  end
  if d then
    error("differs from Emacs Org 9.8.10\n" .. d, 2)
  end
end

return M
