---@meta
-- LuaLS type definitions for the `agenda`, `capture` and `refile` sections of
-- `require("org").setup()`. Annotations only; never loaded at runtime.

---------------------------------------------------------------------------
-- Agenda
---------------------------------------------------------------------------

---Agenda span: a named span or a number of days.
---@alias org.Config.Agenda.Span "day"|"week"|"fortnight"|"month"|"year"|integer

---Agenda sorting strategy (org-agenda-sorting-strategy). An unknown name is
---an error, like in Emacs.
---@alias org.Config.Agenda.SortingStrategy
---| "time-up"
---| "time-down"
---| "priority-up"
---| "priority-down"
---| "urgency-up"
---| "urgency-down"
---| "category-up"
---| "category-down"
---| "category-keep"
---| "todo-state-up"
---| "todo-state-down"
---| "alpha-up"
---| "alpha-down"
---| "habit-up"
---| "habit-down"
---| "deadline-up"
---| "deadline-down"
---| "scheduled-up"
---| "scheduled-down"
---| "timestamp-up"
---| "timestamp-down"
---| "ts-up"
---| "ts-down"
---| "tsia-up"
---| "tsia-down"
---| "stats-up"
---| "stats-down"
---| "tag-up"
---| "tag-down"
---| "effort-up"
---| "effort-down"
---| "user-defined-up"
---| "user-defined-down"

---Agenda block type. Emacs-style names are accepted as aliases:
---`"tags-todo"` = `"tags_todo"`, `"alltodo"` = `"todo"`,
---`"stuck-projects"`/`"stuck_projects"` = `"stuck"`. `"tags-tree"`,
---`"todo-tree"` and `"occur-tree"` make a sparse tree of the current buffer.
---@alias org.Config.Agenda.BlockType
---| "agenda"
---| "todo"
---| "tags"
---| "tags_todo"
---| "search"
---| "stuck"
---| "tags-todo"
---| "alltodo"
---| "stuck-projects"
---| "stuck_projects"
---| "tags-tree"
---| "todo-tree"
---| "occur-tree"

---Kind of dated entry collected by the agenda (org-agenda-entry-types).
---@alias org.Config.Agenda.EntryType "deadline"|"scheduled"|"timestamp"|"sexp"|"deadline*"|"scheduled*"

---Skip function (org-agenda-skip-function): return true to drop the entry.
---See `require("org.agenda").skip_entry_if()` / `skip_subtree_if()`.
---@alias org.Config.Agenda.SkipFunction fun(headline: org.Headline): boolean?

---A limit per view type, or one number for all (org-agenda-max-entries etc.).
---@alias org.Config.Agenda.Limit integer|{ agenda?: integer, todo?: integer, tags?: integer, search?: integer }

---Agenda view options.
---@class org.Config.Agenda
---Default span of the agenda view (org-agenda-span). (default: `"week"`)
---@field span? org.Config.Agenda.Span
---Weekday that 7 and 14 day spans start on, 1 = Monday ... 7 = Sunday;
---`false` starts on the start day (org-agenda-start-on-weekday). (default: `1`)
---@field start_on_weekday? integer|false
---Offset like `"-3d"` or a date for the first day (org-agenda-start-day). A
---block's own `start_day` overrides it. (default: `nil`)
---@field start_day? string
---Kinds of dated entries collected (org-agenda-entry-types).
---(default: `{ "deadline", "scheduled", "timestamp", "sexp" }`)
---@field entry_types? org.Config.Agenda.EntryType[]
---Include deadlines (org-agenda-include-deadlines). (default: `true`)
---@field include_deadlines? boolean
---Hide scheduled entries that are DONE (org-agenda-skip-scheduled-if-done). (default: `false`)
---@field skip_scheduled_if_done? boolean
---Hide deadlines of DONE entries (org-agenda-skip-deadline-if-done). (default: `false`)
---@field skip_deadline_if_done? boolean
---Hide timestamps of DONE entries (org-agenda-skip-timestamp-if-done). (default: `false`)
---@field skip_timestamp_if_done? boolean
---Hide a scheduled entry when its deadline is shown that day; `"not-today"`
---only for past scheduled dates (org-agenda-skip-scheduled-if-deadline-is-shown).
---(default: `false`)
---@field skip_scheduled_if_deadline_is_shown? boolean|"not-today"
---Hide a timestamp when the entry's deadline is shown that day
---(org-agenda-skip-timestamp-if-deadline-is-shown). (default: `false`)
---@field skip_timestamp_if_deadline_is_shown? boolean
---Hide repeats of a scheduled entry after its deadline
---(org-agenda-skip-scheduled-repeats-after-deadline). (default: `false`)
---@field skip_scheduled_repeats_after_deadline? boolean
---Show only the first timestamp of an entry per day
---(org-agenda-skip-additional-timestamps-same-entry). (default: `false`)
---@field skip_additional_timestamps_same_entry? boolean
---Deadline pre-warnings of scheduled entries
---(org-agenda-skip-deadline-prewarning-if-scheduled): `true` = none, a
---number = at most that many days before, `"pre-scheduled"` = not before
---the scheduled date. (default: `false`)
---@field skip_deadline_prewarning_if_scheduled? boolean|integer|"pre-scheduled"
---Ignore a scheduled delay (`-2d`) when the entry has a deadline
---(org-agenda-skip-scheduled-delay-if-deadline). (default: `false`)
---@field skip_scheduled_delay_if_deadline? boolean|integer|"post-deadline"
---Days an overdue deadline is shown in today's agenda (org-deadline-past-days).
---(default: `10000`)
---@field deadline_past_days? integer
---Days a past scheduled entry is shown in today's agenda
---(org-scheduled-past-days). (default: `10000`)
---@field scheduled_past_days? integer
---Show the last repeat instead of the base date; `true` or a list of TODO
---keywords (org-agenda-prefer-last-repeat). (default: `false`)
---@field prefer_last_repeat? boolean|string[]
---Show future occurrences of repeating timestamps; `"next"` only shows the
---next one (org-agenda-show-future-repeats). (default: `true`)
---@field show_future_repeats? boolean|"next"
---Show days without entries (org-agenda-show-all-dates). (default: `true`)
---@field show_all_dates? boolean
---Hide scheduled entries from TODO lists (org-agenda-todo-ignore-scheduled):
---`true`/`"all"`, `"future"`, `"past"`, or a number of days. (default: `false`)
---@field todo_ignore_scheduled? boolean|"all"|"future"|"past"|integer
---Hide entries with a deadline from TODO lists (org-agenda-todo-ignore-deadlines):
---`true`/`"near"` = within the warning period, `"far"`, `"all"`,
---`"future"`, `"past"`, or a number of days. (default: `false`)
---@field todo_ignore_deadlines? boolean|"all"|"near"|"far"|"past"|"future"|integer
---Hide entries with a plain timestamp from TODO lists
---(org-agenda-todo-ignore-timestamp). (default: `false`)
---@field todo_ignore_timestamp? boolean|"future"|"past"|integer
---Hide entries with any active date from TODO lists
---(org-agenda-todo-ignore-with-date). (default: `false`)
---@field todo_ignore_with_date? boolean
---Apply the todo_ignore_* options to tags-todo views
---(org-agenda-tags-todo-honor-ignore-options). (default: `false`)
---@field tags_todo_honor_ignore_options? boolean
---List TODO children of listed TODOs (org-agenda-todo-list-sublevels). (default: `true`)
---@field todo_list_sublevels? boolean
---List matching children of matches (org-tags-match-list-sublevels). (default: `true`)
---@field tags_match_list_sublevels? boolean
---Time grid (org-agenda-time-grid, org-agenda-use-time-grid).
---@field time_grid? org.Config.Agenda.TimeGrid
---Text of the current-time line (org-agenda-current-time-string).
---(default: `"← now ───────────────────────────────────────────────"`)
---@field current_time_string? string
---Show the current-time line (org-agenda-show-current-time-in-grid). (default: `true`)
---@field show_current_time_in_grid? boolean
---Line prefix (org-agenda-prefix-format): one string for all views or one
---per view. `%c` category, `%i` icon, `%t` time, `%s` leader, `%e` effort,
---`%l` level, `%b` breadcrumbs, `%T` last tag, `%(lua expression)`.
---@field prefix_format? string|org.Config.Agenda.PrefixFormat
---Scheduled leaders { on the day, past with `%d` days } (org-agenda-scheduled-leaders).
---(default: `{ "Scheduled: ", "Sched.%2dx: " }`)
---@field scheduled_leaders? string[]
---Deadline leaders { due, in `%d` days, `%d` days ago } (org-agenda-deadline-leaders).
---(default: `{ "Deadline:  ", "In %3d d.: ", "%2d d. ago: " }`)
---@field deadline_leaders? string[]
---Date range leaders { same day, `(%d/%d)` } (org-agenda-timerange-leaders).
---(default: `{ "", "(%d/%d): " }`)
---@field timerange_leaders? string[]
---Leader of inactive timestamps (org-agenda-inactive-leader). (default: `"["`)
---@field inactive_leader? string
---Remove a time of day shown in the prefix from the headline; `"beg"` only
---at its start (org-agenda-remove-times-when-in-prefix). (default: `true`)
---@field remove_times_when_in_prefix? boolean|"beg"
---Take the time of day from the headline when the timestamp has none
---(org-agenda-search-headline-for-time). (default: `true`)
---@field search_headline_for_time? boolean
---Minutes added as end time to timed entries without one
---(org-agenda-default-appointment-duration). (default: `nil`)
---@field default_appointment_duration? integer
---"09:00" instead of " 9:00" (org-agenda-time-leading-zero). (default: `false`)
---@field time_leading_zero? boolean
---Times as "9:00am" (org-agenda-timegrid-use-ampm). (default: `false`)
---@field timegrid_use_ampm? boolean
---Day header: a strftime format or a function (org-agenda-format-date).
---(default: `nil`, "Friday     25 September 2026" with the week on Mondays)
---@field format_date? string|fun(d: table): string
---Weekend days, 0 = Sunday (org-agenda-weekend-days). (default: `{ 6, 0 }`)
---@field weekend_days? integer[]
---Vim regexp of tags not displayed (org-agenda-hide-tags-regexp). (default: `nil`)
---@field hide_tags_regexp? string
---Tag position: `"auto"` = right edge, N > 0 = start column, N < 0 = end
---column (org-agenda-tags-column). (default: `"auto"`)
---@field tags_column? "auto"|integer
---`{ { vim_regexp, icon_text }, ... }` for `%i` (org-agenda-category-icon-alist).
---(default: `{}`)
---@field category_icons? { [1]: string, [2]: string }[]
---Echo the outline path of the entry at point (org-agenda-show-outline-path).
---(default: `true`)
---@field show_outline_path? boolean
---Separator of `%b` breadcrumbs (org-agenda-breadcrumbs-separator). (default: `"->"`)
---@field breadcrumbs_separator? string
---Sorting strategies per view type (org-agenda-sorting-strategy).
---@field sorting? org.Config.Agenda.Sorting
---Comparator for "user-defined-up/down": returns -1, 1 or nil
---(org-agenda-cmp-user-defined). (default: `nil`)
---@field cmp_user_defined? fun(a: org.AgendaItem, b: org.AgendaItem): integer?
---Entries without a time sort last (org-agenda-sort-notime-is-late). (default: `true`)
---@field sort_notime_is_late? boolean
---Entries without an effort count as longest (org-agenda-sort-noeffort-is-high).
---(default: `true`)
---@field sort_noeffort_is_high? boolean
---Maximum entries per day or list (org-agenda-max-entries). (default: `nil`)
---@field max_entries? org.Config.Agenda.Limit
---Maximum TODO entries (org-agenda-max-todos). (default: `nil`)
---@field max_todos? org.Config.Agenda.Limit
---Maximum tagged entries (org-agenda-max-tags). (default: `nil`)
---@field max_tags? org.Config.Agenda.Limit
---Maximum total effort in minutes (org-agenda-max-effort). (default: `nil`)
---@field max_effort? org.Config.Agenda.Limit
---Where the agenda opens (org-agenda-window-setup); `"split"` is Emacs's
---reorganize-frame. Emacs names ("reorganize-frame", "current-window",
---"only-window", "other-window", "other-tab") are accepted. (default: `"split"`)
---@field window? "split"|"only"|"other"|"current"|"vsplit"|"tab"|"float"
---Restore the window layout when quitting (org-agenda-restore-windows-after-quit).
---(default: `false`)
---@field restore_windows_after_quit? boolean
---One buffer per agenda command (org-agenda-sticky). (default: `false`)
---@field sticky? boolean
---Keep filters when another agenda is built (org-agenda-persistent-filter). (default: `false`)
---@field persistent_filter? boolean
---Tag filter computed per tag: returns "+tag", "-tag" or nil
---(org-agenda-auto-exclude-function). (default: `nil`)
---@field auto_exclude_function? fun(tag: string): string?
---Keep marks after a bulk action (org-agenda-persistent-marks). (default: `false`)
---@field persistent_marks? boolean
---Extra bulk action keys (org-agenda-bulk-custom-functions). (default: `{}`)
---@field bulk_custom_functions? table<string, org.Config.Agenda.BulkFunction|fun(target: org.Target, item: org.AgendaItem)>
---No block headers and separators (org-agenda-compact-blocks). (default: `false`)
---@field compact_blocks? boolean
---Items shown in log mode (org-agenda-log-mode-items). (default: `{ "closed", "clock" }`)
---@field log_mode_items? ("closed"|"clock"|"state")[]
---Habit display options (org-habit).
---@field habits? org.Config.Agenda.Habits
---Stuck project definition (org-stuck-projects).
---@field stuck_projects? org.Config.Agenda.StuckProjects
---Save source buffers after editing them from the agenda. Emacs never does.
---(default: `false`)
---@field save_after_edit? boolean
---Character repeated, or a whole line, separating blocks
---(org-agenda-block-separator); `false` for none. (default: `"─"`)
---@field block_separator? string|false
---Show inherited tags on agenda lines (org-agenda-show-inherited-tags). (default: `true`)
---@field show_inherited_tags? boolean
---Hide tags on agenda lines; `"prefix"` when the prefix shows `%T`
---(org-agenda-remove-tags). (default: `false`)
---@field remove_tags? boolean|"prefix"
---Custom agenda commands keyed by dispatcher key (org-agenda-custom-commands).
---Keys may be several characters long; a string value only labels the group
---of keys that start with that prefix. (default: `{}`)
---@field custom_commands? table<string, org.Config.Agenda.CustomCommand|string>
---Columns format of the agenda column view
---(org-agenda-overriding-columns-format). (default: `nil`)
---@field overriding_columns_format? string
---Open every agenda in column view (org-agenda-view-columns-initially). (default: `false`)
---@field view_columns_initially? boolean
---Column summaries on date lines (org-agenda-columns-show-summaries). (default: `true`)
---@field columns_show_summaries? boolean
---More files for the search view; "agenda-archives" adds the archive files
---(org-agenda-text-search-extra-files). (default: `{}`)
---@field text_search_extra_files? string[]
---Every search query is boolean (org-agenda-search-view-always-boolean). (default: `false`)
---@field search_view_always_boolean? boolean
---Search words match whole words (org-agenda-search-view-force-full-words). (default: `false`)
---@field search_view_force_full_words? boolean
---Deeper entries are searched with their ancestor at this level; 0 = no
---limit (org-agenda-search-view-max-outline-level). (default: `0`)
---@field search_view_max_outline_level? integer
---Body lines shown under each entry in entry text mode (`E`)
---(org-agenda-entry-text-maxlines). (default: `5`)
---@field entry_text_maxlines? integer
---Ask before `<C-k>` deletes an entry longer than this many lines
---(org-agenda-confirm-kill). `false` = never ask. (default: `1`)
---@field confirm_kill? integer|false
---Start in log mode; `"all"` shows all log items, `"clockcheck"` the clock
---check (org-agenda-start-with-log-mode). (default: `false`)
---@field start_with_log_mode? boolean|"all"|"clockcheck"
---Add the first line of a clock-out or state note to log items
---(org-agenda-log-mode-add-notes). (default: `true`)
---@field log_mode_add_notes? boolean
---Start in follow mode (org-agenda-start-with-follow-mode). (default: `false`)
---@field start_with_follow_mode? boolean
---Start with the clock report shown (org-agenda-start-with-clockreport-mode). (default: `false`)
---@field start_with_clockreport_mode? boolean
---Clocktable parameters of the clock report
---(org-agenda-clockreport-parameter-plist); the scope and time range come
---from the agenda. (default: `{ link = true, maxlevel = 2 }`)
---@field clockreport_parameters? table<string, any>
---Text above the clock report (org-agenda-clock-report-header). (default: `nil`)
---@field clock_report_header? string
---What the clock check (`vc`) reports (org-agenda-clock-consistency-checks).
---@field clock_consistency_checks? org.Config.Agenda.ClockChecks
---Start in entry text mode (org-agenda-start-with-entry-text-mode). (default: `false`)
---@field start_with_entry_text_mode? boolean
---Dim TODOs blocked by `enforce_todo_dependencies` / checkboxes; `"invisible"`
---hides them (org-agenda-dim-blocked-tasks). (default: `true`)
---@field dim_blocked_tasks? boolean|"invisible"

---Prefix formats per view (org-agenda-prefix-format).
---@class org.Config.Agenda.PrefixFormat
---(default: `" %i %-12:c%?-12t% s"`)
---@field agenda? string
---(default: `" %i %-12:c"`)
---@field todo? string
---(default: `" %i %-12:c"`)
---@field tags? string
---(default: `" %i %-12:c"`)
---@field search? string

---A custom bulk action (org-agenda-bulk-custom-functions).
---@class org.Config.Agenda.BulkFunction
---Called for each marked entry, with the values returned by `args`.
---@field fn fun(target: org.Target, item: org.AgendaItem, ...)
---Label in the bulk menu.
---@field desc? string
---Called once before the action; returns the extra arguments of `fn`.
---@field args? fun(): any[]

---Agenda time grid (org-agenda-time-grid).
---@class org.Config.Agenda.TimeGrid
---Show the time grid at all (org-agenda-use-time-grid). (default: `true`)
---@field enabled? boolean
---Hide the grid (same as `enabled = false`). (default: `nil`)
---@field hidden? boolean
---When to show the grid: `"daily"` in day views, `"weekly"` in all views,
---`"today"` on today's date, `"require-timed"` only on days with timed
---entries; `"remove-match"` hides grid lines at the time of an entry.
---(default: `{ "daily", "today", "require-timed" }`)
---@field type? ("daily"|"weekly"|"today"|"require-timed"|"remove-match")[]
---Grid times as HHMM integers. (default: `{ 800, 1000, 1200, 1400, 1600, 1800, 2000 }`)
---@field times? integer[]
---Text after the time of grid lines and of timed entries without an end
---time. (default: `" ┄┄┄┄┄ "`)
---@field separator? string
---Text of grid lines. (default: `"┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄"`)
---@field time_string? string

---Sorting strategies per view type (org-agenda-sorting-strategy).
---@class org.Config.Agenda.Sorting
---Date agenda views. (default: `{ "habit-down", "time-up", "urgency-down", "category-keep" }`)
---@field agenda? org.Config.Agenda.SortingStrategy[]
---TODO lists. (default: `{ "urgency-down", "category-keep" }`)
---@field todo? org.Config.Agenda.SortingStrategy[]
---Tags matches and stuck projects. (default: `{ "urgency-down", "category-keep" }`)
---@field tags? org.Config.Agenda.SortingStrategy[]
---Search views. (default: `{ "category-keep" }`)
---@field search? org.Config.Agenda.SortingStrategy[]

---Habit display options (org-habit).
---@class org.Config.Agenda.Habits
---Column where the consistency graph starts; it overwrites the rest of
---the line (org-habit-graph-column). (default: `40`)
---@field graph_column? integer
---Days before today shown in the graph (org-habit-preceding-days). (default: `21`)
---@field preceding_days? integer
---Days after today shown in the graph (org-habit-following-days). (default: `7`)
---@field following_days? integer
---Show habits in the agenda (org-habit-show-habits). (default: `true`)
---@field show_habits? boolean
---Show habits on today only, not on future days
---(org-habit-show-habits-only-for-today). (default: `true`)
---@field show_habits_only_for_today? boolean
---Show habits on today even when not yet due (org-habit-show-all-today). (default: `false`)
---@field show_all_today? boolean
---Always color DONE days green (org-habit-show-done-always-green). (default: `false`)
---@field show_done_always_green? boolean
---Past days a habit is shown instead of `scheduled_past_days`
---(org-habit-scheduled-past-days). (default: `nil`)
---@field scheduled_past_days? integer
---Graph character for today (org-habit-today-glyph). (default: `"!"`)
---@field today_glyph? string
---Graph character for done days (org-habit-completed-glyph). (default: `"*"`)
---@field completed_glyph? string

---Stuck project definition (org-stuck-projects).
---@class org.Config.Agenda.StuckProjects
---Match string selecting project headlines (see `:h org-match-syntax`). (default: `"+LEVEL=2/-DONE"`)
---@field match? string
---A project is not stuck if a heading of its subtree (itself included) has
---one of these TODO keywords; `"*"` = any not-done keyword.
---(default: `{ "TODO", "NEXT", "NEXTACTION" }`)
---@field todo_keywords? string[]
---A project is not stuck if a heading of its subtree has one of these tags;
---`"*"` = any tag. (default: `{}`)
---@field tags? string[]
---Vim regexp; a project is not stuck if its subtree text matches it. (default: `nil`)
---@field text? string

---One block of an agenda custom command. Any `org.Config.Agenda` option set
---here (e.g. `prefix_format`, `entry_types`, `todo_ignore_*`,
---`show_future_repeats`, `max_entries`, `habits`), also under its Emacs name
---(`org_agenda_entry_types`, ...), applies to this block.
---@class org.Config.Agenda.Block: org.Config.Agenda
---Block type. (default: `"agenda"`)
---@field type? org.Config.Agenda.BlockType
---Match string (see `:h org-match-syntax`) for `tags`/`tags_todo`, TODO
---keywords (`"KW1|KW2"`) for `todo`, search text for `search`, an Emacs
---regexp for `occur-tree`.
---@field match? string
---TODO keywords for a `todo` block (`"KW1|KW2"` or a list); overrides `match`.
---@field keywords? string|string[]
---Heading shown above the block; `""` for none; a function returning it
---(org-agenda-overriding-header).
---@field header? string|fun(): string
---Alias of `header`.
---@field org_agenda_overriding_header? string|fun(): string
---Span of an `agenda` block (org-agenda-span).
---@field span? org.Config.Agenda.Span
---Alias of `span`.
---@field org_agenda_span? org.Config.Agenda.Span
---First day of an `agenda` block, a date or offset like `"-3d"` (org-agenda-start-day).
---@field start_day? string
---Alias of `start_day`.
---@field org_agenda_start_day? string
---Files, directories or globs used instead of `agenda_files` (org-agenda-files).
---@field files? string|string[]
---Alias of `files`.
---@field org_agenda_files? string|string[]
---Return true to skip an entry (org-agenda-skip-function).
---@field skip? org.Config.Agenda.SkipFunction
---Alias of `skip`.
---@field org_agenda_skip_function? org.Config.Agenda.SkipFunction
---Sorting for this block (org-agenda-sorting-strategy).
---@field sorting? org.Config.Agenda.SortingStrategy[]
---Alias of `sorting`.
---@field org_agenda_sorting_strategy? org.Config.Agenda.SortingStrategy[]
---Restrict a `search` block to TODO entries.
---@field todo_only? boolean
---Tag filter that stays on, e.g. `{ "+work" }` (org-agenda-tag-filter-preset).
---@field tag_filter_preset? string[]
---Category filter that stays on (org-agenda-category-filter-preset).
---@field category_filter_preset? string[]
---Regexp filter that stays on (org-agenda-regexp-filter-preset).
---@field regexp_filter_preset? string[]
---Effort filter that stays on, e.g. `{ "+<1:00" }` (org-agenda-effort-filter-preset).
---@field effort_filter_preset? string[]

---An agenda custom command (org-agenda-custom-commands). Either a composite
---view with `types`/`blocks`, or a single block given inline (set `type` and
---the block options directly on the command). A table with none of `types`,
---`blocks` or `type` only labels a key prefix group.
---@class org.Config.Agenda.CustomCommand: org.Config.Agenda.Block
---Label shown in the dispatcher and as the view title.
---@field description? string
---Blocks of a composite view.
---@field types? org.Config.Agenda.Block[]
---Alias of `types`.
---@field blocks? org.Config.Agenda.Block[]
---Options applied to every block of a composite view (Emacs's settings list).
---@field settings? org.Config.Agenda.Block
---Alias of `settings`.
---@field options? org.Config.Agenda.Block
---Files written by `e` in the dispatcher (org-store-agenda-views): .txt,
---.html, .org or .ics.
---@field export_files? string[]

---------------------------------------------------------------------------
-- Capture
---------------------------------------------------------------------------

---Capture options.
---@class org.Config.Capture
---Templates keyed by selection key (org-capture-templates). Keys may be several
---characters long; a string value only labels the group of keys that start
---with that prefix. Setting this replaces the defaults instead of merging.
---See `:h org-capture-templates`.
---(default: `{ t = { description = "Task", template = "* TODO %?\n  %U" } }`)
---@field templates? table<string, org.Config.CaptureTemplate|string>
---Window used for the capture buffer. (default: `"float"`)
---@field window? "float"|"split"|"vsplit"|"tab"|"current"

---Context passed to a function `template`, also used for `%` expansions.
---@class org.Config.CaptureContext
---Path of the buffer capture was started from.
---@field origin_file? string
---Link to the origin location (`%l`).
---@field link? string
---Description of `link`.
---@field link_desc? string
---Formatted link with description (`%a`).
---@field annotation? string
---Initial content, e.g. the visual selection (`%i`). (default: `""`)
---@field initial string
---Date used for `%t`/`%T`/`%u`/`%U` and the datetree (from the agenda or `time_prompt`).
---@field date? table
---The target file.
---@field target_file? org.File
---@field keywords table

---A capture template (an entry of org-capture-templates). At least one of
---`template`, `type`, `target` or `file` must be set for the table to be
---treated as a template rather than a group label.
---@class org.Config.CaptureTemplate
---Menu label.
---@field description? string
---Template text with `%` expansions (see `:h org-capture-expansions`): a
---string, a list of lines, or a function returning either.
---(default: depends on `type`, e.g. `"* %?"` for entries)
---@field template? string|string[]|fun(ctx: org.Config.CaptureContext): string|string[]
---What is captured. (default: `"entry"`)
---@field type? "entry"|"item"|"checkitem"|"table-line"|"plain"
---Target file (relative to `org_directory`), `"clock"` for the clocked task,
---or a function returning either. (default: `default_notes_file`)
---@field target? string|"clock"|fun(): string
---Alias of `target`.
---@field file? string|"clock"|fun(): string
---Insert under the headline with this title, created when missing (file+headline).
---@field headline? string
---Outline path, a list or a `"A/B"` string; missing nodes are created (file+olp).
---@field olp? string|string[]
---Insert under the entry with this ID (id). Also locates the file when no `target` is set.
---@field id? string
---Vim regexp; insert after the first line that matches (file+regexp).
---@field regexp? string
---Called in the target buffer; returns the line of the headline to insert
---under, or nil for top level (function).
---@field func? fun(bufnr: integer): integer?
---Alias of `func`.
---@field ["function"]? fun(bufnr: integer): integer?
---File the entry in a date tree (file+datetree), under the location above if any.
---@field datetree? boolean|{ tree_type?: "day"|"week"|"month" }
---Date tree type when `datetree = true`. (default: `"day"`)
---@field tree_type? "day"|"week"|"month"
---Insert as the first child / at the top instead of the end (:prepend).
---@field prepend? boolean
---Blank lines before and after the captured text (:empty-lines). (default: `0`)
---@field empty_lines? integer
---Blank lines before the captured text (:empty-lines-before).
---@field empty_lines_before? integer
---Blank lines after the captured text (:empty-lines-after).
---@field empty_lines_after? integer
---Properties added to a captured entry.
---@field properties? table<string, string>
---Store without opening the capture window (:immediate-finish).
---@field immediate_finish? boolean
---Jump to the captured entry after finishing (:jump-to-captured).
---@field jump_to_captured? boolean
---Clock the captured entry while capturing (:clock-in): the running clock
---stops when the capture starts, and the capture time is logged as a CLOCK
---line when it ends.
---@field clock_in? boolean
---With `clock_in`, keep the clock running on the captured entry (:clock-keep).
---@field clock_keep? boolean
---With `clock_in`, clock the interrupted task in again when the capture ends
---or is aborted (:clock-resume). `clock_keep` wins over it.
---@field clock_resume? boolean
---Ask for the date used by `%t`/`%T`/`%u`/`%U` and the datetree (:time-prompt).
---@field time_prompt? boolean
---Don't save the target file after capturing (:no-save).
---@field no_save? boolean
---Called with the capture buffer before its text is read (:prepare-finalize).
---@field prepare_finalize? fun(bufnr: integer)
---Called in the target before saving, with the captured line (:before-finalize).
---@field before_finalize? fun(bufnr: integer, lnum: integer)
---Called when the capture is done, with the captured line (:after-finalize).
---@field after_finalize? fun(bufnr: integer, lnum: integer)

---------------------------------------------------------------------------
-- Refile
---------------------------------------------------------------------------

---Refile options.
---@class org.Config.Refile
---Deepest headline level offered as a target (without `targets`). (default: `3`)
---@field max_level? integer
---How targets are labelled (org-refile-use-outline-path): `"file"` (or
---`"full-file-path"`) = `file.org/Parent/Child`, `true` = `Parent/Child`,
---`false` = the title plus the file name. (default: `"file"`)
---@field use_outline_path? "file"|"full-file-path"|boolean
---Allow typing a new path like `file.org/Parent/New` to create missing parents
---(org-refile-allow-creating-parent-nodes). (default: `false`)
---@field allow_creating_parent_nodes? boolean
---Also offer targets in the current file (without `targets`). (default: `true`)
---@field include_current_file? boolean
---Target specs like org-refile-targets; replaces `max_level` /
---`include_current_file` when non-empty. See `:h org-refile`. (default: `{}`)
---@field targets? org.Config.RefileTargetSpec[]
---Return false to drop a target (org-refile-target-verify-function). (default: `nil`)
---@field verify? fun(headline: org.Headline): boolean
---Log refiling in the entry's logbook (org-log-refile). (default: `false`)
---@field log? false|"time"|"note"
---Refile as the first child instead of the last (org-reverse-note-order). (default: `false`)
---@field reverse_note_order? boolean

---A refile target spec (an entry of org-refile-targets).
---@class org.Config.RefileTargetSpec
---Where targets come from: `"agenda"` (agenda files), `"current"` (the current
---file), a path/directory/glob, a list of them, or a function returning any of
---these. (default: `"current"`)
---@field files? "agenda"|"current"|string|string[]|fun(): (string|string[]|nil)
---Only headlines up to this level (:maxlevel).
---@field max_level? integer
---Alias of `max_level`.
---@field maxlevel? integer
---Only headlines at exactly this level (:level).
---@field level? integer
---Only headlines with this tag (:tag).
---@field tag? string
---Only headlines with this TODO keyword (:todo).
---@field todo? string
---Only headlines matching this Vim regexp (:regexp).
---@field regexp? string

---Clock check settings (org-agenda-clock-consistency-checks). Durations are
---"H:MM" strings or minutes.
---@class org.Config.Agenda.ClockChecks
---Report clocks longer than this. (default: `"10:00"`)
---@field max_duration? string|integer
---Report clocks shorter than this. (default: `0`)
---@field min_duration? string|integer
---Report gaps between clocks longer than this. (default: `"0:05"`)
---@field max_gap? string|integer
---Times of day that make a gap fine when it contains one (night, lunch).
---(default: `{ "4:00" }`)
---@field gap_ok_around? (string|integer)[]
