---@meta

---A tag comparator of `tags_sort_function`, or the name of a built-in one.
---@alias org.TagsSortFunction (fun(a: string, b: string): boolean)|"hierarchy"|"string<"|"string>"

---Options for `require("org").setup()`. Every field is optional: dict options
---are merged key by key into the defaults, lists replace the default list.
---@class org.Config
---Base directory for org files; relative paths are resolved against it.
---(default: `"~/org"`)
---@field org_directory? string
---Files, directories and globs scanned by the agenda, refile and id lookups.
---Directories are scanned recursively for `*.org` files. A single string is
---also accepted. (Emacs `org-agenda-files`, default: `{ "~/org/**/*.org" }`)
---@field agenda_files? string|string[]
---Default target for capture templates without a `target`.
---(Emacs `org-default-notes-file`, default: `"~/.notes"`)
---@field default_notes_file? string
---TODO keyword sequences, like Emacs `org-todo-keywords`. Each string is one
---sequence: `"TODO(t) NEXT(n!) | DONE(d@/!)"`; `(k)` is a fast-selection key,
---`!` logs a timestamp, `@` asks for a note, `/x` is the flag used when
---leaving the state. A flat list with a `"|"` element (or a single string)
---is also accepted. `{ type = "Fred Sara | DONE" }` is a type sequence
---(Emacs `(type ...)`, `#+TYP_TODO:`). (default: `{ "TODO | DONE" }`)
---@field todo_keywords? string|(string|{ type?: string, sequence?: string })[]
---State a repeating task returns to when marked done: `nil` = the first
---keyword of its sequence, `true` = the state it had before, or a keyword.
---The `REPEAT_TO_STATE` property overrides it.
---(Emacs `org-todo-repeat-to-state`, default: `nil`)
---@field todo_repeat_to_state? true|string
---Tag changes on TODO state changes. Keys are keywords, `"todo"`, `"done"`
---or `""` (no keyword); values map tags to `true` (add) / `false` (remove):
---`{ CANCELLED = { CANCELLED = true }, done = { WAITING = false } }`.
---(Emacs `org-todo-state-tags-triggers`, default: `{}`)
---@field todo_state_tags_triggers? table<string, table<string, boolean>>
---Block marking an entry DONE while its children are not DONE.
---(Emacs `org-enforce-todo-dependencies`, default: `false`)
---@field enforce_todo_dependencies? boolean
---Block marking an entry DONE while it has unchecked checkboxes.
---(Emacs `org-enforce-todo-checkbox-dependencies`, default: `false`)
---@field enforce_todo_checkbox_dependencies? boolean
---Functions that can block a TODO state change. Each receives
---`{ type = "todo-state-change", from, to, bufnr, lnum }` and blocks the
---change by returning `false`. (Emacs `org-blocker-hook`, default: `{}`)
---@field todo_blockers? (fun(change: table): boolean?)[]
---Functions receiving the new and old state (nil for none); the first
---string returned becomes the new state (`""` = no keyword). Also asked for
---the keyword of M-S-RET (old is nil). (Emacs `org-todo-get-default-hook`,
---default: `{}`)
---@field todo_get_default_hooks? (fun(new: string?, old: string?): string?)[]
---Functions called with the numbers of done and not-done children and the
---ancestor `{ bufnr, lnum }` for each ancestor whose TODO statistics cookie
---is updated after a state change. (Emacs
---`org-after-todo-statistics-hook`, default: `{}`)
---@field after_todo_statistics_hooks? (fun(n_done: integer, n_not_done: integer, target: table))[]
---Functions called with the changed entry `{ bufnr, lnum }` whenever TODO
---statistics are updated, even without a cookie. (Emacs
---`org-todo-statistics-hook`, default: `{}`)
---@field todo_statistics_hooks? (fun(target: table))[]
---C-c C-t opens the fast-selection menu when keywords have keys; `false`
---always cycles. (Emacs `org-use-fast-todo-selection`, default: `"auto"`)
---@field use_fast_todo_selection? "auto"|false
---<S-Left>/<S-Right> on a headline are real state changes (logged and
---blocked); `false` changes the keyword without logging or blocking.
---(Emacs `org-treat-S-cursor-todo-selection-as-state-change`, default: `true`)
---@field treat_S_cursor_todo_selection_as_state_change? boolean
---M-S-RET / C-S-RET set the new heading's keyword as a logged state change.
---(Emacs `org-treat-insert-todo-heading-as-state-change`, default: `false`)
---@field treat_insert_todo_heading_as_state_change? boolean
---Which child headlines statistics cookies count: `true` (entries with a
---TODO keyword), `"all-headlines"`, a list of keywords (plus done ones) or
---`{ todo_keywords, done_keywords }`; `false` stops updating cookies on
---state changes. (Emacs `org-provide-todo-statistics`, default: `true`)
---@field provide_todo_statistics? boolean|"all-headlines"|string[]|string[][]
---Statistics cookies count direct children only; `false` counts the whole
---subtree. (Emacs `org-hierarchical-todo-statistics`, default: `true`)
---@field hierarchical_todo_statistics? boolean
---Keep `CLOSED:` when the TODO keyword is removed.
---(Emacs `org-closed-keep-when-no-todo`, default: `false`)
---@field closed_keep_when_no_todo? boolean
---Logging when an entry is marked DONE: `false`, `"time"` (add `CLOSED:`)
---or `"note"` (`CLOSED:` plus a note). (Emacs `org-log-done`, default: `false`)
---@field log_done? false|"time"|"note"
---`CLOSED:` records the time too; `false` records the date only.
---(Emacs `org-log-done-with-time`, default: `true`)
---@field log_done_with_time? boolean
---Logging when a repeating task is marked done.
---(Emacs `org-log-repeat`, default: `"time"`)
---@field log_repeat? false|"time"|"note"
---Logging when SCHEDULED is changed.
---(Emacs `org-log-reschedule`, default: `false`)
---@field log_reschedule? false|"time"|"note"
---Logging when DEADLINE is changed.
---(Emacs `org-log-redeadline`, default: `false`)
---@field log_redeadline? false|"time"|"note"
---Ask for a note when clocking out.
---(Emacs `org-log-note-clock-out`, default: `false`)
---@field log_note_clock_out? boolean
---Drawer for state changes, notes and clock lines: a drawer name, `true`
---(= `"LOGBOOK"`) or `false` (no drawer).
---(Emacs `org-log-into-drawer`, default: `false`)
---@field log_into_drawer? string|boolean
---Put the newest log entries first.
---(Emacs `org-log-states-order-reversed`, default: `true`)
---@field log_states_order_reversed? boolean
---Without a log drawer, notes go after the clock lines and drawers that
---follow the headline. (Emacs `org-log-state-notes-insert-after-drawers`,
---default: `false`)
---@field log_state_notes_insert_after_drawers? boolean
---Type log notes in a small `*Org Note*` split (<C-c><C-c> stores,
---<C-c><C-k> cancels) like Emacs `org-add-log-note`; `false` asks with a
---one-line prompt. (default: `true`)
---@field note_buffer? boolean
---Headings of log notes, by purpose (`done`, `state`, `note`,
---`reschedule`, `delschedule`, `redeadline`, `deldeadline`, `refile`,
---`clock-out`). `%t`/`%T` inactive/active timestamp, `%d`/`%D` date only,
---`%s`/`%S` new/old state or date (quoted), `%u`/`%U` user name; `%-12s`
---pads. (Emacs `org-log-note-headings`)
---@field log_note_headings? table<string, string>
---Hours after midnight that still count as the previous day for "today"
---in the agenda and date prompts. (Emacs `org-extend-today-until`,
---default: `0`)
---@field extend_today_until? integer
---With `extend_today_until`, record `CLOSED:` and log times before that
---hour as 23:59 of the previous day.
---(Emacs `org-use-effective-time`, default: `false`)
---@field use_effective_time? boolean
---`CLOSED:` and log notes record the last clock-out time of the subtree.
---(Emacs `org-use-last-clock-out-time-as-effective-time`, default: `false`)
---@field use_last_clock_out_time_as_effective_time? boolean
---In Visual mode, C-c C-t, C-c C-s, C-c C-d and the archiving commands act
---on every headline of the selection: `true`, `"start-level"` (only
---headlines of the first one's level) or `false`; a match string acts like
---`true`, as in Emacs 9.8.
---(Emacs `org-loop-over-headlines-in-active-region`, default: `true`)
---@field loop_over_headlines_in_active_region? boolean|"start-level"|string
---Highest priority letter. (Emacs `org-priority-highest`, default: `"A"`)
---@field priority_highest? string
---Lowest priority letter. (Emacs `org-priority-lowest`, default: `"C"`)
---@field priority_lowest? string
---Priority of entries without a cookie.
---(Emacs `org-priority-default`, default: `"B"`)
---@field priority_default? string
---`false` disables the priority commands.
---(Emacs `org-priority-enable-commands`, default: `true`)
---@field priority_enable_commands? boolean
---Shifting a headline without cookie starts at the default priority;
---`false` starts one step past it.
---(Emacs `org-priority-start-cycle-with-default`, default: `true`)
---@field priority_start_cycle_with_default? boolean
---Function receiving the headline line and returning the priority value
---used for sorting (1000 per level). (Emacs
---`org-priority-get-priority-function`, default: `nil`)
---@field priority_get_priority_function? fun(line: string): number
---Tag groups (`[ GTD : Control Persp ]`) also match their members in tag
---searches and sparse trees; toggled by `toggle_tags_groups`.
---(Emacs `org-group-tags`, default: `true`)
---@field group_tags? boolean
---Fast tag selection exits after one change: `false`, `true`, or `"expert"`
---(no menu window until <C-c>).
---(Emacs `org-fast-tag-selection-single-key`, default: `false`)
---@field fast_tag_selection_single_key? boolean|"expert"
---Show the TODO keywords with fast keys in the fast tag selection menu.
---(Emacs `org-fast-tag-selection-include-todo`, default: `false`)
---@field fast_tag_selection_include_todo? boolean
---Fast tag selection: `"auto"` when some tag has a key, `true` always,
---`false` never. (Emacs `org-use-fast-tag-selection`, default: `"auto"`)
---@field use_fast_tag_selection? "auto"|boolean
---How many tags fast selection shows, counting the tags with keys and the
---tags in groups (always shown). (Emacs
---`org-fast-tag-selection-maximum-tags`, default: `56`)
---@field fast_tag_selection_maximum_tags? integer
---Tag completion offers the tags of every agenda file instead of the
---current buffer's. (Emacs `org-complete-tags-always-offer-all-agenda-tags`,
---default: `false`)
---@field complete_tags_always_offer_all_agenda_tags? boolean
---Global tag list offered for completion and fast tag selection. Strings
---may contain fast keys (`"work(w)"`) and `"{"` ... `"}"` elements for
---mutually exclusive groups. A file's `#+TAGS:` replaces it.
---(Emacs `org-tag-alist`, default: `{}`)
---@field tags? string[]
---Tags always available, in the format of `tags`, placed before `tags` or
---`#+TAGS:`; `#+STARTUP: noptag` turns them off in a file.
---(Emacs `org-tag-persistent-alist`, default: `{}`)
---@field tags_persistent? string[]
---Comparator (or list of comparators, the next one breaking ties) sorting
---the tags set on a headline and the agenda's tag sorting; "hierarchy",
---"string<" and "string>" are org-tags-sort-hierarchy, org-string< and
---org-string>. (Emacs `org-tags-sort-function`, default: `nil`)
---@field tags_sort_function? org.TagsSortFunction|org.TagsSortFunction[]
---Column tags are aligned to; negative = right-align so tags end at that
---column. (Emacs `org-tags-column`, default: `-77`)
---@field tags_column? integer
---Realign tags after edits. (Emacs `org-auto-align-tags`, default: `true`)
---@field auto_align_tags? boolean
---Toggling ORDERED also toggles a tag: `true` (ORDERED) or a tag name.
---(Emacs `org-track-ordered-property-with-tag`, default: `false`)
---@field track_ordered_property_with_tag? boolean|string
---Whether tags are inherited by sub-headings: `true`, `false`, a list of the
---tags that inherit, or a regexp matching them.
---(Emacs `org-use-tag-inheritance`, default: `true`)
---@field use_tag_inheritance? boolean|string[]|string
---Tags that are never inherited.
---(Emacs `org-tags-exclude-from-inheritance`, default: `{}`)
---@field tags_exclude_from_inheritance? string[]
---Property inheritance: `true`, `false`, a list of property names that
---inherit, or a regexp matching them (ignoring case).
---(Emacs `org-use-property-inheritance`, default: `false`)
---@field use_property_inheritance? boolean|string[]|string
---Format of `:NAME: value` lines written to property drawers.
---(Emacs `org-property-format`, default: `"%-10s %s"`)
---@field property_format? string
---Properties that apply to every entry, e.g.
---`{ Effort_ALL = "0:10 0:30 1:00 2:00" }`.
---(Emacs `org-global-properties`, default: `{}`)
---@field global_properties? table<string, string>
---Functions adjusting values given to `set_property`, by property name
---(ignoring case); they get the value and `{ bufnr, lnum }`.
---(Emacs `org-properties-postprocess-alist`, default: `{}`)
---@field properties_postprocess? table<string, fun(value: string, target: table): string>
---Separators joining `PROP` and `PROP+` values: `{ { names_or_regexp,
---separator }, ... }`; a space otherwise.
---(Emacs `org-property-separators`, default: `{}`)
---@field property_separators? { [1]: string[]|string, [2]: string }[]
---Properties hidden and shown by toggle_custom_properties_visibility.
---(Emacs `org-custom-properties`, default: `{}`)
---@field custom_properties? string[]
---Constants for table formulas (`$name`). `#+CONSTANTS:` lines in a file
---take precedence. (Emacs `org-table-formula-constants`, default: `{}`)
---@field table_formula_constants? table<string, string|number>
---How `table_copy_down` (<S-CR>) increments numbers and dates: `true` (by
---the difference to the field above, else 1), a number (fixed step) or
---`false`. (Emacs `org-table-copy-increment`, default: `true`)
---@field table_copy_increment? boolean|number
---A field formula writing beyond the last column: `false` (error), `true`
---(add columns), `"warn"` (add them and warn) or `"prompt"` (ask). Column
---formulas always add columns.
---(Emacs `org-table-formula-create-columns`, default: `false`)
---@field table_formula_create_columns? boolean|"warn"|"prompt"
---Ask before rewriting `#+TBLFM` references after inserting, deleting or
---moving rows and columns. (Emacs `org-table-fix-formulas-confirm`,
---default: `false`)
---@field table_fix_formulas_confirm? boolean
---Output of the `t` formula flag.
---(Emacs `org-table-duration-custom-format`, default: `"hours"`)
---@field table_duration_custom_format? "hours"|"minutes"|"seconds"|"days"
---Pad hours to two digits in `T` / `U` durations (`01:30:00`).
---(Emacs `org-table-duration-hour-zero-padding`, default: `true`)
---@field table_duration_hour_zero_padding? boolean
---Typing `=formula` or `:=formula` into a field installs it as a column or
---field formula. (Emacs `org-table-formula-evaluate-inline`, default: `true`)
---@field table_formula_evaluate_inline? boolean
---Minimum fraction of numbers in a column for it to be right-aligned.
---(Emacs `org-table-number-fraction`, default: `0.5`)
---@field table_number_fraction? number
---Emacs regexp of the cells that count as numbers for right alignment.
---(Emacs `org-table-number-regexp`, default: Emacs's)
---@field table_number_regexp? string
---Realign the table on <Tab>, <S-Tab>, <CR> and when leaving Insert mode.
---(Emacs `org-table-automatic-realign`, default: `true`)
---@field table_automatic_realign? boolean
---<Tab> jumps over an hline instead of adding a row before it.
---(Emacs `org-table-tab-jumps-over-hlines`, default: `true`)
---@field table_tab_jumps_over_hlines? boolean
---Typing right after <Tab>, <S-Tab> or <CR> replaces the field's text.
---(Emacs `org-table-auto-blank-field`, default: `true`)
---@field table_auto_blank_field? boolean
---Recalculate a `#` row on <Tab>, <CR> and C-c C-c.
---(Emacs `org-table-allow-automatic-line-recalculation`, default: `true`)
---@field table_allow_automatic_line_recalculation? boolean
---Size of a new table, "COLUMNSxROWS". (Emacs `org-table-default-size`, default: `"5x2"`)
---@field table_default_size? string
---Largest region converted to a table.
---(Emacs `org-table-convert-region-max-lines`, default: `999`)
---@field table_convert_region_max_lines? integer
---Format of formula results, `%s` being the value.
---(Emacs `org-table-formula-field-format`, default: `"%s"`)
---@field table_formula_field_format? string
---Replace `$name` names in formulas computed by C-c = or typed inline.
---(Emacs `org-table-formula-use-constants`, default: `true`)
---@field table_formula_use_constants? boolean
---Relative row references crossing an hline: `true`, `false` (stop at the
---hline) or `"error"`. (Emacs `org-table-relative-ref-may-cross-hline`, default: `true`)
---@field table_relative_ref_may_cross_hline? boolean|"error"
---Calc modes of table formulas.
---(Emacs `org-calc-default-modes`, default: `{ internal_prec = 12, float_format = { "float", 8 }, angle_mode = "deg", prefer_frac = false }`)
---@field calc_default_modes? { internal_prec?: integer, float_format?: { [1]: "float"|"fix"|"sci"|"eng", [2]: integer }, angle_mode?: "deg"|"rad", prefer_frac?: boolean }
---In orgtbl-mode, typing keeps the table aligned and auto-blanks fields.
---(Emacs `orgtbl-optimized`, default: `true`)
---@field orgtbl_optimized? boolean
---Text shown at the end of a shrunk column.
---(Emacs `org-table-shrunk-column-indicator`, default: `"…"`)
---@field table_shrunk_column_indicator? string
---Shrink the columns with a width cookie of every table when a file is
---opened; `#+STARTUP: shrink` / `noshrink` override it.
---(Emacs `org-startup-shrink-all-tables`, default: `false`)
---@field startup_shrink_all_tables? boolean
---Align every table when a file is opened; `#+STARTUP: align` / `noalign`
---override it. (Emacs `org-startup-align-all-tables`, default: `false`)
---@field startup_align_all_tables? boolean
---Show the first row of a table in the winbar while it is scrolled out of
---view. (Emacs `org-table-header-line-p`, default: `false`)
---@field table_header_line_p? boolean
---Leaving the table ends follow-field mode.
---(Emacs `org-table-exit-follow-field-mode-when-leaving-table`, default: `true`)
---@field table_exit_follow_field_mode_when_leaving_table? boolean
---A1-style references (`B3`) in formulas: `"from"` accepts them when
---typed, `true` also shows them in the formula editor, `false` never.
---(Emacs `org-table-use-standard-references`, default: `"from"`)
---@field table_use_standard_references? boolean|"from"
---Translator used by `table_export` when no TABLE_EXPORT_FORMAT is set.
---(Emacs `org-table-export-default-format`, default: `"orgtbl-to-tsv"`)
---@field table_export_default_format? string
---The gnuplot program run by `table_plot`.
---(Emacs `gnuplot-program`, default: `"gnuplot"`)
---@field plot_gnuplot_program? string
---Text added to every plot script.
---(Emacs `org-plot/gnuplot-script-preamble`, default: `""`)
---@field plot_gnuplot_script_preamble? string
---Extra `set term` options, e.g. `"size 1050,650"`.
---(Emacs `org-plot/gnuplot-term-extra`, default: `""`)
---@field plot_gnuplot_term_extra? string
---Extra (or replaced) `#+PLOT: type:NAME` plot types.
---(Emacs `org-plot/preset-plot-types`, default: `{}`; 2d, 3d, grid and radar are built in)
---@field plot_preset_plot_types? table<string, { plot_func?: fun(rows: table, data_file: string, ncols: integer, opts: table, plot_str: string): string[], plot_cmd?: string, plot_str?: string, plot_pre?: string|fun(rows: table, data_file: string, ncols: integer, opts: table, plot_str: string): string?, data_dump?: fun(rows: table, data_file: string, ncols: integer, opts: table): string?, check_ind_type?: boolean }>
---Radio table templates inserted by `orgtbl_insert_radio_table`, per
---filetype (`tex`, `texinfo`, `html`, `org`); `%n` is the table name.
---(Emacs `orgtbl-radio-table-templates`)
---@field orgtbl_radio_table_templates? table<string, string>
---Column view display: `"overlay"` draws the column rows over the
---headlines of the org buffer (with the titles in the winbar), like Emacs
---`org-columns`; `"table"` shows them as a table in a split.
---(default: `"overlay"`)
---@field columns_view? "overlay"|"table"
---Extra column view summary operators: operator → `fun(values: string[],
---format?: string): string`. (Emacs `org-columns-summary-types`,
---default: `{}`)
---@field columns_summary_types? table<string, fun(values: string[], format?: string): string>
---Change values shown in column view and columnview blocks: return the
---new text, or nil to keep the value.
---(Emacs `org-columns-modify-value-for-display-function`, default: `nil`)
---@field columns_modify_value_for_display_function? fun(prop: string, value: string): string?
---Write columnview dynamic blocks with this function instead of the
---default table; it gets the rows (lists of cells, `"hline"` for rules)
---and the block parameters and returns the lines.
---(Emacs `org-columns-dblock-formatter`, default: `nil`)
---@field columns_dblock_formatter? fun(rows: (string[]|string)[], params: table): string[]
---Values <S-Right> cycles through in checkbox columns.
---(Emacs `org-columns-checkbox-allowed-values`, default: `{ "[ ]", "[X]" }`)
---@field columns_checkbox_allowed_values? string[]
---Text ending a truncated column view field.
---(Emacs `org-columns-ellipses`, default: `".."`)
---@field columns_ellipses? string
---Property holding effort estimates.
---(Emacs `org-effort-property`, default: `"Effort"`)
---@field effort_property? string
---Format of durations in clock tables, clock sums, column summaries and
---efforts: `"d h:mm"` writes `1d 2:30` from one day on, `"h:mm"` writes
---`26:30`, `"h:mm:ss"` `26:30:00`; a list of `{ unit, required }` entries,
---`{ "special", "h:mm"|"h:mm:ss"|decimals }` and `"compact"` builds unit
---strings like `1d 2h 30min` or `26.50h`.
---(Emacs `org-duration-format`, default: `"d h:mm"`)
---@field duration_format? "d h:mm"|"h:mm"|"h:mm:ss"|table
---Minutes per duration unit, e.g. `{ d = 480 }` for 8-hour days; new units
---may be added. (Emacs `org-duration-units`, default:
---`{ min = 1, h = 60, d = 1440, w = 10080, m = 43200, y = 525960 }`)
---@field duration_units? table<string, number>
---Column view format used when a file has no `#+COLUMNS:`.
---(Emacs `org-columns-default-format`,
---default: `"%25ITEM %TODO %3PRIORITY %TAGS"`)
---@field columns_default_format? string
---Initial visibility when a file is opened; `#+STARTUP:` overrides it.
---(Emacs `org-startup-folded`, default: `"showeverything"`)
---@field startup_folded? "overview"|"content"|"showall"|"showeverything"|"nofold"|"show2levels"|"show3levels"|"show4levels"|"show5levels"
---Fold drawers when a file is opened (`#+STARTUP: hidedrawers` /
---`nohidedrawers`). (Emacs `org-hide-drawer-startup`, default: `true`)
---@field hide_drawer_startup? boolean
---Fold `#+begin_...` blocks when a file is opened (`#+STARTUP: hideblocks`).
---(Emacs `org-hide-block-startup`, default: `false`)
---@field hide_block_startup? boolean
---Turn on the Beamer editing mode (`:Org beamer_mode`) when a file is opened
---(`#+STARTUP: beamer`). (Emacs `org-startup-with-beamer-mode`, default: `false`)
---@field startup_with_beamer_mode? boolean
---Let visibility cycling open subtrees tagged `:ARCHIVE:`.
---(Emacs `org-cycle-open-archived-trees`, default: `false`)
---@field cycle_open_archived_trees? boolean
---Sparse trees open subtrees tagged `:ARCHIVE:` to show matches in them.
---(Emacs `org-sparse-tree-open-archived-trees`, default: `false`)
---@field sparse_tree_open_archived_trees? boolean
---Dates the before/after/range sparse trees look at; `nil` = SCHEDULED
---and DEADLINE. (Emacs `org-sparse-tree-default-date-type`, default: `nil`)
---@field sparse_tree_default_date_type? "all"|"active"|"inactive"|"scheduled"|"deadline"|"closed"|nil
---Heading that collects footnote definitions (created when missing);
---`false` puts each definition at the end of the reference's section.
---(Emacs `org-footnote-section`, default: `"Footnotes"`)
---@field footnote_section? string|false
---Indent body text, planning lines and drawers to the headline level;
---`"headline-data"` indents only planning lines and the property and log
---drawers. (Emacs `org-adapt-indentation`, default: `false`)
---@field adapt_indentation? boolean|"headline-data"
---New day nodes of date trees get a time stamp of their date.
---(Emacs `org-datetree-add-timestamp`, default: `false`)
---@field datetree_add_timestamp? false|"active"|"inactive"
---Indentation added to src block contents in the edit buffer.
---(Emacs `org-edit-src-content-indentation`, default: `2`)
---@field edit_src_content_indentation? integer
---Keep src block lines as written: no common indentation is removed for
---evaluation, tangling or the edit buffer (the `-i` switch does it per
---block). (Emacs `org-src-preserve-indentation`, default: `false`)
---@field src_preserve_indentation? boolean
---Show "Edit, then exit with ... or abort with ..." in the winbar of edit
---buffers. (Emacs `org-edit-src-persistent-message`, default: `true`)
---@field edit_src_persistent_message? boolean
---Write an edit buffer back to the Org buffer after this many seconds
---without changes; `0` = never.
---(Emacs `org-edit-src-auto-save-idle-delay`, default: `0`)
---@field edit_src_auto_save_idle_delay? number
---Auto-save the contents of edit buffers to an `org-src-XXXXXX-%Y-%d-%m.txt`
---file next to the Org file.
---(Emacs `org-edit-src-turn-on-auto-save`, default: `false`)
---@field edit_src_turn_on_auto_save? boolean
---Ask before going back to the existing edit buffer of a block (`n`
---discards it and opens a new one); `false` = go back at once.
---(Emacs `org-src-ask-before-returning-to-edit-buffer`, default: `true`)
---@field src_ask_before_returning_to_edit_buffer? boolean
---Filetype, or a function of the buffer, for the edit buffer of `: `
---fixed-width areas. (Emacs `org-edit-fixed-width-region-mode`, default: `nil`)
---@field edit_fixed_width_region_mode? string|fun(bufnr: integer)
---Filetype of the edit buffer and highlighting of src blocks by language,
---merged with the defaults; `""` = none. (Emacs `org-src-lang-modes`,
---default: `{ C = "c", ["C++"] = "cpp", elisp = "lisp", shell = "sh", ... }`)
---@field src_lang_modes? table<string, string>
---TAB on a src block line indents it with the language's indentation.
---(Emacs `org-src-tab-acts-natively`, default: `true`)
---@field src_tab_acts_natively? boolean
---Default coderef label format; `-l "fmt"` overrides it per block.
---(Emacs `org-coderef-label-format`, default: `"(ref:%s)"`)
---@field coderef_label_format? string
---Text appended to folded headlines. (Emacs `org-ellipsis`, default: `"..."`)
---@field ellipsis? string
---Entities of your own, taking precedence over the built-in ones:
---`{ name, latex, latex_math, html, ascii, latin1, utf8 }` entries.
---(Emacs `org-entities-user`, default: `{}`)
---@field entities_user? { [1]: string, [2]: string, [3]: boolean, [4]: string, [5]: string, [6]: string, [7]: string }[]
---Blank line before new headings / list items. A single value applies to
---headings. (Emacs `org-blank-before-new-entry`,
---default: `{ heading = "auto", plain_list_item = "auto" }`)
---@field blank_before_new_entry? org.Config.BlankBeforeNewEntry|boolean|"auto"
---M-RET in Insert mode splits the line at the cursor: `true`, `false`, or
---per context `{ headline = false, item = true, default = true }`.
---(Emacs `org-M-RET-may-split-line`, default: `true`)
---@field meta_return_split_line? boolean|{ headline?: boolean, item?: boolean, default?: boolean }
---Clones made by clone_subtree lose their ID instead of getting a new one.
---(Emacs `org-clone-delete-id`, default: `false`)
---@field clone_delete_id? boolean
---Only odd levels: promotion and demotion add or remove two stars
---(`#+STARTUP: odd` / `oddeven`). (Emacs `org-odd-levels-only`, default: `false`)
---@field odd_levels_only? boolean
---Named key functions for sorting by function (`f`), called with the
---headline (or list item) and its lines. (default: `{}`)
---@field sort_functions? table<string, fun(entry: any, lines: string[]): any>
---Names of the bookmarks set by capture (`last_capture`) and refile
---(`last_refile`), saved across sessions; `false` sets none.
---(Emacs `org-bookmark-names-plist`)
---@field bookmark_names? { last_capture?: string|false, last_refile?: string|false, last_capture_marker?: string|false }
---`buffer_goto` interface: `"outline"` browses a copy of the buffer in
---overview (<CR> jumps), `"outline-path-completion"` picks a headline by its
---path. A count uses the other one. (Emacs `org-goto-interface`,
---default: `"outline"`)
---@field goto_interface? "outline"|"outline-path-completion"
---Deepest headlines offered by the completion interface of `buffer_goto`.
---(Emacs `org-goto-max-level`, default: `5`)
---@field goto_max_level? integer
---In the outline interface of `buffer_goto`, typing searches the headlines;
---when `false`, n p f b u move and q quits. (Emacs `org-goto-auto-isearch`,
---default: `true`)
---@field goto_auto_isearch? boolean
---How sorting (entries, lists, tables, the agenda) compares text:
---`"collate"` with the collation locale (`:language collate`; character
---codes on macOS, like Emacs's string-collate-lessp there), `"fallback"`
---by character code, or `function(a, b, ignore_case)` returning `a < b`.
---(Emacs `org-sort-function`, default: `"collate"`, string-collate-lessp)
---@field sort_function? "collate"|"fallback"|fun(a: string, b: string, ignore_case?: boolean): boolean
---TAB on a list item folds its children and text; `"integrate"` also
---treats list items as children of their headline when cycling it.
---(Emacs `org-cycle-include-plain-lists`, default: `true`)
---@field cycle_include_plain_lists? boolean|"integrate"
---Plain list options (Emacs `org-list-*`).
---@field lists? org.Config.Lists
---Where TAB outside headlines, items, drawers and blocks indents the line:
---`true` (everywhere), `"white"`, `"whitestart"`, `"exc-hl-bol"` or `false`
---(then it cycles the entry). (Emacs `org-cycle-emulate-tab`, default: `true`)
---@field cycle_emulate_tab? boolean|"white"|"whitestart"|"exc-hl-bol"
---Blank lines needed at the end of a subtree for one of them to stay
---visible when it is folded. (Emacs `org-cycle-separator-lines`, default: `2`)
---@field cycle_separator_lines? integer
---Typing on hidden lines: `false`, `"error"`, `"show"`, `"show-and-error"`
---or `"smart"`. (Emacs `org-fold-catch-invisible-edits`, default: `"smart"`)
---@field catch_invisible_edits? false|"error"|"show"|"show-and-error"|"smart"
---The edits `catch_invisible_edits` checks, by command: `self_insert`,
---`delete_backward_char` (<BS>), `delete_char` (<Del>), `return` (<CR>) or
---an action name, each `"insert"`, `"delete"` or `"delete-backward"`.
---(Emacs `org-fold-catch-invisible-edits-commands`)
---@field catch_invisible_edits_commands? table<string, "insert"|"delete"|"delete-backward"|false>
---TAB at the very start of the buffer, not on a headline, cycles globally.
---(Emacs `org-cycle-global-at-bob`, default: `false`)
---@field cycle_global_at_bob? boolean
---Deepest level cycled as a headline by TAB; `nil` = all.
---(Emacs `org-cycle-max-level`, default: `nil`)
---@field cycle_max_level? integer
---TAB on an entry without children skips the CHILDREN state.
---(Emacs `org-cycle-skip-children-state-if-no-children`, default: `true`)
---@field cycle_skip_children_state_if_no_children? boolean
---How much is shown around a location reached by a jump, per context, or
---one span for all. (Emacs `org-fold-show-context-detail`)
---@field fold_show_context_detail? string|boolean|table<string, "minimal"|"local"|"ancestors"|"ancestors-full"|"lineage"|"tree"|"canonical">
---Sparse-tree regexp searches ignore case: `true`, `false` or `"smart"`.
---(Emacs `org-occur-case-fold-search`, default: `true`)
---@field occur_case_fold_search? boolean|"smart"
---Changes remove sparse-tree and clock_display highlights.
---(Emacs `org-remove-highlights-with-change`, default: `true`)
---@field remove_highlights_with_change? boolean
---`beginning_of_line` / `end_of_line` on headlines and items: `true` goes
---to the title start / before the tags first, `"reversed"` on a repeated key;
---`{ a = ..., e = ... }` sets each key. (Emacs `org-special-ctrl-a/e`,
---default: `false`)
---@field special_ctrl_a_e? boolean|"reversed"|{ a?: boolean|"reversed", e?: boolean|"reversed" }
---`kill_line` in a headline kills up to the tags, then the tags.
---(Emacs `org-special-ctrl-k`, default: `false`)
---@field special_ctrl_k? boolean
---`kill_line` on a folded headline: `false` kills the hidden subtree too,
---`true` asks, `"error"` refuses. (Emacs `org-ctrl-k-protect-subtree`,
---default: `false`)
---@field ctrl_k_protect_subtree? boolean|"error"
---Setting the org filetype on an empty file not named `*.org` inserts the
---Emacs mode line `#    -*- mode: org -*-`, so it opens as org from then on.
---(Emacs `org-insert-mode-line-in-empty-file`, default: `false`)
---@field insert_mode_line_in_empty_file? boolean
---New headlines from `meta_return` and the other insertions go after the
---current subtree, like `insert_heading`.
---(Emacs `org-insert-heading-respect-content`, default: `false`)
---@field insert_heading_respect_content? boolean
---Promoting a level-1 headline turns its `* ` into `# ` instead of refusing.
---(Emacs `org-allow-promoting-top-level-subtree`, default: `false`)
---@field allow_promoting_top_level_subtree? boolean
---Keep the Visual selection after `meta_left` / `meta_right` / `meta_up` /
---`meta_down`: `true`, `false` or per command. (Emacs `org-edit-keep-region`,
---default: all four `true`)
---@field edit_keep_region? boolean|{ meta_left?: boolean, meta_right?: boolean, meta_up?: boolean, meta_down?: boolean }
---`p` / `P` of whole subtrees folds them, unless that would hide the text
---after them. (Emacs `org-yank-folded-subtrees`, default: `true`)
---@field yank_folded_subtrees? boolean
---`p` / `P` of whole subtrees adjusts their level to the visible headlines
---around, like paste_subtree. (Emacs `org-yank-adjusted-subtrees`,
---default: `false`)
---@field yank_adjusted_subtrees? boolean
---Single-letter commands typed in Insert mode at the start of a headline,
---or a function deciding where they apply.
---(Emacs `org-use-speed-commands`, default: `false`)
---@field use_speed_commands? boolean|fun(): boolean
---Extra or changed speed commands: an action name, a function, or `false`.
---(Emacs `org-speed-commands`, default: `{}`)
---@field speed_commands? table<string, string|fun()|false>
---Functions of a key returning the speed command it runs (an action name or
---a function) or nil, tried in order; `"org-speed-command-activate"` and
---`"org-babel-speed-command-activate"` name the built-in ones.
---(Emacs `org-speed-command-hook`)
---@field speed_command_hook? (string|fun(key: string): (string|fun())?)[]
---Headlines of this level or deeper are inline tasks; `false` = off (Emacs
---without the org-inlinetask module; 15 once it is loaded).
---(Emacs `org-inlinetask-min-level`, default: `false`)
---@field inlinetask_min_level? integer|false
---Show the first star of inline tasks as a marker.
---(Emacs `org-inlinetask-show-first-star`, default: `false`)
---@field inlinetask_show_first_star? boolean
---TODO keyword of new inline tasks.
---(Emacs `org-inlinetask-default-state`, default: `nil`)
---@field inlinetask_default_state? string
---Block types of insert_structure_template, by key; `false` removes one.
---(Emacs `org-structure-template-alist`, default: a c C e E h l q s v)
---@field structure_template_alist? table<string, string|false>
---Expand `<s` + TAB (Insert mode) into blocks and keywords.
---(the org-tempo module, default: `false`)
---@field tempo? boolean
---Keywords for tempo expansion.
---(Emacs `org-tempo-keywords-alist`, default: `{ L = "latex", H = "html", A = "ascii", i = "index" }`)
---@field tempo_keywords? table<string, string|false>
---Labels of new footnotes: `true` (fn:N), `false` (prompt), `"confirm"`,
---`"random"`, `"plain"` or `"anonymous"`; `#+STARTUP: fnauto` etc.
---(Emacs `org-footnote-auto-label`, default: `true`)
---@field footnote_auto_label? boolean|"confirm"|"random"|"plain"|"anonymous"
---Renumber and / or sort footnotes after inserting or deleting one:
---`false`, `true`, `"sort"` or `"renumber"`; `#+STARTUP: fnadjust`.
---(Emacs `org-footnote-auto-adjust`, default: `false`)
---@field footnote_auto_adjust? boolean|"sort"|"renumber"
---Define new footnotes inline (`[fn:N: text]`); `#+STARTUP: fninline`.
---(Emacs `org-footnote-define-inline`, default: `false`)
---@field footnote_define_inline? boolean
---Refill the paragraphs that lost an inline footnote when normalizing.
---(Emacs `org-footnote-fill-after-inline-note-extraction`, default: `false`)
---@field footnote_fill_after_inline_note_extraction? boolean
---Days before a deadline it starts showing up in the agenda.
---(Emacs `org-deadline-warning-days`, default: `14`)
---@field deadline_warning_days? integer
---Days a scheduled entry is hidden after its date unless it has its own
---`-Nd` delay; negative: always (org-scheduled-delay-days). (default: `0`)
---@field scheduled_delay_days? integer
---`{ rounding, step }`: minutes the current time is rounded to in date
---prompts, and the minute step of <S-Up>/<S-Down> on timestamps (a count
---steps by exactly that many minutes).
---(Emacs `org-time-stamp-rounding-minutes`, default: `{ 0, 5 }`)
---@field time_stamp_rounding_minutes? integer[]
---Date prompts read incomplete dates in the future: `true` (a past day or
---month means next month or year), `"time"` (also a past time today means
---tomorrow) or `false`. (Emacs `org-read-date-prefer-future`,
---default: `true`)
---@field read_date_prefer_future? boolean|"time"
---Date prompts show the calendar; `false` = only a "Date+time [default]: "
---prompt. (Emacs `org-read-date-popup-calendar`, default: `true`)
---@field read_date_popup_calendar? boolean
---Alias of `read_date_popup_calendar` (Emacs `org-popup-calendar-for-date-prompt`).
---@field popup_calendar_for_date_prompt? boolean
---Show what a typed date means while typing it in the calendar.
---(Emacs `org-read-date-display-live`, default: `true`)
---@field read_date_display_live? boolean
---Key of the `goto_calendar` calendar showing the agenda of its date:
---`"default"` (`c`), another key, or `false`.
---(Emacs `org-calendar-to-agenda-key`, default: `"default"`)
---@field calendar_to_agenda_key? string|false
---Key of that calendar adding a diary entry for its date to an Org
---`agenda.diary_entry_file`.
---(Emacs `org-calendar-insert-diary-entry-key`, default: `"i"`)
---@field calendar_insert_diary_entry_key? string
---`<S-Down>` makes timestamps later and `<S-Up>` earlier.
---(Emacs `org-edit-timestamp-down-means-later`, default: `false`)
---@field edit_timestamp_down_means_later? boolean
---Display timestamps with `time_stamp_custom_formats`; toggled per buffer
---by `toggle_time_stamp_overlays`, `#+STARTUP: customtime` turns it on.
---Exports of a buffer with the display on use the formats too.
---(Emacs `org-display-custom-times`, default: `false`)
---@field display_custom_times? boolean
---`{ date format, date and time format }` (Emacs `format-time-string`,
---e.g. `"%A %d %B %Y"`) of the custom timestamp display and exports;
---surrounding brackets are dropped in the buffer and kept in exports. (Emacs `org-timestamp-custom-formats`,
---default: `{ "%m/%d/%y %a", "%m/%d/%y %a %H:%M" }`)
---@field time_stamp_custom_formats? string[]
---Where `archive_subtree` sends entries: `"file::heading"`, `%s` = current
---file name. (Emacs `org-archive-location`, default: `"%s_archive::"`)
---@field archive_location? string
---Context saved as `ARCHIVE_*` properties on archived entries.
---(Emacs `org-archive-save-context-info`,
---default: `{ "time", "file", "olpath", "category", "todo", "itags" }`)
---@field archive_save_context_info? ("time"|"file"|"olpath"|"olid"|"category"|"todo"|"itags"|"ltags")[]
---Heading of the sibling used by `archive_to_sibling`.
---(Emacs `org-archive-sibling-heading`, default: `"Archive"`)
---@field archive_sibling_heading? string
---Add inherited tags to archived entries: `"infile"` (only when archiving
---within the same file), `true` or `false`.
---(Emacs `org-archive-subtree-add-inherited-tags`, default: `"infile"`)
---@field archive_subtree_add_inherited_tags? "infile"|boolean
---Archive as the first child of the archive heading instead of the last.
---(Emacs `org-archive-reversed-order`, default: `false`)
---@field archive_reversed_order? boolean
---What `archive_subtree_default` (C-c C-x C-a, the agenda's `a` and
---C-c C-x C-a) does.
---(Emacs `org-archive-default-command`, default: `"archive_subtree"`)
---@field archive_default_command? "archive_subtree"|"archive_to_sibling"|"set_tag"|fun(target: org.Target|nil)
---When `archive_subtree` saves the archive file: always, never, only from Org
---buffers or only from the agenda.
---(Emacs `org-archive-subtree-save-file-p`, default: `"from_org"`)
---@field archive_subtree_save_file? boolean|"from_org"|"from_agenda"
---Mark archived entries done: `true` (the first done keyword) or a done keyword.
---(Emacs `org-archive-mark-done`, default: `false`)
---@field archive_mark_done? boolean|string
---Text put at the top of a new archive file, `%s` = the source file; `false`
---for none. (Emacs `org-archive-file-header-format`,
---default: `"\nArchived entries from file %s\n\n"`)
---@field archive_file_header_format? string|false
---Window used for special buffers (src edit, capture, etc.).
---(default: `"float"`)
---@field win_split_mode? "float"|"split"|"vsplit"|"tab"|"current"
---Where `indirect_subtree` shows the subtree: `"other-window"` (a split),
---`"current-window"`, `"new-frame"` (a new tab each time) or
---`"dedicated-frame"` (one tab, reused; with a count a new one).
---(Emacs `org-indirect-buffer-display`, default: `"other-window"`)
---@field indirect_buffer_display? "other-window"|"current-window"|"new-frame"|"dedicated-frame"
---Border of floating windows, as accepted by `nvim_open_win()`.
---(default: `"rounded"`)
---@field win_border? "none"|"single"|"double"|"rounded"|"solid"|"shadow"|string|string[]
---Agenda views.
---@field agenda? org.Config.Agenda
---Capture templates and capture window.
---@field capture? org.Config.Capture
---Refile targets and behaviour.
---@field refile? org.Config.Refile
---Clocking (time tracking).
---@field clock? org.Config.Clock
---Encrypting entries (`org-crypt`).
---@field crypt? org.Config.Crypt
---Relative and countdown timers.
---@field timer? org.Config.Timer
---org-protocol handling.
---@field protocol? org.Config.Protocol
---Plain links through tags files (`org-ctags`).
---@field ctags? org.Config.Ctags
---Pasting clipboard images and dropped files (`org-yank-*`).
---@field yank? org.Config.Yank
---RSS and Atom feeds (`org-feed`).
---@field feed? org.Config.Feed
---org-mouse: context menus, dragging subtrees, clickable stars.
---@field mouse? org.Config.Mouse
---Links: abbreviations, custom types, following.
---@field links? org.Config.Links
---Downloading remote resources (a URL in `#+INCLUDE`): `"prompt"`, `"safe"`,
---`true` (always) or `false` (never).
---(Emacs `org-resource-download-policy`, default: `"prompt"`)
---@field resource_download_policy? "prompt"|"safe"|boolean
---Vim regexes of safe URLs (also matched against "file://" .. the file).
---(Emacs `org-safe-remote-resources`, default: `{}`)
---@field safe_remote_resources? string[]
---BibTeX entries as headlines (ol-bibtex).
---@field bibtex? org.Config.Bibtex
---`ID` property creation and lookup.
---@field id? org.Config.Id
---Attachments (`org-attach`).
---@field attach? org.Config.Attach
---MobileOrg staging and sync (`org-mobile`).
---@field mobile? org.Config.Mobile
---Source block evaluation (Babel).
---@field babel? org.Config.Babel
---Export backends and options.
---@field export? org.Config.Export
---Appointment reminders for timed agenda entries.
---@field notifications? org.Config.Notifications
---Buffer appearance: concealing, bullets, faces.
---@field ui? org.Config.UI
---Key mappings. Set any mapping to `false` to disable it, or a list of lhs.
---@field mappings? org.Config.Mappings
---Optional extensions, off until listed here (see `:h org-extensions`).
---@field extensions? org.Config.Extensions

---Optional extensions. Listing one enables it; `false` or
---`{ enabled = false }` keeps it off. Each value is merged over that
---extension's defaults.
---@class org.Config.Extensions
---@field [string] table|boolean
---org-ql queries, search views and `#+BEGIN: org-ql` blocks (`:h org-extensions-ql`).
---@field ql? org.Config.Extensions.Ql|boolean
---org-super-agenda groups in agenda views (`:h org-extensions-super-agenda`).
---@field super_agenda? org.Config.Extensions.SuperAgenda|boolean
---Slideshows of org buffers, like Emacs org-present (`:h org-extensions-present`).
---@field present? org.Config.Extensions.Present|boolean

---@class org.Config.Extensions.Ql
---`false` keeps the extension off.
---@field enabled? boolean
---Files a search looks in: `"agenda"`, `"buffer"` (the current buffer),
---`"all"` (loaded org buffers) or a list of files and globs. (default: `"agenda"`)
---@field files? "agenda"|"buffer"|"all"|string[]
---Predicate for bare words in plain queries (org-ql-default-predicate).
---(default: `"rifle"`)
---@field default_predicate? string
---Sort of searches without their own (`"date"`, `"deadline"`, `"scheduled"`,
---`"closed"`, `"priority"`, `"todo"`, `"random"`, `"reverse"`, a comparator
---or a list of those; a list is applied in order, the last being the
---primary key). (default: `nil`, file order)
---@field sort? string|fun(a: org.Headline, b: org.Headline): boolean|(string|function)[]
---Named views for `:Org ql_view` (org-ql-views). (default: `{}`)
---@field views? table<string, org.Config.Extensions.QlView>
---JSON file of the views saved from search buffers; `false` to not save.
---(default: `stdpath("data") .. "/org/ql-views.json"`)
---@field views_file? string|false
---Key in search buffers that saves the search as a view. (default: `"<C-x><C-s>"`)
---@field save_view_key? string|false
---Also search COMMENT and ARCHIVE subtrees, as org-ql does. (default: `false`)
---@field include_hidden? boolean
---A repeating timestamp matches a date range when an occurrence does. (default: `true`)
---@field expand_repeaters? boolean
---Remember results per entry until its file changes. (default: `true`)
---@field cache? boolean

---@class org.Config.Extensions.QlView
---The query: a sexp or plain query string, or a Lua-form table.
---@field query string|table
---@field files? "agenda"|"buffer"|"all"|string[]
---@field sort? string|function|(string|function)[]
---Header line of the view (default: the view's name).
---@field title? string
---org-super-agenda groups for this view.
---@field super_groups? table[]
---Also search COMMENT and ARCHIVE subtrees (default: `include_hidden`).
---@field include_hidden? boolean

---@class org.Config.Extensions.SuperAgenda
---`false` keeps the extension off.
---@field enabled? boolean
---The groups (org-super-agenda-groups), e.g.
---`{ { name = "Today", time_grid = true }, { auto_category = true } }`. (default: `{}`)
---@field groups? table[]
---Header of the items no group takes. (default: `"Other items"`)
---@field unmatched_name? string
---Order of that group. (default: `99`)
---@field unmatched_order? number
---Before each group header: a string (`"\n"` = a blank line) or one
---character repeated across the window. (default: `"\n"`)
---@field header_separator? string
---Text before each group name. (default: `" "`)
---@field header_prefix? string
---After the last group. (default: `""`)
---@field final_group_separator? string
---strftime format of `auto_planning` / `auto_ts` headers. (default: `"%e %B %Y"`)
---@field date_format? string
---Property read by `auto_group`. (default: `"agenda-group"`)
---@field group_property_name? string
---Inherit properties in `property`, `auto_property` and `auto_group`. (default: `true`)
---@field properties_inherit? boolean
---Keep the agenda's order inside a group (org-super-agenda-keep-order);
---off, a group lists its items selector by selector. (default: `false`)
---@field keep_order? boolean
---Keys on group headers: `toggle` folds the group, `next` / `prev` move
---between headers; `false` for none.
---(default: `{ toggle = "<Tab>", next = "gj", prev = "gk" }`)
---@field header_keys? { toggle?: string|false, next?: string|false, prev?: string|false }|false

---Options of the `present` extension (Emacs org-present).
---@class org.Config.Extensions.Present
---@field enabled? boolean
---Headlines of this level or less start a slide. (default: `1`)
---@field slide_level? integer
---Show the lines before the first headline (#+TITLE, #+AUTHOR, ...) as a
---first slide when they have anything to show. (default: `true`)
---@field title_slide? boolean
---Slide width in columns, or a fraction of the screen (0 < w <= 1); the
---slide is centered. (default: `80`)
---@field width? number
---Blank lines above the slide. (default: `2`)
---@field padding_top? integer
---Start read-only; `present_toggle_read_only` switches to editing, and edits
---are written back to the source buffer. (default: `true`)
---@field read_only? boolean
---Hide the cursor while read-only (org-present-hide-cursor). (default: `true`)
---@field hide_cursor? boolean
---Hide headline stars (org-present-hide-stars-in-headings). (default: `true`)
---@field hide_stars? boolean
---Hide `#+KEY:` lines other than TITLE, SUBTITLE, AUTHOR, DATE and EMAIL,
---and the keyword part of those. (default: `true`)
---@field hide_keywords? boolean
---Hide emphasis markers on slides. (default: `true`)
---@field hide_emphasis_markers? boolean
---Draw a rule under the slide's headline. (default: `true`)
---@field heading_underline? boolean
---Preview image links when an image backend is available. (default: `true`)
---@field show_images? boolean
---Show `3/12` in the window bar. (default: `true`)
---@field counter? boolean
---Show only a slide's headline at first; <Tab> unfolds it
---(org-present-startup-folded). (default: `false`)
---@field startup_folded? boolean
---Indent headlines below the slide's own headline by two columns per level.
---(default: `true`)
---@field indent_subheadings? boolean
---Grow the terminal font by this many points while presenting
---(org-present-text-scale); 0 leaves it alone. Needs kitty with remote
---control, or `font_command`. (default: `0`)
---@field font_scale? integer
---Changes the terminal font: called with `"+N"` or `"0"` (reset).
---@field font_command? fun(delta: string)
---Keys always active in the slide buffer: `next`, `prev`, `first`, `last`,
---`quit`, `toggle_read_only`, `toggle_one_big_page`, `big`, `small` -> lhs,
---a list of lhs or `false`.
---@field keys? table<string, string|string[]|false>
---Keys active only while read-only (same names as `keys`).
---@field read_only_keys? table<string, string|string[]|false>
---Called with the presentation state when it starts (org-present-mode-hook).
---@field on_start? fun(state: table)
---Called when it ends (org-present-mode-quit-hook).
---@field on_quit? fun(state: table)
---Called with the slide number, the state and the slide's headline after
---each move (org-present-after-navigate-functions).
---@field on_slide? fun(n: integer, state: table, heading: string)

---org-mouse (`:h org-mouse`).
---@class org.Config.Mouse
---Load org-mouse (Emacs: `(require 'org-mouse)`). (default: `false`)
---@field org_mouse? boolean
---Its parts: `"context-menu"`, `"move-tree"`, `"yank-link"`,
---`"activate-stars"`, `"activate-bullets"`, `"activate-checkboxes"`.
---(Emacs `org-mouse-features`, default: all but `"move-tree"`)
---@field features? string[]

---Plain lists.
---@class org.Config.Lists
---Single-letter bullets `a.`, `A)` and counters `[@c]`.
---(Emacs `org-list-allow-alphabetical`, default: `false`)
---@field allow_alphabetical? boolean
---Ordered bullet terminators: `true` (both), `"."` or `")"`.
---(Emacs `org-plain-list-ordered-item-terminator`, default: `true`)
---@field ordered_item_terminator? true|"."|")"
---Bullet given to demoted items, keyed by the old bullet type (`"-"`,
---`"+"`, `"*"`, `"1."`, `"1)"`, `"a."`, `"A)"`...).
---(Emacs `org-list-demote-modify-bullet`, default: `{}`)
---@field demote_modify_bullet? table<string, string>
---Emacs regexp matching bullets followed by two spaces.
---(Emacs `org-list-two-spaces-after-bullet-regexp`, default: `nil`)
---@field two_spaces_after_bullet_regexp? string
---Extra indentation of sub-lists. (Emacs `org-list-indent-offset`, default: `0`)
---@field indent_offset? integer
---`checkbox`: update statistics after checkbox changes; `indent`: the first
---item moves the whole list and `*` becomes `-` at column 0.
---(Emacs `org-list-automatic-rules`, default: `{ checkbox = true, indent = true }`)
---@field automatic_rules? { checkbox?: boolean, indent?: boolean }
---Item motions and moves wrap around the list.
---(Emacs `org-list-use-circular-motion`, default: `false`)
---@field use_circular_motion? boolean
---Checkbox cookies count direct children only; `false` counts every box.
---(Emacs `org-checkbox-hierarchical-statistics`, default: `true`)
---@field checkbox_hierarchical_statistics? boolean

---Blank line handling before new entries (Emacs `org-blank-before-new-entry`).
---@class org.Config.BlankBeforeNewEntry
---Before new headings: `true`, `false`, or `"auto"` (blank when the
---current heading is preceded by a blank line). (default: `"auto"`)
---@field heading? boolean|"auto"
---Before new plain list items: `true`, `false`, or `"auto"` (the blank
---lines between the items of the list, see
---org-list-separating-blank-lines-number). (default: `"auto"`)
---@field plain_list_item? boolean|"auto"

---Payload passed to a custom `notifications.notifier`.
---@class org.Config.Notifications.Event
---Notification title: TODO keyword and headline.
---@field title string
---Notification body: kind, time, "in N min" and category.
---@field body string
---The agenda item the reminder is for.
---@field item org.AgendaItem
---Minutes until the entry starts (0 = now).
---@field minutes integer

---Appointment reminders for timed SCHEDULED, DEADLINE and plain timestamps
---of today and tomorrow (Emacs `org-agenda-to-appt`).
---@class org.Config.Notifications
---Start the reminder timer on setup. (default: `false`)
---@field enabled? boolean
---Minutes before an entry's start to notify; one notification per offset.
---A single number is also accepted. (default: `{ 10, 0 }`)
---@field reminder_time? integer|integer[]
---Seconds between checks. (default: `60`)
---@field check_interval? integer
---Also use the OS notifier (`osascript` / `notify-send`) when available.
---(default: `true`)
---@field system_notification? boolean
---Custom notifier replacing the built-in `vim.notify` + OS notification.
---(default: `nil`)
---@field notifier? fun(event: org.Config.Notifications.Event)

---Buffer appearance.
---@class org.Config.UI
---The Org, Table, Agenda, Column, Edit-Formulas and OrgTbl menus, added
---while a buffer they belong to is current (Emacs has no option for them).
---(default: `true`)
---@field menus? boolean
---How to ask for one of a fixed set of values (a table export format, a
---column summary type, …): a floating list, or the command line with
---`<Tab>` completion (Emacs `completing-read`).
---(default: `"float"`)
---@field choice_prompt? "float"|"input"
---Headline levels listed by `imenu` (`gO`).
---(Emacs `org-imenu-depth`, default: `2`)
---@field imenu_depth? integer
---Conceal link brackets and show only descriptions (sets `conceallevel=2`).
---(default: `true`)
---@field conceal_links? boolean
---Hide `*`, `/`, `_`, `=`, `~`, `+` around emphasized text.
---(Emacs `org-hide-emphasis-markers`, default: `false`)
---@field hide_emphasis_markers? boolean
---Show only the last star of each headline.
---(Emacs `org-hide-leading-stars`, default: `false`)
---@field hide_leading_stars? boolean
---Replace headline stars with symbols, one per level (cycled for deeper
---levels), e.g. `{ "◉", "○", "✸", "✿" }`; `false` = off. (default: `false`)
---@field bullets? string[]|false
---Replace checkboxes with icons `{ unchecked, partial, checked }`, e.g.
---`{ " ", "◐", "✓" }`; `false` = off. (default: `false`)
---@field checkboxes? string[]|false
---Virtual indentation of body text (`#+STARTUP: indent` / `noindent`).
---(Emacs `org-indent-mode` / `org-startup-indented`, default: `false`)
---@field indent_mode? boolean
---Columns of virtual indentation per level in indent mode; `0` = none.
---(Emacs `org-indent-indentation-per-level`, default: `2`)
---@field indent_indentation_per_level? integer
---Indent mode turns `adapt_indentation` off in its buffer.
---(Emacs `org-indent-mode-turns-off-org-adapt-indentation`, default: `true`)
---@field indent_mode_turns_off_adapt_indentation? boolean
---Render entities like `\alpha` as unicode (`#+STARTUP: entitiespretty` /
---`entitiesplain`, toggle_pretty_entities).
---(Emacs `org-pretty-entities`, default: `false`)
---@field pretty_entities? boolean
---With pretty_entities, show `x^2` and `a_{i}` as super/subscripts.
---(Emacs `org-pretty-entities-include-sub-superscripts`, default: `true`)
---@field pretty_entities_include_sub_superscripts? boolean
---Which `^` / `_` are scripts: `true`, `"{}"` (braces only) or `false`.
---(Emacs `org-use-sub-superscripts`, default: `true`)
---@field use_sub_superscripts? boolean|"{}"
---Number headlines with virtual text (`#+STARTUP: num` / `nonum`, num_mode).
---(Emacs `org-num-mode` / `org-startup-numerated`, default: `false`)
---@field num? boolean
---Highlight the text of TODO headlines (OrgHeadlineTodo).
---(Emacs `org-fontify-todo-headline`, default: `false`)
---@field fontify_todo_headline? boolean
---The headline level color on the stars only.
---(Emacs `org-level-color-stars-only`, default: `false`)
---@field level_color_stars_only? boolean
---Keywords shown without their `#+KEYWORD:` part.
---(Emacs `org-hidden-keywords`, default: `{}`)
---@field hidden_keywords? ("title"|"subtitle"|"author"|"date"|"email")[]
---Hide the `{{{ }}}` around macro calls.
---(Emacs `org-hide-macro-markers`, default: `false`)
---@field hide_macro_markers? boolean
---LaTeX-related syntax highlighted: `"latex"`, `"native"`, `"script"`,
---`"entities"`. (Emacs `org-highlight-latex-and-related`, default: `{}`)
---@field highlight_latex_and_related? ("latex"|"native"|"script"|"entities")[]
---Deepest numbered level; `nil` = all. (Emacs `org-num-max-level`, default: `nil`)
---@field num_max_level? integer
---Don't number COMMENT subtrees. (Emacs `org-num-skip-commented`, default: `false`)
---@field num_skip_commented? boolean
---Don't number the footnote section. (Emacs `org-num-skip-footnotes`, default: `false`)
---@field num_skip_footnotes? boolean
---Tags whose subtrees are not numbered. (Emacs `org-num-skip-tags`, default: `{}`)
---@field num_skip_tags? string[]
---Don't number subtrees with an UNNUMBERED property.
---(Emacs `org-num-skip-unnumbered`, default: `false`)
---@field num_skip_unnumbered? boolean
---Text shown before a headline from its numbers, e.g. `{ 1, 2 }` -> `"1.2 "`.
---(Emacs `org-num-format-function`, default: `nil`)
---@field num_format_function? fun(numbers: integer[]): string?
---Dim the whole headline of DONE entries.
---(Emacs `org-fontify-done-headline`, default: `true`)
---@field fontify_done_headline? boolean
---Highlight src blocks with their language's syntax.
---(Emacs `org-src-fontify-natively`, default: `true`)
---@field src_highlight? boolean
---Face of src block bodies by language (`""` = no language), like
---`todo_keyword_faces`: `{ python = { bg = "#e5ffb8" } }`.
---(Emacs `org-src-block-faces`, default: `{}`)
---@field src_block_faces? table<string, string|vim.api.keyset.highlight>
---Per-keyword faces. Values are an Emacs-style face string
---(`":foreground orange :weight bold"`), a highlight group name, or a
---highlight definition table (`{ fg = "#ff9e64", bold = true }`).
---(Emacs `org-todo-keyword-faces`, default: `{}`)
---@field todo_keyword_faces? table<string, string|vim.api.keyset.highlight>
---Faces of priority cookies, by priority (`A`, `"10"`), like
---`todo_keyword_faces`. (Emacs `org-priority-faces`, default: `{}`)
---@field priority_faces? table<string, string|vim.api.keyset.highlight>
---Faces of tags, by tag, like `todo_keyword_faces`.
---(Emacs `org-tag-faces`, default: `{}`)
---@field tag_faces? table<string, string|vim.api.keyset.highlight>
---Inline image previews (`org-link-preview`). See `:h org-images`.
---@field images? org.Config.UI.Images
---LaTeX fragment previews (`org-latex-preview`), drawn by the `images` backend.
---@field latex_preview? org.Config.UI.LatexPreview

---@class org.Config.UI.Images
---`"auto"`, `"native"` (`vim.ui.img`: Neovim 0.13+ in a terminal with the
---Kitty graphics protocol), `"snacks"` (Snacks.image), `"image.nvim"`, or
---`false`. `"auto"` uses the first that works. (default: `"auto"`)
---@field backend? "auto"|"native"|"snacks"|"image.nvim"|false
---Image width: `true` = their own size, a number = pixels, `false` or
---`{ n }` = the `:width` of `#+ATTR_ORG` (else another `#+ATTR_x`), else n
---pixels. The ORG-IMAGE-ACTUAL-WIDTH property overrides it.
---(Emacs `org-image-actual-width`, default: `true`)
---@field actual_width? boolean|number|number[]
---Widest image: `"fill-column"` ('textwidth', else 70), `"window"`, a
---number of pixels, a fraction of the window, or `false` (the window).
---(Emacs `org-image-max-width`, default: `"fill-column"`)
---@field max_width? "fill-column"|"window"|number|false
---Tallest image, in rows. (default: `24`)
---@field max_height? integer
---Alignment of images alone in their paragraph; `#+ATTR_ORG: :align` /
---`:center t` override it. (Emacs `org-image-align`, default: `"left"`)
---@field align? "left"|"center"|"right"
---Preview image links when a file opens (`#+STARTUP: linkpreviews` /
---`inlineimages`). (Emacs `org-startup-with-link-previews`, default: `false`)
---@field startup? boolean
---Preview an entry's links when TAB shows it, remove them when it folds.
---(Emacs `org-cycle-link-previews-display`, default: `false`)
---@field cycle_display? boolean
---File extensions previewed. (Emacs `image-file-name-regexp`)
---@field extensions? string[]

---@class org.Config.UI.LatexProcess
---@field programs? string[] programs that must be installed
---@field message? string shown when they are not
---@field image_input_type? string what the compiler makes (dvi, xdv, pdf)
---@field image_output_type? string png or svg
---@field image_size_adjust? number[] { buffer, html } scale factors
---@field latex_header? string header used instead of `latex_preview.header`
---@field latex_compiler? string[] shell commands (%f %F %b %o %O)
---@field image_converter? string[] shell commands (%f %F %b %o %O %D %S)
---@field transparent_image_converter? string[] used with a transparent background

---@class org.Config.UI.LatexPreview
---The process from `processes` that renders fragments, or `"auto"` for the
---first installed of dvipng, dvisvgm, tectonic, pdflatex, imagemagick.
---(Emacs `org-preview-latex-default-process`, default: `"auto"`)
---@field process? string
---Processes added to or replacing dvipng, dvisvgm, xelatex, imagemagick,
---tectonic and pdflatex. (Emacs `org-preview-latex-process-alist`, default: `{}`)
---@field processes? table<string, org.Config.UI.LatexProcess>
---Size of the formulas relative to the text.
---(Emacs `org-format-latex-options` `:scale`, default: `1.0`)
---@field scale? number
---Color of the formulas: `"default"` (Normal), `"auto"` (the text at the
---fragment), a color name or `"#rrggbb"`. (`:foreground`, default: `"default"`)
---@field foreground? string
---Background: `"default"` (Normal), `"Transparent"`, a color name or
---`"#rrggbb"`. (`:background`, default: `"default"`)
---@field background? string
---LaTeX preamble with `[DEFAULT-PACKAGES]` / `[PACKAGES]`; `#+LATEX_HEADER`
---lines are added. `nil` = the Emacs header.
---(Emacs `org-format-latex-header`, default: `nil`)
---@field header? string
---Where rendered images go, relative to the file's directory or absolute.
---(Emacs `org-preview-latex-image-directory`, default: `"ltximg/"`)
---@field image_directory? string
---An absolute directory used instead of `image_directory`. (default: `nil`)
---@field cache_dir? string
---Preview every fragment when a file opens (`#+STARTUP: latexpreview`).
---(Emacs `org-startup-with-latex-preview`, default: `false`)
---@field startup? boolean
