---@meta

-- Types for the `clock`, `links`, `id`, `attach`, `babel` and `export`
-- sections of `require("org").setup({...})`. Annotations only.

---------------------------------------------------------------------------
-- Clocking
---------------------------------------------------------------------------

---Clocking options.
---@class org.Config.Clock
---Clock out when the clocked task is marked DONE (`org-clock-out-when-done`).
---`true` = any DONE state, `false` = never, or a list of TODO keywords that
---clock out when switched to. (default: `true`)
---@field out_when_done? boolean|string[]
---Drawer for CLOCK lines (`org-clock-into-drawer`). `true` = the log drawer
---(`log_into_drawer`, else `LOGBOOK`), `false` = no drawer, a string = that
---drawer name, or a number N: only once the entry has N CLOCK lines (the
---loose lines are then moved into the drawer). The `CLOCK_INTO_DRAWER`
---property overrides it. (default: `true`)
---@field into_drawer? boolean|string|integer
---Remove clock lines of zero duration on clock out
---(`org-clock-out-remove-zero-time-clocks`). (default: `false`)
---@field out_remove_zero_time? boolean
---Round clock-in/out times to this many minutes; `"same-as-time-stamp"`
---uses `time_stamp_rounding_minutes[1]` (`org-clock-rounding-minutes`). (default: `0`)
---@field rounding_minutes? integer|"same-as-time-stamp"
---Clocking into an entry with an open CLOCK line continues that clock
---(`org-clock-in-resume`). (default: `false`)
---@field in_resume? boolean
---TODO state to switch the task to on clock in (`org-clock-in-switch-to-state`):
---a keyword, or a function receiving the task's current keyword (`nil` when
---it has none) and returning the new keyword, or `nil` to keep it.
---Ignored unless the result is a TODO keyword of the file. (default: `nil`)
---@field in_switch_to_state? string|fun(keyword: string?): string?
---TODO state to switch the task to on clock out (`org-clock-out-switch-to-state`):
---a keyword, or a function receiving the task's current keyword (`nil` when
---it has none) and returning the new keyword, or `nil` to keep it. (default: `nil`)
---@field out_switch_to_state? string|fun(keyword: string?): string?
---Notify once when the clocked time reaches the task's effort. (default: `true`)
---@field notify_effort? boolean
---Number of tasks remembered in the clock history, used by clock in with a
---count (`org-clock-history-length`). (default: `35`)
---@field history_length? integer
---Start a new clock where the last one stopped (`org-clock-continuously`).
---(default: `false`)
---@field continuously? boolean
---Time shown in the statusline next to the running clock
---(`org-clock-mode-line-total`, overridden by the CLOCK_MODELINE_TOTAL
---property): `"current"` this clock, `"today"`, `"repeat"` since
---LAST_REPEAT, `"all"`, or `"auto"` (`"repeat"` for repeated tasks, else
---`"all"`). (default: `"auto"`)
---@field mode_line_total? "current"|"today"|"repeat"|"all"|"auto"
---Maximum statusline length, 0 = no limit (`org-clock-string-limit`). (default: `0`)
---@field string_limit? integer
---Task name shown in the statusline (`org-clock-heading-function`). (default: `nil`)
---@field heading_function? fun(headline: org.Headline): string
---Text put before the statusline once the effort is used up
---(`org-clock-task-overrun-text`). (default: `nil`)
---@field task_overrun_text? string
---Sound of the effort notification: `true` = bell, or a sound file
---(`org-clock-sound`). (default: `nil`)
---@field sound? boolean|string
---Function or program receiving the effort notification instead of
---`vim.notify` (`org-show-notification-handler`). (default: `nil`)
---@field notification_handler? fun(msg: string)|string
---After this many idle minutes, ask how to resolve the running clock
---(`org-clock-idle-time`). Uses the system idle time on macOS and X11
---(xprintidle). (default: `nil`)
---@field idle_time? integer
---Clock out after this many idle seconds (`org-clock-auto-clockout-timer`).
---(default: `nil`)
---@field auto_clockout_timer? integer
---Resolve dangling clocks when clocking in (`org-clock-auto-clock-resolution`).
---(default: `"when-no-clock-is-running"`)
---@field auto_clock_resolution? "when-no-clock-is-running"|boolean
---Count the running clock in clock tables and clock sums
---(`org-clock-report-include-clocking-task`). (default: `false`)
---@field report_include_clocking_task? boolean
---`clock_goto` falls back to the last clocked task
---(`org-clock-goto-may-find-recent-task`). (default: `true`)
---@field goto_may_find_recent_task? boolean
---Lines shown above the entry after `clock_goto`
---(`org-clock-goto-before-context`). (default: `2`)
---@field goto_before_context? integer
---Range of `clock_display` without a count, a `:block` value
---(`org-clock-display-default-range`). (default: `"thisyear"`)
---@field display_default_range? string
---Ask to clock out (and save) when quitting with a running clock
---(`org-clock-ask-before-exiting`). (default: `true`)
---@field ask_before_exiting? boolean
---Icon prefixed to the running clock in the statusline. (default: `"⏱"`)
---@field statusline_icon? string
---Default parameters for clock tables (`org-clocktable-defaults`); block
---parameters override them. (default: `{ maxlevel = 2, scope = "file" }`)
---@field clocktable_default? org.Config.Clock.ClocktableDefault
---Persist the running clock and clock history across restarts
---(`org-clock-persist`): `true` (both), `"clock"`, `"history"`, `false`.
---(default: `true`)
---@field persist? boolean|"clock"|"history"
---Ask before resuming a clock after a restart
---(`org-clock-persist-query-resume`). (default: `true`)
---@field persist_query_resume? boolean
---File where the clock state is persisted (`org-clock-persist-file`).
---(default: `stdpath("data") .. "/org/clock.json"`)
---@field persist_file? string

---Default clock table parameters (`org-clocktable-defaults`).
---@class org.Config.Clock.ClocktableDefault
---Maximum headline level shown (`:maxlevel`). (default: `2`)
---@field maxlevel? integer
---Files/subtrees covered (`:scope`): `"file"`, `"file-with-archives"`,
---`"subtree"`, `"tree"`, `"treeN"` (e.g. `"tree2"`), `"agenda"`,
---`"agenda-with-archives"`, or a file path / list like `'("a.org" "b.org")'`.
---(default: `"file"`)
---@field scope? "file"|"file-with-archives"|"subtree"|"tree"|"agenda"|"agenda-with-archives"|string
---Time block (`:block`): `"today"`, `"yesterday"`, `"thisweek"`,
---`"lastweek"`, `"thismonth"`, `"lastmonth"`, `"thisyear"`, `"lastyear"`,
---`"thisq"`, `"lastq"`, `"untilnow"`, with an optional `-N`/`+N` offset
---(e.g. `"today-1"`), or `"YYYY-MM-DD"`, `"YYYY-WNN"`, `"YYYY-QN"`,
---`"YYYY-MM"`, `"YYYY"`. `nil` = all time. (default: `nil`)
---@field block? "today"|"yesterday"|"thisweek"|"lastweek"|"thismonth"|"lastmonth"|"thisyear"|"lastyear"|string

---------------------------------------------------------------------------
-- Timers
---------------------------------------------------------------------------

---Timer options.
---@class org.Config.Timer
---How `timer_insert` writes the value; `%s` is the value (`org-timer-format`).
---(default: `"%s "`)
---@field format? string
---Countdown suggested at the prompt, minutes or `h:mm:ss`; `"0"` suggests
---nothing (`org-timer-default-timer`). (default: `"0"`)
---@field default_timer? string

---------------------------------------------------------------------------
-- Links
---------------------------------------------------------------------------

---A link as passed to a custom link type handler.
---@class org.Config.Links.Link
---Link target as written inside `[[...]]`.
---@field target string
---Link type (the scheme before `:`).
---@field type string
---Part after `type:`.
---@field path string

---Handler that opens a custom link type (`org-link-set-parameters` `:follow`).
---Receives the path after `type:` and the classified link.
---@alias org.Config.Links.TypeHandler fun(path: string, link: org.Config.Links.Link): any

---External application for `links.file_apps`: a shell command (the path is
---appended, or substituted for `%s`), `"system"`/`"default"` for the OS
---opener, or a function receiving the absolute path.
---@alias org.Config.Links.FileApp "system"|"default"|string|fun(path: string): any

---Link options.
---@class org.Config.Links
---Link abbreviations like `#+LINK:` (`org-link-abbrev-alist`), e.g.
---`{ gh = "https://github.com/%s" }`. In the replacement `%s` is the tag and
---`%h` the URL-encoded tag; otherwise the tag is appended. A function
---receiving the tag and returning the URL is also accepted. (default: `{}`)
---@field abbreviations? table<string, string|fun(tag: string): string>
---Custom link types, e.g. `{ jira = function(path, link) ... end }`
---(`org-link-set-parameters` `:follow`). (default: `{}`)
---@field types? table<string, org.Config.Links.TypeHandler>
---Ask before running `shell:` links (`org-link-shell-confirm-function`).
---(default: `true`)
---@field confirm_shell? boolean
---Store links to headlines as `id:` links (`org-id-link-to-org-use-id`):
---`true` = always, creating an ID if needed; `"create-if-interactive"` =
---create only when storing interactively; `"use-existing"` = only when the
---headline already has an ID; `false` = never. (default: `"create-if-interactive"`)
---@field use_id? boolean|"create-if-interactive"|"use-existing"
---Open files with these (lowercase) extensions with an external app
---(`org-file-apps`), e.g. `{ pdf = "open" }` or `{ pdf = "zathura %s" }`.
---(default: `{}`)
---@field file_apps? table<string, org.Config.Links.FileApp>

---------------------------------------------------------------------------
-- IDs / attachments
---------------------------------------------------------------------------

---ID options.
---@class org.Config.Id
---JSON file mapping IDs to files (`org-id-locations-file`; not shared with Emacs).
---(default: `stdpath("data") .. "/org/id-locations.json"`)
---@field locations_file? string
---How new IDs are generated (`org-id-method`): `"uuid"`, `"ts"` (a time
---stamp like `20240101T120000.123456`) or `"org"` (a compact time based
---ID). (default: `"uuid"`)
---@field method? "uuid"|"ts"|"org"
---Prefix of new IDs, joined with `:` (`org-id-prefix`). (default: `nil`)
---@field prefix? string
---Format of `"ts"` IDs; `%6N` is replaced by microseconds (`org-id-ts-format`).
---(default: `"%Y%m%dT%H%M%S.%6N"`)
---@field ts_format? string
---Also look for IDs in the archive files of the agenda files
---(`org-id-search-archives`). (default: `true`)
---@field search_archives? boolean
---More files (paths or globs) scanned for IDs (`org-id-extra-files`). (default: `{}`)
---@field extra_files? string[]

---Attachment options.
---@class org.Config.Attach
---Attachment root (`org-attach-id-dir`), relative to the org file's
---directory unless absolute. (default: `"data/"`)
---@field dir? string
---Default attach method (`org-attach-method`): `"cp"` copy, `"mv"` move,
---`"ln"` hard link, `"lns"` symbolic link. (default: `"cp"`)
---@field method? "cp"|"mv"|"ln"|"lns"
---Map an ID to a folder under `dir` (`org-attach-id-to-path-function-list`):
---functions `fun(id): string?` or the built-ins `"uuid"` (`ab/cdef...`),
---`"ts"` (`202401/...` for time stamp IDs) and `"fallback"`
---(`__/a/abcdef...`). The first existing folder wins, else the first result.
---(default: `{ "uuid", "ts", "fallback" }`)
---@field id_to_path? (string|fun(id: string): string?)[]
---Inherit the attachment directory (`DIR` / an ancestor's ID) from parents
---(`org-attach-use-inheritance`): `"selective"` follows
---`use_property_inheritance`. (default: `"selective"`)
---@field use_inheritance? boolean|"selective"
---Store `DIR` relative to the org file (`org-attach-dir-relative`). (default: `false`)
---@field dir_relative? boolean
---How an entry without a directory gets one (`org-attach-preferred-new-method`):
---`"id"`, `"dir"` (ask for a `DIR`), `"ask"` or `false` (error). (default: `"id"`)
---@field preferred_new_method? "id"|"dir"|"ask"|false
---Store a link after attaching (`org-attach-store-link-p`): `"attached"`
---(`attachment:` link), `"file"` (`file:` link to the attachment), `true`
---(`file:` link to the source) or `false`. (default: `"attached"`)
---@field store_link? "attached"|"file"|boolean
---Delete an empty attachment directory when syncing
---(`org-attach-sync-delete-empty-dir`): `"query"`, `true` or `false`. (default: `"query"`)
---@field sync_delete_empty_dir? "query"|boolean
---Delete the attachments of archived entries (`org-attach-archive-delete`):
---`false`, `true` or `"query"`. (default: `false`)
---@field archive_delete? boolean|"query"
---Tag of entries with attachments (`org-attach-auto-tag`); `false` for none.
---(default: `"ATTACH"`)
---@field auto_tag? string|false

---------------------------------------------------------------------------
-- Babel
---------------------------------------------------------------------------

---How to run one src block language.
---@class org.Config.Babel.Language
---Command that runs the program: a string (split on whitespace) or an argv
---list. The code is written to a temp file whose path is appended (sqlite
---gets the `:db` path and the code on stdin). Required to evaluate a
---language not in the defaults; `lua` always runs inside Neovim.
---@field cmd? string|string[]
---Extension of the temp file / tangled file, e.g. `"py"`. Defaults to a
---built-in per-language table, else the language name.
---@field ext? string

---Default header arguments (`org-babel-default-header-args`). Keys are
---header argument names without `:`; values are strings.
---@class org.Config.Babel.HeaderArgs
---(default: `"replace"`)
---@field results? string
---(default: `"code"`)
---@field exports? "code"|"results"|"both"|"none"|string
---`"none"`, or a session name: blocks with the same language and session
---name share one running interpreter. (default: `"none"`)
---@field session? string
---(default: `"no"`)
---@field noweb? "yes"|"no"|"tangle"|"no-export"|"strip-export"|"eval"|string
---(default: `"no"`)
---@field tangle? "yes"|"no"|string
---@field [string] string|number

---Source block evaluation (Babel) options.
---@class org.Config.Babel
---Ask before evaluating a src block (`org-confirm-babel-evaluate`); `:eval`
---header args still apply. (default: `true`)
---@field confirm_evaluate? boolean
---Results with at least this many lines use an example block instead of
---`: ` lines (`org-babel-min-lines-for-block-output`). (default: `10`)
---@field min_lines_for_block_output? integer
---Kill evaluation after this many milliseconds; for a `:session`, stop
---waiting for the answer. (default: `30000`)
---@field timeout? integer
---Evaluate code blocks, `#+CALL` lines and inline code when exporting, like
---Emacs `org-export-use-babel`: `:exports results|both` blocks get fresh
---results in the exported copy (the buffer is not changed). When `false`,
---export uses the `#+RESULTS` already in the buffer. (default: `false`)
---@field evaluate_on_export? boolean
---Default header arguments, merged key by key with the defaults.
---(default: `{ results = "replace", exports = "code", session = "none", noweb = "no", tangle = "no" }`)
---@field default_header_args? org.Config.Babel.HeaderArgs
---Languages that can be evaluated, merged key by key with the defaults
---(sh, shell, bash, zsh, fish, python, python3, lua, js, javascript,
---typescript, ts, ruby, perl, php, r, R, go, rust, sqlite, awk). Set a
---language to `false` to remove it.
---@field languages? table<string, org.Config.Babel.Language|false>

---------------------------------------------------------------------------
-- Export
---------------------------------------------------------------------------

---HTML exporter options.
---@class org.Config.Export.Html
---Stylesheet: `nil` = built-in stylesheet, `false` = none, a string = CSS
---put in a `<style>` element (`org-html-head-include-default-style`).
---(default: `nil`)
---@field style? string|false
---Extra markup appended to `<head>` (`org-html-head-extra`). (default: `""`)
---@field head_extra? string
---Load MathJax when the document contains math. (default: `true`)
---@field mathjax? boolean

---Pandoc options (LaTeX/PDF/DOCX/ODT/... export).
---@class org.Config.Export.Pandoc
---Pandoc executable: a string (split on whitespace) or an argv list.
---(default: `"pandoc"`)
---@field cmd? string|string[]
---Extra arguments passed to pandoc. (default: `{}`)
---@field args? string[]

---Export options. `#+OPTIONS:` in a file overrides the `with_*` values.
---@class org.Config.Export
---Output directory, relative to the source file unless absolute; `nil` =
---next to the source file. (default: `nil`)
---@field output_dir? string
---Include a table of contents (`org-export-with-toc`, `toc:`). (default: `true`)
---@field with_toc? boolean
---Number sections (`org-export-with-section-numbers`, `num:`). (default: `true`)
---@field with_section_numbers? boolean
---Deepest headline level exported as a section (`org-export-headline-levels`,
---`H:`). (default: `3`)
---@field headline_levels? integer
---Include the author (`org-export-with-author`, `author:`). (default: `true`)
---@field with_author? boolean
---Include the date (`org-export-with-date`, `date:`). (default: `true`)
---@field with_date? boolean
---Include TODO keywords (`org-export-with-todo-keywords`, `todo:`). (default: `true`)
---@field with_todo_keywords? boolean
---Include tags (`org-export-with-tags`, `tags:`). (default: `true`)
---@field with_tags? boolean
---Include priority cookies (`org-export-with-priority`, `pri:`). (default: `false`)
---@field with_priority? boolean
---Include drawers (`org-export-with-drawers`, `d:`). (default: `false`)
---@field with_drawers? boolean
---Include planning lines (`org-export-with-planning`, `p:`). (default: `false`)
---@field with_planning? boolean
---Include timestamps (`org-export-with-timestamps`, `<:`). (default: `true`)
---@field with_timestamps? boolean
---When any headline has one of these tags, only those subtrees are exported
---(`org-export-select-tags`). (default: `{ "export" }`)
---@field select_tags? string[]
---Subtrees with one of these tags are not exported (`org-export-exclude-tags`).
---(default: `{ "noexport" }`)
---@field exclude_tags? string[]
---Open the exported file with the system opener. (default: `false`)
---@field open_after_export? boolean
---HTML exporter options.
---@field html? org.Config.Export.Html
---Line width of the plain-text (UTF-8) exporter (`org-ascii-text-width`).
---(default: `72`)
---@field text_width? integer
---Pandoc options for formats handled by pandoc.
---@field pandoc? org.Config.Export.Pandoc
