---@meta

-- Types for the `clock`, `links`, `id`, `attach`, `babel` and `export`
-- sections of `require("org").setup({...})`. Annotations only.

---------------------------------------------------------------------------
-- Clocking
---------------------------------------------------------------------------

---Clocking options.
---@class org.Config.Clock
---Clock out when the clocked task is marked DONE (`org-clock-out-when-done`).
---`true` = any DONE state, `false` = never, or a list of TODO keywords that
---clock out when switched to. (default: `true`)
---@field out_when_done? boolean|string[]
---Drawer for CLOCK lines (`org-clock-into-drawer`). `true` = the log drawer
---(`log_into_drawer`, else `LOGBOOK`), `false` = no drawer, a string = that
---drawer name, or a number N: only once the entry has N CLOCK lines (the
---loose lines are then moved into the drawer). The `CLOCK_INTO_DRAWER`
---property overrides it. (default: `true`)
---@field into_drawer? boolean|string|integer
---Remove clock lines of zero duration on clock out
---(`org-clock-out-remove-zero-time-clocks`). (default: `false`)
---@field out_remove_zero_time? boolean
---Round clock-in/out times to this many minutes; `"same-as-time-stamp"`
---uses `time_stamp_rounding_minutes[1]` (`org-clock-rounding-minutes`). (default: `0`)
---@field rounding_minutes? integer|"same-as-time-stamp"
---Clocking into an entry with an open CLOCK line continues that clock
---(`org-clock-in-resume`). (default: `false`)
---@field in_resume? boolean
---TODO state to switch the task to on clock in (`org-clock-in-switch-to-state`):
---a keyword, or a function receiving the task's current keyword (`nil` when
---it has none) and returning the new keyword, or `nil` to keep it.
---Ignored unless the result is a TODO keyword of the file. (default: `nil`)
---@field in_switch_to_state? string|fun(keyword: string?): string?
---TODO state to switch the task to on clock out (`org-clock-out-switch-to-state`):
---a keyword, or a function receiving the task's current keyword (`nil` when
---it has none) and returning the new keyword, or `nil` to keep it. (default: `nil`)
---@field out_switch_to_state? string|fun(keyword: string?): string?
---Notify once when the clocked time reaches the task's effort. (default: `true`)
---@field notify_effort? boolean
---Number of tasks remembered in the clock history, used by clock in with a
---count (`org-clock-history-length`). (default: `35`)
---@field history_length? integer
---Start a new clock where the last one stopped (`org-clock-continuously`).
---(default: `false`)
---@field continuously? boolean
---Time shown in the statusline next to the running clock
---(`org-clock-mode-line-total`, overridden by the CLOCK_MODELINE_TOTAL
---property): `"current"` this clock, `"today"`, `"repeat"` since
---LAST_REPEAT, `"all"`, or `"auto"` (`"repeat"` for repeated tasks, else
---`"all"`). (default: `"auto"`)
---@field mode_line_total? "current"|"today"|"repeat"|"all"|"auto"
---Maximum statusline length, 0 = no limit (`org-clock-string-limit`). (default: `0`)
---@field string_limit? integer
---Task name shown in the statusline (`org-clock-heading-function`). (default: `nil`)
---@field heading_function? fun(headline: org.Headline): string
---Text put before the statusline once the effort is used up
---(`org-clock-task-overrun-text`). (default: `nil`)
---@field task_overrun_text? string
---Sound of the effort notification: `true` = bell, or a sound file
---(`org-clock-sound`). (default: `nil`)
---@field sound? boolean|string
---Function or program receiving the effort notification instead of
---`vim.notify` (`org-show-notification-handler`). (default: `nil`)
---@field notification_handler? fun(msg: string)|string
---After this many idle minutes, ask how to resolve the running clock
---(`org-clock-idle-time`). Uses the system idle time on macOS and X11
---(xprintidle). (default: `nil`)
---@field idle_time? integer
---Clock out after this many idle seconds (`org-clock-auto-clockout-timer`).
---(default: `nil`)
---@field auto_clockout_timer? integer
---Resolve dangling clocks when clocking in (`org-clock-auto-clock-resolution`).
---(default: `"when-no-clock-is-running"`)
---@field auto_clock_resolution? "when-no-clock-is-running"|boolean
---Count the running clock in clock tables and clock sums
---(`org-clock-report-include-clocking-task`). (default: `false`)
---@field report_include_clocking_task? boolean
---`clock_goto` falls back to the last clocked task
---(`org-clock-goto-may-find-recent-task`). (default: `true`)
---@field goto_may_find_recent_task? boolean
---Lines shown above the entry after `clock_goto`
---(`org-clock-goto-before-context`). (default: `2`)
---@field goto_before_context? integer
---Range of `clock_display` without a count, a `:block` value
---(`org-clock-display-default-range`). (default: `"thisyear"`)
---@field display_default_range? string
---Ask to clock out (and save) when quitting with a running clock
---(`org-clock-ask-before-exiting`). (default: `true`)
---@field ask_before_exiting? boolean
---Icon prefixed to the running clock in the statusline. (default: `"⏱"`)
---@field statusline_icon? string
---Default parameters for clock tables (`org-clocktable-defaults`); block
---parameters override them. (default: `{ maxlevel = 2, scope = "file" }`)
---@field clocktable_default? org.Config.Clock.ClocktableDefault
---Persist the running clock and clock history across restarts
---(`org-clock-persist`): `true` (both), `"clock"`, `"history"`, `false`.
---(default: `true`)
---@field persist? boolean|"clock"|"history"
---Ask before resuming a clock after a restart
---(`org-clock-persist-query-resume`). (default: `true`)
---@field persist_query_resume? boolean
---File where the clock state is persisted (`org-clock-persist-file`).
---(default: `stdpath("data") .. "/org/clock.json"`)
---@field persist_file? string

---Default clock table parameters (`org-clocktable-defaults`).
---@class org.Config.Clock.ClocktableDefault
---Maximum headline level shown (`:maxlevel`). (default: `2`)
---@field maxlevel? integer
---Files/subtrees covered (`:scope`): `"file"`, `"file-with-archives"`,
---`"subtree"`, `"tree"`, `"treeN"` (e.g. `"tree2"`), `"agenda"`,
---`"agenda-with-archives"`, or a file path / list like `'("a.org" "b.org")'`.
---(default: `"file"`)
---@field scope? "file"|"file-with-archives"|"subtree"|"tree"|"agenda"|"agenda-with-archives"|string
---Time block (`:block`): `"today"`, `"yesterday"`, `"thisweek"`,
---`"lastweek"`, `"thismonth"`, `"lastmonth"`, `"thisyear"`, `"lastyear"`,
---`"thisq"`, `"lastq"`, `"untilnow"`, with an optional `-N`/`+N` offset
---(e.g. `"today-1"`), or `"YYYY-MM-DD"`, `"YYYY-WNN"`, `"YYYY-QN"`,
---`"YYYY-MM"`, `"YYYY"`. `nil` = all time. (default: `nil`)
---@field block? "today"|"yesterday"|"thisweek"|"lastweek"|"thismonth"|"lastmonth"|"thisyear"|"lastyear"|string

---------------------------------------------------------------------------
-- Timers
---------------------------------------------------------------------------

---Timer options.
---@class org.Config.Timer
---How `timer_insert` writes the value; `%s` is the value (`org-timer-format`).
---(default: `"%s "`)
---@field format? string
---Countdown suggested at the prompt, minutes or `h:mm:ss`; `"0"` suggests
---nothing (`org-timer-default-timer`). (default: `"0"`)
---@field default_timer? string

---------------------------------------------------------------------------
-- Links
---------------------------------------------------------------------------

---A link as passed to a custom link type handler.
---@class org.Config.Links.Link
---Link target as written inside `[[...]]`.
---@field target string
---Link type (the scheme before `:`).
---@field type string
---Part after `type:`.
---@field path string

---Handler that opens a custom link type (`org-link-set-parameters` `:follow`).
---Receives the path after `type:` and the classified link.
---@alias org.Config.Links.TypeHandler fun(path: string, link: org.Config.Links.Link): any

---External application for `links.file_apps`: a shell command (the path is
---appended, or substituted for `%s`), `"system"`/`"default"` for the OS
---opener, or a function receiving the absolute path.
---@alias org.Config.Links.FileApp "system"|"default"|string|fun(path: string): any

---Link options.
---@class org.Config.Links
---Link abbreviations like `#+LINK:` (`org-link-abbrev-alist`), e.g.
---`{ gh = "https://github.com/%s" }`. In the replacement `%s` is the tag and
---`%h` the URL-encoded tag; otherwise the tag is appended. A function
---receiving the tag and returning the URL is also accepted. (default: `{}`)
---@field abbreviations? table<string, string|fun(tag: string): string>
---Custom link types, e.g. `{ jira = function(path, link) ... end }`
---(`org-link-set-parameters` `:follow`). (default: `{}`)
---@field types? table<string, org.Config.Links.TypeHandler>
---Ask before running `shell:` links (`org-link-shell-confirm-function`).
---(default: `true`)
---@field confirm_shell? boolean
---Store links to headlines as `id:` links (`org-id-link-to-org-use-id`):
---`true` = always, creating an ID if needed; `"create-if-interactive"` =
---create only when storing interactively; `"use-existing"` = only when the
---headline already has an ID; `false` = never. (default: `"create-if-interactive"`)
---@field use_id? boolean|"create-if-interactive"|"use-existing"
---Open files with these (lowercase) extensions with an external app
---(`org-file-apps`), e.g. `{ pdf = "open" }` or `{ pdf = "zathura %s" }`.
---(default: `{}`)
---@field file_apps? table<string, org.Config.Links.FileApp>

---------------------------------------------------------------------------
-- IDs / attachments
---------------------------------------------------------------------------

---ID options.
---@class org.Config.Id
---JSON file mapping IDs to files (`org-id-locations-file`).
---(default: `stdpath("data") .. "/org/id-locations.json"`)
---@field locations_file? string
---How new IDs are generated (`org-id-method`): `"uuid"` or `"ts"`
---(timestamp like `20240101T120000.123456`). (default: `"uuid"`)
---@field method? "uuid"|"ts"

---Attachment options.
---@class org.Config.Attach
---Attachment root (`org-attach-id-dir`), relative to the org file's
---directory unless absolute. Files go to `<dir>/<ID[1:2]>/<ID[3:]>`.
---(default: `"data/"`)
---@field dir? string
---Default attach method (`org-attach-method`): `"cp"` copy, `"mv"` move,
---`"ln"` symbolic link (absolute path), `"lns"` symbolic link (relative
---path). (default: `"cp"`)
---@field method? "cp"|"mv"|"ln"|"lns"

---------------------------------------------------------------------------
-- Babel
---------------------------------------------------------------------------

---How to run one src block language.
---@class org.Config.Babel.Language
---Command that runs the program: a string (split on whitespace) or an argv
---list. The code is written to a temp file whose path is appended (sqlite
---gets the `:db` path and the code on stdin). Required to evaluate a
---language not in the defaults; `lua` always runs inside Neovim.
---@field cmd? string|string[]
---Extension of the temp file / tangled file, e.g. `"py"`. Defaults to a
---built-in per-language table, else the language name.
---@field ext? string

---Default header arguments (`org-babel-default-header-args`). Keys are
---header argument names without `:`; values are strings.
---@class org.Config.Babel.HeaderArgs
---(default: `"replace"`)
---@field results? string
---(default: `"code"`)
---@field exports? "code"|"results"|"both"|"none"|string
---`"none"`, or a session name: blocks with the same language and session
---name share one running interpreter. (default: `"none"`)
---@field session? string
---(default: `"no"`)
---@field noweb? "yes"|"no"|"tangle"|"no-export"|"strip-export"|"eval"|string
---(default: `"no"`)
---@field tangle? "yes"|"no"|string
---@field [string] string|number

---Source block evaluation (Babel) options.
---@class org.Config.Babel
---Ask before evaluating a src block (`org-confirm-babel-evaluate`); `:eval`
---header args still apply. (default: `true`)
---@field confirm_evaluate? boolean
---Results with at least this many lines use an example block instead of
---`: ` lines (`org-babel-min-lines-for-block-output`). (default: `10`)
---@field min_lines_for_block_output? integer
---Kill evaluation after this many milliseconds; for a `:session`, stop
---waiting for the answer. (default: `30000`)
---@field timeout? integer
---Evaluate code blocks, `#+CALL` lines and inline code when exporting, like
---Emacs `org-export-use-babel`: `:exports results|both` blocks get fresh
---results in the exported copy (the buffer is not changed). `confirm_evaluate`
---still applies. When `false`, export uses the buffer as it is and ignores
---`:exports`. (default: `true`)
---@field evaluate_on_export? boolean
---Default header arguments, merged key by key with the defaults.
---(default: `{ results = "replace", exports = "code", session = "none", noweb = "no", tangle = "no" }`)
---@field default_header_args? org.Config.Babel.HeaderArgs
---Languages that can be evaluated, merged key by key with the defaults
---(sh, shell, bash, zsh, fish, python, python3, lua, js, javascript,
---typescript, ts, ruby, perl, php, r, R, go, rust, sqlite, awk). Set a
---language to `false` to remove it.
---@field languages? table<string, org.Config.Babel.Language|false>

---------------------------------------------------------------------------
-- Export
---------------------------------------------------------------------------

---HTML back-end options (ox-html).
---@class org.Config.Export.Html
---(`org-html-doctype`) (default: `"xhtml-strict"`)
---@field doctype? string
---(`org-html-html5-fancy`) (default: `false`)
---@field html5_fancy? boolean
---(`org-html-container-element`) (default: `"div"`)
---@field container? string
---(`org-html-content-class`) (default: `"content"`)
---@field content_class? string
---(`org-html-extension`) (default: `"html"`)
---@field extension? string
---(`org-html-head-include-default-style`) (default: `true`)
---@field head_include_default_style? boolean
---Extra CSS put after the default style; `false` = no default style.
---(default: `nil`)
---@field style? string|false
---(`org-html-head`) (default: `""`)
---@field head? string|fun(info: table): string
---(`org-html-head-extra`) (default: `""`)
---@field head_extra? string|fun(info: table): string
---(`org-html-head-include-scripts`) (default: `false`)
---@field head_include_scripts? boolean
---(`org-html-preamble`): `true`, `false`, a format string or a function.
---(default: `true`)
---@field preamble? boolean|string|fun(info: table): string
---(`org-html-postamble`): `"auto"`, `true`, `false`, a format string or a
---function. (default: `"auto"`)
---@field postamble? boolean|string|fun(info: table): string
---(`org-html-postamble-format`), per language. (default: Emacs value)
---@field postamble_format? table<string, string>
---(`org-html-preamble-format`), per language. (default: `nil`)
---@field preamble_format? table<string, string>
---(`org-html-validation-link`) (default: Emacs value)
---@field validation_link? string|false
---(`org-html-creator-string`) (default: `nil` = `creator`)
---@field creator_string? string
---(`org-html-link-home`) (default: `""`)
---@field link_home? string
---(`org-html-link-up`) (default: `""`)
---@field link_up? string
---(`org-html-link-use-abs-url`) (default: `false`)
---@field link_use_abs_url? boolean
---(`org-html-link-org-files-as-html`) (default: `true`)
---@field link_org_files_as_html? boolean
---(`org-html-metadata-timestamp-format`) (default: `"%Y-%m-%d %a %H:%M"`)
---@field metadata_timestamp_format? string
---(`org-html-toplevel-hlevel`) (default: `2`)
---@field toplevel_hlevel? integer
---(`org-html-self-link-headlines`) (default: `false`)
---@field self_link_headlines? boolean
---(`org-html-prefer-user-labels`) (default: `false`)
---@field prefer_user_labels? boolean
---(`org-html-checkbox-type`) (default: `"ascii"`)
---@field checkbox_type? "ascii"|"unicode"|"html"
---(`org-html-inline-images`) (default: `true`)
---@field inline_images? boolean
---(`org-html-table-caption-above`) (default: `true`)
---@field table_caption_above? boolean
---(`org-html-footnote-format`) (default: `"<sup>%s</sup>"`)
---@field footnote_format? string
---(`org-html-footnote-separator`) (default: `"<sup>, </sup>"`)
---@field footnote_separator? string
---(`org-html-equation-reference-format`) (default: `"\\eqref{%s}"`)
---@field equation_reference_format? string
---(`org-html-use-infojs`) (default: `"when-configured"`)
---@field use_infojs? boolean|"when-configured"
---(`org-html-wrap-src-lines`) (default: `false`)
---@field wrap_src_lines? boolean
---Load MathJax for LaTeX fragments (`org-html-with-latex` = `mathjax`).
---(default: `true`)
---@field mathjax? boolean
---(`org-html-mathjax-options`) (default: Emacs value)
---@field mathjax_options? table
---Highlight source code (Emacs uses htmlize): `function(code, lang)`
---returning HTML. (default: `nil`)
---@field fontify? fun(code: string, lang: string): string

---LaTeX back-end options (ox-latex).
---@class org.Config.Export.Latex
---(`org-latex-default-class`) (default: `"article"`)
---@field default_class? string
---(`org-latex-classes`): `{ { name, header, { open, close } | format, ... } }`.
---(default: `nil` = the Emacs list)
---@field classes? table[]
---(`org-latex-default-packages-alist`) (default: `nil` = the Emacs list)
---@field default_packages? table[]
---(`org-latex-packages-alist`) (default: `{}`)
---@field packages? table[]
---(`org-latex-compiler`) (default: `"pdflatex"`)
---@field compiler? string
---(`org-latex-pdf-process`): list of commands with `%f %b %o %O %latex %bib`.
---(default: `nil` = latexmk when available, else three `%latex` runs)
---@field pdf_process? string[]
---(`org-latex-bib-compiler`) (default: `"bibtex"`)
---@field bib_compiler? string
---(`org-latex-remove-logfiles`) (default: `true`)
---@field remove_logfiles? boolean
---Compile PDFs in the background with `vim.system`. (default: `true`)
---@field async_compile? boolean
---(`org-latex-src-block-backend`) (default: `"verbatim"`)
---@field src_block_backend? "verbatim"|"listings"|"minted"
---(`org-latex-caption-above`) (default: `{ "table" }`)
---@field caption_above? boolean|string[]
---(`org-latex-prefer-user-labels`) (default: `false`)
---@field prefer_user_labels? boolean
---(`org-latex-reference-command`) (default: `"\\ref{%s}"`)
---@field reference_command? string
---(`org-latex-tables-booktabs`) (default: `false`)
---@field tables_booktabs? boolean
---(`org-latex-tables-centered`) (default: `true`)
---@field tables_centered? boolean
---(`org-latex-images-centered`) (default: `true`)
---@field images_centered? boolean
---(`org-latex-image-default-width`) (default: `".9\\linewidth"`)
---@field image_default_width? string
---(`org-latex-default-figure-position`) (default: `"htbp"`)
---@field default_figure_position? string
---(`org-latex-default-table-environment`) (default: `"tabular"`)
---@field default_table_environment? string
---(`org-latex-default-table-mode`) (default: `"table"`)
---@field default_table_mode? string
---(`org-latex-title-command`) (default: `"\\maketitle"`)
---@field title_command? string
---(`org-latex-toc-command`) (default: `"\\tableofcontents\n\n"`)
---@field toc_command? string
---(`org-latex-hyperref-template`) (default: `nil` = the Emacs template)
---@field hyperref_template? string
---(`org-latex-use-sans`) (default: `false`)
---@field use_sans? boolean

---Markdown back-end options (ox-md).
---@class org.Config.Export.Md
---(`org-md-headline-style`) (default: `"atx"`)
---@field headline_style? "atx"|"setext"|"mixed"
---(`org-md-toplevel-hlevel`) (default: `1`)
---@field toplevel_hlevel? integer
---(`org-md-footnote-format`) (default: `"<sup>%s</sup>"`)
---@field footnote_format? string
---(`org-md-footnotes-section`) (default: `"%s%s"`)
---@field footnotes_section? string
---(`org-md-link-org-files-as-md`) (default: `true`)
---@field link_org_files_as_md? boolean

---Org back-end options (ox-org).
---@class org.Config.Export.Org
---(`org-org-with-special-rows`) (default: `true`)
---@field with_special_rows? boolean

---Beamer back-end options (ox-beamer).
---@class org.Config.Export.Beamer
---(`org-beamer-frame-level`) (default: `1`)
---@field frame_level? integer
---(`org-beamer-frame-default-options`) (default: `""`)
---@field frame_default_options? string
---(`org-beamer-outline-frame-title`) (default: `"Outline"`)
---@field outline_frame_title? string
---(`org-beamer-outline-frame-options`) (default: `""`)
---@field outline_frame_options? string
---(`org-beamer-subtitle-format`) (default: `"\\subtitle{%s}"`)
---@field subtitle_format? string
---(`org-beamer-theme`) (default: `"default"`)
---@field theme? string
---(`org-beamer-environments-extra`): `{ { name, key, open, close }, ... }`.
---(default: `{}`)
---@field environments_extra? string[][]
---(`org-beamer-frame-environment`) (default: `"orgframe"`)
---@field frame_environment? string

---iCalendar back-end options (ox-icalendar).
---@class org.Config.Export.Icalendar
---(`org-icalendar-combined-agenda-file`) (default: `"~/org.ics"`)
---@field combined_agenda_file? string
---(`org-icalendar-combined-name`) (default: `"OrgMode"`)
---@field combined_name? string
---(`org-icalendar-combined-description`) (default: `""`)
---@field combined_description? string
---(`org-icalendar-alarm-time`), minutes. (default: `0`)
---@field alarm_time? integer
---(`org-icalendar-force-alarm`) (default: `false`)
---@field force_alarm? boolean
---(`org-icalendar-exclude-tags`) (default: `{}`)
---@field exclude_tags? string[]
---(`org-icalendar-scheduled-summary-prefix`) (default: `"S: "`)
---@field scheduled_summary_prefix? string
---(`org-icalendar-deadline-summary-prefix`) (default: `"DL: "`)
---@field deadline_summary_prefix? string
---(`org-icalendar-use-deadline`) (default: `{ "event-if-not-todo", "todo-due" }`)
---@field use_deadline? string[]
---(`org-icalendar-use-scheduled`) (default: `{ "todo-start" }`)
---@field use_scheduled? string[]
---(`org-icalendar-categories`) (default: `{ "local-tags", "category" }`)
---@field categories? string[]
---(`org-icalendar-with-timestamps`) (default: `"active"`)
---@field with_timestamps? boolean|"active"|"inactive"
---(`org-icalendar-include-todo`) (default: `false`)
---@field include_todo? boolean|"unblocked"|"all"|string[]
---(`org-icalendar-todo-unscheduled-start`) (default: `"recurring-deadline-warning"`)
---@field todo_unscheduled_start? string|false
---(`org-icalendar-include-sexps`); diary sexps are not supported. (default: `true`)
---@field include_sexps? boolean
---(`org-icalendar-include-body`): `true` or a number of characters. (default: `true`)
---@field include_body? boolean|integer
---(`org-icalendar-store-UID`) (default: `false`)
---@field store_uid? boolean
---(`org-icalendar-timezone`) (default: `nil` = `$TZ`)
---@field timezone? string
---(`org-icalendar-date-time-format`) (default: `":%Y%m%dT%H%M%S"`)
---@field date_time_format? string
---(`org-icalendar-ttl`) (default: `nil`)
---@field ttl? string
---(`org-agenda-default-appointment-duration`), minutes. (default: `nil`)
---@field default_appointment_duration? integer
---(`org-icalendar-after-save-hook`) (default: `nil`)
---@field after_save_hook? fun(path: string)

---Publishing options (ox-publish).
---@class org.Config.Export.Publish
---(`org-publish-project-alist`): `{ name = { base_directory = ..., ... } }`
---or a list of project tables with a `name` field. (default: `{}`)
---@field projects? table
---(`org-publish-timestamp-directory`) (default: `stdpath("data") .. "/org-timestamps/"`)
---@field timestamp_directory? string
---(`org-publish-use-timestamps-flag`) (default: `true`)
---@field use_timestamps_flag? boolean
---(`org-publish-list-skipped-files`) (default: `true`)
---@field list_skipped_files? boolean
---(`org-publish-sitemap-sort-files`) (default: `"alphabetically"`)
---@field sitemap_sort_files? "alphabetically"|"chronologically"|"anti-chronologically"|false
---(`org-publish-sitemap-sort-folders`) (default: `"ignore"`)
---@field sitemap_sort_folders? "first"|"last"|"ignore"
---(`org-publish-sitemap-sort-ignore-case`) (default: `false`)
---@field sitemap_sort_ignore_case? boolean
---(`org-publish-after-publishing-hook`) (default: `nil`)
---@field after_publishing_hook? fun(src: string, out: string)

---ASCII back-end options (ox-ascii).
---@class org.Config.Export.Ascii
---(`org-ascii-charset`) (default: `"ascii"`)
---@field charset? "ascii"|"latin1"|"utf-8"
---(`org-ascii-text-width`) (default: `nil` = `export.text_width`, else `72`)
---@field text_width? integer
---(`org-ascii-global-margin`) (default: `0`)
---@field global_margin? integer
---(`org-ascii-inner-margin`) (default: `2`)
---@field inner_margin? integer
---(`org-ascii-quote-margin`) (default: `6`)
---@field quote_margin? integer
---(`org-ascii-list-margin`) (default: `0`)
---@field list_margin? integer
---(`org-ascii-inlinetask-width`) (default: `30`)
---@field inlinetask_width? integer
---(`org-ascii-headline-spacing`): `{ before, after }` or `false`. (default: `{ 1, 2 }`)
---@field headline_spacing? integer[]|false
---(`org-ascii-indented-line-width`) (default: `"auto"`)
---@field indented_line_width? integer|"auto"
---(`org-ascii-paragraph-spacing`) (default: `"auto"`)
---@field paragraph_spacing? integer|"auto"
---(`org-ascii-links-to-notes`) (default: `true`)
---@field links_to_notes? boolean
---(`org-ascii-table-keep-all-vertical-lines`) (default: `false`)
---@field table_keep_all_vertical_lines? boolean
---(`org-ascii-table-widen-columns`) (default: `true`)
---@field table_widen_columns? boolean
---(`org-ascii-table-use-ascii-art`), not supported. (default: `false`)
---@field table_use_ascii_art? boolean
---(`org-ascii-caption-above`) (default: `false`)
---@field caption_above? boolean
---(`org-ascii-verbatim-format`) (default: ``"`%s'"``)
---@field verbatim_format? string
---(`org-ascii-bullets`) (default: `nil` = the Emacs bullets)
---@field bullets? table<string, string[]>
---(`org-ascii-underline`) (default: `nil` = the Emacs characters)
---@field underline? table<string, string[]>
---(`org-ascii-format-drawer-function`) (default: `nil`)
---@field format_drawer_function? fun(name: string, contents: string, width: integer): string
---(`org-ascii-format-inlinetask-function`) (default: `nil`)
---@field format_inlinetask_function? function

---Citation export options (oc, oc-basic).
---@class org.Config.Export.Cite
---(`org-cite-export-processors`): `{ [backend] = { name, bibstyle, citestyle } | name }`,
---`t` is the fallback. (default: `{ t = { "basic" } }`)
---@field export_processors? table<string, string|string[]>
---(`org-cite-global-bibliography`) (default: `{}`)
---@field global_bibliography? string[]
---(`org-cite-adjust-note-numbers`) (default: `true`)
---@field adjust_note_numbers? boolean
---(`org-cite-note-rules`) (default: `nil` = the Emacs rules)
---@field note_rules? table<string, string[]>
---(`org-cite-punctuation-marks`) (default: `{ ".", ",", ";", ":", "!", "?" }`)
---@field punctuation_marks? string[]
---(`org-cite-basic-sorting-field`) (default: `"author"`)
---@field basic_sorting_field? string|false
---(`org-cite-basic-author-year-separator`) (default: `", "`)
---@field basic_author_year_separator? string
---(`org-cite-natbib-options`) (default: `{}`)
---@field natbib_options? string[]
---(`org-cite-biblatex-options`) (default: `nil`)
---@field biblatex_options? string
---(`org-cite-biblatex-styles`) (default: `nil` = the Emacs table)
---@field biblatex_styles? table
---(`org-cite-biblatex-style-shortcuts`) (default: `nil` = the Emacs table)
---@field biblatex_style_shortcuts? table

---Pandoc options (ODT/DOCX/RST/EPUB export).
---@class org.Config.Export.Pandoc
---Pandoc executable: a string (split on whitespace) or an argv list.
---(default: `"pandoc"`)
---@field cmd? string|string[]
---Extra arguments passed to pandoc. (default: `{}`)
---@field args? string[]

---Export options. `#+OPTIONS:`, keywords and `EXPORT_*` properties override
---the `with_*` values; each option names the Emacs variable it mirrors.
---@class org.Config.Export
---Output directory, relative to the source file unless absolute; `nil` =
---next to the source file. (default: `nil`)
---@field output_dir? string
---Open the exported file with the system opener. (default: `false`)
---@field open_after_export? boolean
---(`org-export-with-toc`, `toc:`) (default: `true`)
---@field with_toc? boolean|integer
---(`org-export-with-section-numbers`, `num:`) (default: `true`)
---@field with_section_numbers? boolean|integer
---(`org-export-headline-levels`, `H:`) (default: `3`)
---@field headline_levels? integer
---(`org-export-with-author`, `author:`) (default: `true`)
---@field with_author? boolean
---(`org-export-with-date`, `date:`) (default: `true`)
---@field with_date? boolean
---(`org-export-with-email`, `email:`) (default: `false`)
---@field with_email? boolean
---(`org-export-with-creator`, `creator:`) (default: `false`)
---@field with_creator? boolean
---(`org-export-with-title`, `title:`) (default: `true`)
---@field with_title? boolean
---(`org-export-with-todo-keywords`, `todo:`) (default: `true`)
---@field with_todo_keywords? boolean
---(`org-export-with-tags`, `tags:`) (default: `true`)
---@field with_tags? boolean|"not-in-toc"
---(`org-export-with-priority`, `pri:`) (default: `false`)
---@field with_priority? boolean
---(`org-export-with-drawers`, `d:`): `true`, `false`, a list of names, or
---`{ ["not"] = { ... } }`. (default: `{ ["not"] = { "LOGBOOK" } }`)
---@field with_drawers? boolean|string[]|table
---(`org-export-with-properties`, `prop:`) (default: `false`)
---@field with_properties? boolean|string[]
---(`org-export-with-planning`, `p:`) (default: `false`)
---@field with_planning? boolean
---(`org-export-with-clocks`, `c:`) (default: `false`)
---@field with_clocks? boolean
---(`org-export-with-timestamps`, `<:`) (default: `true`)
---@field with_timestamps? boolean|"active"|"inactive"
---(`org-export-with-tasks`, `tasks:`) (default: `true`)
---@field with_tasks? boolean|"todo"|"done"|string[]
---(`org-export-with-archived-trees`, `arch:`) (default: `"headline"`)
---@field with_archived_trees? boolean|"headline"
---(`org-export-with-emphasize`, `*:`) (default: `true`)
---@field with_emphasize? boolean
---(`org-export-with-entities`, `e:`) (default: `true`)
---@field with_entities? boolean
---(`org-export-with-fixed-width`, `::`) (default: `true`)
---@field with_fixed_width? boolean
---(`org-export-with-footnotes`, `f:`) (default: `true`)
---@field with_footnotes? boolean
---(`org-export-with-inlinetasks`, `inline:`) (default: `true`)
---@field with_inlinetasks? boolean
---(`org-export-with-latex`, `tex:`) (default: `true`)
---@field with_latex? boolean|"verbatim"
---(`org-export-with-smart-quotes`, `':`) (default: `false`)
---@field with_smart_quotes? boolean
---(`org-export-with-special-strings`, `-:`) (default: `true`)
---@field with_special_strings? boolean
---(`org-export-with-statistics-cookies`, `stat:`) (default: `true`)
---@field with_statistics_cookies? boolean
---(`org-export-with-sub-superscripts`, `^:`) (default: `true`)
---@field with_sub_superscripts? boolean|"{}"
---(`org-export-with-tables`, `|:`) (default: `true`)
---@field with_tables? boolean
---(`org-export-with-broken-links`, `broken-links:`): `false` stops the export,
---`true` ignores broken links, `"mark"` marks them. (default: `false`)
---@field with_broken_links? boolean|"mark"
---(`org-export-preserve-breaks`, `\n:`) (default: `false`)
---@field preserve_breaks? boolean
---(`org-export-timestamp-file`, `timestamp:`) (default: `true`)
---@field timestamp_file? boolean
---(`org-export-expand-links`) (default: `true`)
---@field expand_links? boolean
---(`org-export-select-tags`) (default: `{ "export" }`)
---@field select_tags? string[]
---(`org-export-exclude-tags`) (default: `{ "noexport" }`)
---@field exclude_tags? string[]
---(`org-export-default-language`) (default: `"en"`)
---@field default_language? string
---(`org-export-date-timestamp-format`) (default: `nil`)
---@field date_timestamp_format? string
---(`user-full-name`); `nil` = the system user's full name. (default: `nil`)
---@field author? string
---(`user-mail-address`) (default: `nil`)
---@field email? string
---(`org-export-creator-string`) (default: `nil` = Neovim and org.nvim versions)
---@field creator? string
---(`org-export-global-macros`): `{ name = "template $1" | function(...) }`.
---(default: `{}`)
---@field global_macros? table<string, string|function>
---(`org-export-snippet-translation-alist`) (default: `{}`)
---@field snippet_translation? table<string, string>
---(`org-inlinetask-min-level`) (default: `15`)
---@field inlinetask_min_level? integer
---(`org-table-number-fraction`) (default: `0.5`)
---@field table_number_fraction? number
---`{ before_processing = fn, before_parsing = fn }`, `fn(backend, lines)`
---returning new lines (`org-export-before-processing-functions`,
---`org-export-before-parsing-functions`). (default: `{}`)
---@field hooks? table<string, function>
---Filters (`org-export-filter-TYPE-functions`): `{ [type] = fn | fn[] }`,
---`fn(text, backend, info)` returning the new text (`nil` keeps it). Types are
---element/object types plus `"body"`, `"final-output"`, `"parse-tree"` and
---`"options"`. (default: `{}`)
---@field filters? table<string, function|function[]>
---@field html? org.Config.Export.Html
---@field latex? org.Config.Export.Latex
---@field md? org.Config.Export.Md
---@field org? org.Config.Export.Org
---@field beamer? org.Config.Export.Beamer
---@field icalendar? org.Config.Export.Icalendar
---@field publish? org.Config.Export.Publish
---@field ascii? org.Config.Export.Ascii
---@field cite? org.Config.Export.Cite
---Legacy alias of `ascii.text_width`. (default: `72`)
---@field text_width? integer
---@field pandoc? org.Config.Export.Pandoc
