Output docs/media/babel.gif
Source docs/media/tapes/common.tape

Hide
Type "export ORG_DEMO_DIR=/tmp/org-demo-babel; clear; nvim -u docs/media/demo/init.lua $ORG_DEMO_DIR/babel.org" Enter
Sleep 2.5s
Show
Sleep 1s
Type "/import" Enter Sleep 600ms
Ctrl+C Ctrl+C Sleep 2.5s
Type "/printf" Enter Sleep 600ms
Ctrl+C Ctrl+C Sleep 2s
Type "/vim.version" Enter Sleep 600ms
Ctrl+C Ctrl+C Sleep 1.5s
Type "zz" Sleep 1.5s
Sleep 1s
