-- Regenerate lua/org/extensions/ics/tz_rules.lua from the system's zoneinfo:
--   nvim -l scripts/gen_tz_rules.lua [/usr/share/zoneinfo]
-- Each zone's POSIX TZ rule (the footer of its TZif file) is what the ics
-- extension falls back to where there is no zoneinfo (Windows).
local dir = arg[1] or "/usr/share/zoneinfo"
local version = (io.open(dir .. "/+VERSION") or io.open(dir .. "/tzdata.zi") or { read = function() end })
local ver = version:read("*l") or "?"
local rules = {}
local function walk(rel)
  for name, kind in vim.fs.dir(dir .. (rel == "" and "" or "/" .. rel)) do
    local path = rel == "" and name or (rel .. "/" .. name)
    if kind == "directory" and not name:match("^posix") and not name:match("^right") then
      walk(path)
    elseif kind == "file" and name:match("^[A-Z]") then
      local f = io.open(dir .. "/" .. path, "rb")
      local data = f:read("*a")
      f:close()
      local footer = data:sub(1, 4) == "TZif" and data:match("\n([^\n]*)\n$")
      if footer and footer ~= "" then
        rules[path] = footer
      end
    end
  end
end
walk("")
local names = vim.tbl_keys(rules)
table.sort(names)
local out = {
  "-- Generated by scripts/gen_tz_rules.lua from tzdata " .. vim.trim(ver:gsub("^#%s*version%s*", "")) .. ": do not edit.",
  "-- The current POSIX TZ rule of each IANA zone, for systems without",
  "-- zoneinfo files (Windows). Rules only: no past changes of a zone.",
  "return {",
}
for _, n in ipairs(names) do
  out[#out + 1] = string.format("  [%q] = %q,", n, rules[n])
end
out[#out + 1] = "}"
local f = assert(io.open("lua/org/extensions/ics/tz_rules.lua", "wb"))
f:write(table.concat(out, "\n") .. "\n")
f:close()
print(#names .. " zones")
