local archive = require("org.archive")
local config = require("org.config")
local utils = require("org.utils")
vim.g.org_test = true

describe("archive", function()
  it("parses locations", function()
    local l = archive.parse_location("%s_archive::", "/x/y.org")
    eq("/x/y.org_archive", l.filename)
    eq(nil, l.heading)
    l = archive.parse_location("::* Archived Tasks", "/x/y.org")
    eq("/x/y.org", l.filename)
    eq("Archived Tasks", l.heading)
    eq(1, l.level)
    l = archive.parse_location("arch/%s::** From %s", "/x/y.org")
    ok(l.filename:match("/x/arch/x/y.org") or l.filename:match("arch"), l.filename)
    eq(2, l.level)
    l = archive.parse_location("other.org::", "/x/y.org")
    eq("/x/other.org", l.filename)
  end)

  it("archives to the _archive file with context", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, "p")
    local p = dir .. "/tasks.org"
    utils.writefile(p, { "#+FILETAGS: :f:", "* Project :proj:", "** DONE Finish :x:", "   CLOSED: [2026-09-20 Sun]", "** Keep" })
    config.setup({ org_directory = dir, agenda_files = { dir } })
    vim.cmd("edit! " .. p)
    vim.api.nvim_win_set_cursor(0, { 3, 0 })
    archive.archive_subtree()
    eq({ "#+FILETAGS: :f:", "* Project :proj:", "** Keep" }, vim.tbl_map(function(l)
      return (l:gsub("%s+", " "))
    end, buf_lines()))
    local a = utils.readfile(p .. "_archive")
    eq("#    -*- mode: org -*-", a[1])
    ok(a[4]:match("^Archived entries from file .*/tasks%.org$"), a[4])
    local text = table.concat(a, "\n")
    ok(text:find("\n%* DONE Finish"), text)
    ok(text:find(":ARCHIVE_OLPATH: Project", 1, true), text)
    ok(text:find(":ARCHIVE_TODO: DONE", 1, true))
    ok(text:find(":ARCHIVE_CATEGORY: tasks", 1, true))
    ok(text:find(":ARCHIVE_ITAGS: f proj", 1, true))
    ok(text:find(":ARCHIVE_TIME: %[", 1, false))
  end)

  it("archives under a heading in the same file via #+ARCHIVE", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, "p")
    local p = dir .. "/s.org"
    utils.writefile(p, { "#+ARCHIVE: ::* Archive", "* A", "* B" })
    config.setup({ org_directory = dir, agenda_files = { dir }, archive_save_context_info = { "todo" } })
    vim.cmd("edit! " .. p)
    vim.api.nvim_win_set_cursor(0, { 2, 0 })
    archive.archive_subtree()
    eq({ "#+ARCHIVE: ::* Archive", "* B", "* Archive", "** A" }, buf_lines())
  end)

  it("toggles the ARCHIVE tag", function()
    config.setup({ tags_column = 0 })
    org_buffer({ "* Task :a:" }, { 1, 0 })
    archive.toggle_archive_tag()
    eq("* Task :a:ARCHIVE:", buf_lines()[1])
    archive.toggle_archive_tag()
    eq("* Task :a:", buf_lines()[1])
    config.setup({})
  end)
end)
