-- Columnview dynamic blocks compared with Emacs Org 9.8.10: each expected
-- buffer is what org-update-all-dblocks produced on the same input
-- (including the summaries Emacs writes back into property drawers).
local dblock = require("org.dblock")

describe("columnview blocks (Emacs parity)", function()
  local cases = {
    {
      "cv_basic",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global",
        "| <40>    |      |        |      |       |",
        "| ITEM    | TODO | Effort | Cost | Done  |",
        "|---------+------+--------+------+-------|",
        "| Project | TODO |   2:15 |  4.1 | [1/2] |",
        "| Task A  | DONE |   1:30 |  1.1 | [X]   |",
        "| Task B  | TODO |   0:45 |    3 | [ ]   |",
        "| Sub B1  |      |        |    3 |       |",
        "| Other   |      |        |   10 |       |",
        "#+END:",
      },
    },
    {
      "cv_default_fmt",
      {
        "* A",
        ":PROPERTIES:",
        ":X: 1",
        ":END:",
        "** B",
        "",
        "#+BEGIN: columnview :id global",
        "#+END:",
      },
      {
        "* A",
        ":PROPERTIES:",
        ":X: 1",
        ":END:",
        "** B",
        "",
        "#+BEGIN: columnview :id global",
        "| <25> |      | <3>      |      |",
        "| ITEM | TODO | PRIORITY | TAGS |",
        "|------+------+----------+------|",
        "| A    |      | B        |      |",
        "| B    |      | B        |      |",
        "#+END:",
      },
    },
    {
      "cv_exclude",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :exclude-tags (\"work\")",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :exclude-tags (\"work\")",
        "| <40>    |      |        |      |       |",
        "| ITEM    | TODO | Effort | Cost | Done  |",
        "|---------+------+--------+------+-------|",
        "| Project | TODO |   2:15 |  4.1 | [1/2] |",
        "| Task A  | DONE |   1:30 |  1.1 | [X]   |",
        "| Other   |      |        |   10 |       |",
        "#+END:",
      },
    },
    {
      "cv_format",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :format \"%ITEM(Name) %Cost(Money){+;%.1f}\"",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3.0",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :format \"%ITEM(Name) %Cost(Money){+;%.1f}\"",
        "| Name    | Money |",
        "|---------+-------|",
        "| Project |   4.1 |",
        "| Task A  |   1.1 |",
        "| Task B  |   3.0 |",
        "| Sub B1  |   3.0 |",
        "| Other   |  10.0 |",
        "#+END:",
      },
    },
    {
      "cv_hlines",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :hlines 1",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :hlines 1",
        "| <40>    |      |        |      |       |",
        "| ITEM    | TODO | Effort | Cost | Done  |",
        "|---------+------+--------+------+-------|",
        "| Project | TODO |   2:15 |  4.1 | [1/2] |",
        "| Task A  | DONE |   1:30 |  1.1 | [X]   |",
        "| Task B  | TODO |   0:45 |    3 | [ ]   |",
        "| Sub B1  |      |        |    3 |       |",
        "|---------+------+--------+------+-------|",
        "| Other   |      |        |   10 |       |",
        "#+END:",
      },
    },
    {
      "cv_hlines_t",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :hlines t",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :hlines t",
        "| <40>    |      |        |      |       |",
        "| ITEM    | TODO | Effort | Cost | Done  |",
        "|---------+------+--------+------+-------|",
        "| Project | TODO |   2:15 |  4.1 | [1/2] |",
        "|---------+------+--------+------+-------|",
        "| Task A  | DONE |   1:30 |  1.1 | [X]   |",
        "|---------+------+--------+------+-------|",
        "| Task B  | TODO |   0:45 |    3 | [ ]   |",
        "|---------+------+--------+------+-------|",
        "| Sub B1  |      |        |    3 |       |",
        "|---------+------+--------+------+-------|",
        "| Other   |      |        |   10 |       |",
        "#+END:",
      },
    },
    {
      "cv_indent",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :indent t",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :indent t",
        "| <40>         |      |        |      |       |",
        "| ITEM         | TODO | Effort | Cost | Done  |",
        "|--------------+------+--------+------+-------|",
        "| Project      | TODO |   2:15 |  4.1 | [1/2] |",
        "| \\_  Task A   | DONE |   1:30 |  1.1 | [X]   |",
        "| \\_  Task B   | TODO |   0:45 |    3 | [ ]   |",
        "| \\_    Sub B1 |      |        |    3 |       |",
        "| Other        |      |        |   10 |       |",
        "#+END:",
      },
    },
    {
      "cv_local",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        "#+BEGIN: columnview",
        "#+END:",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        "#+BEGIN: columnview",
        "| <40>   |      |        |      |      |",
        "| ITEM   | TODO | Effort | Cost | Done |",
        "|--------+------+--------+------+------|",
        "| Sub B1 |      |        |      |      |",
        "#+END:",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
      },
    },
    {
      "cv_match",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :match \"work\"",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :match \"work\"",
        "| <40>   |      |        |      |      |",
        "| ITEM   | TODO | Effort | Cost | Done |",
        "|--------+------+--------+------+------|",
        "| Task B | TODO |   0:45 |    3 | [ ]  |",
        "| Sub B1 |      |        |    3 |      |",
        "#+END:",
      },
    },
    {
      "cv_maxlevel",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :maxlevel 1",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :maxlevel 1",
        "| <40>    |      |        |      |       |",
        "| ITEM    | TODO | Effort | Cost | Done  |",
        "|---------+------+--------+------+-------|",
        "| Project | TODO |   2:15 |  4.1 | [1/2] |",
        "| Other   |      |        |   10 |       |",
        "#+END:",
      },
    },
    {
      "cv_nochildval",
      {
        "#+COLUMNS: %ITEM %Cost{+}",
        "* P",
        ":PROPERTIES:",
        ":Cost: 99",
        ":END:",
        "** C1",
        "** C2",
        "",
        "#+BEGIN: columnview :id global",
        "#+END:",
      },
      {
        "#+COLUMNS: %ITEM %Cost{+}",
        "* P",
        ":PROPERTIES:",
        ":Cost: 99",
        ":END:",
        "** C1",
        "** C2",
        "",
        "#+BEGIN: columnview :id global",
        "| ITEM | Cost |",
        "|------+------|",
        "| P    |   99 |",
        "| C1   |      |",
        "| C2   |      |",
        "#+END:",
      },
    },
    {
      "cv_plus_float",
      {
        "#+COLUMNS: %ITEM %Cost{+}",
        "* P",
        "** C1",
        ":PROPERTIES:",
        ":Cost: 1.25",
        ":END:",
        "** C2",
        ":PROPERTIES:",
        ":Cost: 2.5",
        ":END:",
        "** C3",
        ":PROPERTIES:",
        ":Cost: abc",
        ":END:",
        "",
        "#+BEGIN: columnview :id global",
        "#+END:",
      },
      {
        "#+COLUMNS: %ITEM %Cost{+}",
        "* P",
        "** C1",
        ":PROPERTIES:",
        ":Cost: 1.25",
        ":END:",
        "** C2",
        ":PROPERTIES:",
        ":Cost: 2.5",
        ":END:",
        "** C3",
        ":PROPERTIES:",
        ":Cost: abc",
        ":END:",
        "",
        "#+BEGIN: columnview :id global",
        "| ITEM | Cost |",
        "|------+------|",
        "| P    | 3.75 |",
        "| C1   | 1.25 |",
        "| C2   |  2.5 |",
        "| C3   |  abc |",
        "#+END:",
      },
    },
    {
      "cv_skip",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :skip-empty-rows t :format \"%ITEM %Done\"",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :skip-empty-rows t :format \"%ITEM %Done\"",
        "| ITEM   | Done |",
        "|--------+------|",
        "| Task A | [X]  |",
        "| Task B | [ ]  |",
        "#+END:",
      },
    },
    {
      "cv_special",
      {
        "#+COLUMNS: %ITEM %TODO %PRIORITY %TAGS %ALLTAGS %SCHEDULED %DEADLINE %CATEGORY %LEVEL",
        "#+CATEGORY: cat",
        "* TODO [#A] Head :a:",
        "SCHEDULED: <2024-01-01 Mon> DEADLINE: <2024-02-01 Thu>",
        "** Child :b:",
        "",
        "#+BEGIN: columnview :id global",
        "#+END:",
      },
      {
        "#+COLUMNS: %ITEM %TODO %PRIORITY %TAGS %ALLTAGS %SCHEDULED %DEADLINE %CATEGORY %LEVEL",
        "#+CATEGORY: cat",
        "* TODO [#A] Head :a:",
        "SCHEDULED: <2024-01-01 Mon> DEADLINE: <2024-02-01 Thu>",
        "** Child :b:",
        "",
        "#+BEGIN: columnview :id global",
        "| ITEM  | TODO | PRIORITY | TAGS | ALLTAGS | SCHEDULED        | DEADLINE         | CATEGORY | LEVEL |",
        "|-------+------+----------+------+---------+------------------+------------------+----------+-------|",
        "| Head  | TODO | A        | :a:  | :a:     | [2024-01-01 Mon] | [2024-02-01 Thu] | cat      |       |",
        "| Child |      | B        | :b:  | :a:b:   |                  |                  | cat      |       |",
        "#+END:",
      },
    },
    {
      "cv_summaries",
      {
        "#+COLUMNS: %ITEM %A{min} %B{max} %C{mean} %D{est+} %E{$} %F{X%} %G{X} %H{:min} %I{:mean} %J{+;%.2f}",
        "* Parent",
        "** One",
        ":PROPERTIES:",
        ":A: 3",
        ":B: 3",
        ":C: 3",
        ":D: 2-4",
        ":E: 1.5",
        ":F: [X]",
        ":G: [X]",
        ":H: 1:00",
        ":I: 1:00",
        ":J: 1",
        ":END:",
        "** Two",
        ":PROPERTIES:",
        ":A: 5",
        ":B: 5",
        ":C: 4",
        ":D: 1-9",
        ":E: 2",
        ":F: [ ]",
        ":G: [ ]",
        ":H: 0:30",
        ":I: 2:00",
        ":J: 2.5",
        ":END:",
        "",
        "#+BEGIN: columnview :id global",
        "#+END:",
      },
      {
        "#+COLUMNS: %ITEM %A{min} %B{max} %C{mean} %D{est+} %E{$} %F{X%} %G{X} %H{:min} %I{:mean} %J{+;%.2f}",
        "* Parent",
        "** One",
        ":PROPERTIES:",
        ":A: 3",
        ":B: 3",
        ":C: 3",
        ":D: 2-4",
        ":E: 1.5",
        ":F: [X]",
        ":G: [X]",
        ":H: 1:00",
        ":I: 1:00",
        ":J: 1",
        ":END:",
        "** Two",
        ":PROPERTIES:",
        ":A: 5",
        ":B: 5",
        ":C: 4",
        ":D: 1-9",
        ":E: 2",
        ":F: [ ]",
        ":G: [ ]",
        ":H: 0:30",
        ":I: 2:00",
        ":J: 2.5",
        ":END:",
        "",
        "#+BEGIN: columnview :id global",
        "| ITEM   | A | B |   C |    D |    E | F     | G   |    H |    I |    J |",
        "|--------+---+---+-----+------+------+-------+-----+------+------+------|",
        "| Parent | 3 | 5 | 3.5 | 4-12 | 3.50 | [50%] | [-] | 0:30 | 1:30 | 3.50 |",
        "| One    | 3 | 3 |   3 |  2-4 |  1.5 | [X]   | [X] | 1:00 | 1:00 | 1.00 |",
        "| Two    | 5 | 5 |   4 |  1-9 |    2 | [ ]   | [ ] | 0:30 | 2:00 | 2.50 |",
        "#+END:",
      },
    },
    {
      "cv_tblfm",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :format \"%ITEM %Cost\"",
        "| x |",
        "#+TBLFM: @>$2=vsum(@2..@-1)",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :format \"%ITEM %Cost\"",
        "| ITEM    |  Cost |",
        "|---------+-------|",
        "| Project |       |",
        "| Task A  |   1.1 |",
        "| Task B  | 2.222 |",
        "| Sub B1  |     3 |",
        "| Other   | 6.322 |",
        "#+TBLFM: @>$2=vsum(@2..@-1)",
        "#+END:",
      },
    },
    {
      "cv_vlines",
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":Cost: 2.222",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :vlines t",
        "#+END:",
      },
      {
        "#+COLUMNS: %40ITEM %TODO %Effort{:} %Cost{+} %Done{X/}",
        "* TODO Project [1/2]",
        "** DONE Task A",
        ":PROPERTIES:",
        ":Effort: 1:30",
        ":Cost: 1.1",
        ":Done: [X]",
        ":END:",
        "** TODO Task B :work:",
        ":PROPERTIES:",
        ":Effort: 0:45",
        ":COST:     3",
        ":Done: [ ]",
        ":END:",
        "*** Sub B1",
        ":PROPERTIES:",
        ":Cost: 3",
        ":END:",
        "* Other",
        ":PROPERTIES:",
        ":Cost: 10",
        ":END:",
        "",
        "#+BEGIN: columnview :id global :vlines t",
        "| <40> |         |      |        |      |       |",
        "|      | ITEM    | TODO | Effort | Cost | Done  |",
        "|------+---------+------+--------+------+-------|",
        "|      | Project | TODO |   2:15 |  4.1 | [1/2] |",
        "|      | Task A  | DONE |   1:30 |  1.1 | [X]   |",
        "|      | Task B  | TODO |   0:45 |    3 | [ ]   |",
        "|      | Sub B1  |      |        |    3 |       |",
        "|      | Other   |      |        |   10 |       |",
        "| /    | <>      | <>   |     <> |   <> | <>    |",
        "#+END:",
      },
    },
    {
      "cv_width",
      {
        "#+COLUMNS: %10ITEM %5X(Short)",
        "* A",
        ":PROPERTIES:",
        ":X: 1",
        ":END:",
        "",
        "#+BEGIN: columnview :id global",
        "#+END:",
      },
      {
        "#+COLUMNS: %10ITEM %5X(Short)",
        "* A",
        ":PROPERTIES:",
        ":X: 1",
        ":END:",
        "",
        "#+BEGIN: columnview :id global",
        "| <10> | <5>   |",
        "| ITEM | Short |",
        "|------+-------|",
        "| A    | 1     |",
        "#+END:",
      },
    },
  }
  for _, c in ipairs(cases) do
    it(c[1], function()
      local buf = org_buffer(c[2], { 1, 0 })
      dblock.update_all(buf)
      eq(c[3], buf_lines(buf))
    end)
  end
end)
