local date = require("org.date")
local parser = require("org.parser")
local tk = require("org.todo_keywords")

describe("date", function()
  it("civil <-> days roundtrip", function()
    for _, d in ipairs({ { 1970, 1, 1 }, { 2000, 2, 29 }, { 2026, 9, 23 }, { 1999, 12, 31 } }) do
      local n = date.days_from_civil(d[1], d[2], d[3])
      eq(d, { date.civil_from_days(n) })
    end
    eq(0, date.days_from_civil(1970, 1, 1))
  end)
  it("parses and formats timestamps", function()
    local ts = date.parse("<2026-09-23 Wed 10:00-11:30 +1w -2d>")
    eq(2026, ts.year)
    eq(10, ts.hour)
    eq(11, ts.end_hour)
    eq("+", ts.repeater.type)
    eq("-", ts.warning.type)
    eq("<2026-09-23 Wed 10:00-11:30 +1w -2d>", ts:to_string())
    eq(3, ts:weekday())
  end)
  it("parses ranges and inactive", function()
    local all = date.parse_all("x <2026-01-01 Thu>--<2026-01-03 Sat> [2026-02-01 Sun]")
    eq(2, #all)
    ok(all[1].date.range_end)
    eq(false, all[2].date.active)
  end)
  it("adds months with clamping", function()
    local d = date.parse("<2026-01-31 Sat>")
    eq("2026-02-28", d:add(1, "m"):to_date_string())
    eq("2027-01-31", d:add(1, "y"):to_date_string())
  end)
  it("applies repeaters", function()
    local now = date.parse("<2026-09-23 Wed 12:00>")
    eq("2026-09-08", date.apply_repeater(date.parse("<2026-09-01 Tue +1w>"), now):to_date_string())
    eq("2026-09-29", date.apply_repeater(date.parse("<2026-09-01 Tue ++1w>"), now):to_date_string())
    eq("2026-09-30", date.apply_repeater(date.parse("<2026-09-01 Tue .+1w>"), now):to_date_string())
  end)
  it("reads dates", function()
    local base = date.today()
    eq(base:days() + 3, date.read_date("+3d"):days())
    eq(base:days() + 14, date.read_date("+2w"):days())
    local fri = date.read_date("fri")
    eq(5, fri:weekday())
    ok(fri:days() >= base:days() and fri:days() < base:days() + 7)
    local d = date.read_date("2027-03-04 14:30")
    eq("2027-03-04", d:to_date_string())
    eq(14, d.hour)
    eq(30, d.min)
    local r = date.read_date("10:00-11:00")
    eq(11, r.end_hour)
  end)
  it("durations", function()
    eq(90, date.parse_duration("1:30"))
    eq(90, date.parse_duration("1h30min"))
    eq("1:05", date.format_duration(65))
  end)
end)

describe("todo keywords", function()
  it("parses sequences", function()
    local cfg = tk.new({ "TODO(t) NEXT(n!) | DONE(d@/!)", "WAIT | CANCELLED" })
    eq({ "TODO", "NEXT", "DONE", "WAIT", "CANCELLED" }, cfg:names())
    ok(cfg:is_done("DONE"))
    eq("time", cfg:get("NEXT").log_enter)
    eq("note", cfg:get("DONE").log_enter)
    eq("time", cfg:get("DONE").log_leave)
    eq("NEXT", cfg:cycle("TODO", 1))
    eq(nil, cfg:cycle("DONE", 1))
    eq("TODO", cfg:cycle(nil, 1))
    eq("CANCELLED", cfg:cycle("WAIT", 1))
  end)
  it("accepts flat lists", function()
    local cfg = tk.new({ "TODO", "WAITING", "|", "DONE" })
    eq(3, #cfg.keywords)
    ok(cfg:is_done("DONE"))
    local cfg2 = tk.new({ "TODO", "DONE" })
    ok(cfg2:is_done("DONE"))
  end)
end)

describe("parser", function()
  local lines = {
    "#+TITLE: Test",
    "#+FILETAGS: :proj:",
    "#+TODO: TODO NEXT | DONE",
    "* TODO [#A] First task :work:urgent:",
    "  SCHEDULED: <2026-09-23 Wed> DEADLINE: <2026-09-30 Wed -3d>",
    "  :PROPERTIES:",
    "  :ID: abc",
    "  :Effort: 1:00",
    "  :END:",
    "  :LOGBOOK:",
    "  CLOCK: [2026-09-22 Tue 10:00]--[2026-09-22 Tue 11:30] =>  1:30",
    "  :END:",
    "  Body <2026-10-01 Thu 09:00>",
    "** NEXT Child",
    "*** Grandchild :deep:",
    "* COMMENT Done one",
    "* DONE Finished",
    "  CLOSED: [2026-09-20 Sun 10:00]",
  }
  local file = parser.parse(lines, "/tmp/test.org")
  it("settings", function()
    eq("Test", file.settings.title)
    eq({ "proj" }, file.settings.filetags)
  end)
  it("headlines", function()
    eq(5, #file.headlines)
    local h = file.headlines[1]
    eq("TODO", h.todo)
    eq("A", h.priority)
    eq("First task", h.title)
    eq({ "work", "urgent" }, h.tags)
    eq(15, h.end_line)
    eq(13, h.body_end)
    eq("2026-09-23", h.planning.scheduled:to_date_string())
    eq(3, h.planning.deadline.warning.value)
    eq("abc", h.properties.ID)
    eq(90, h.clocks[1].minutes)
    eq(1, #h.timestamps)
    eq(10, h.logbook.start)
  end)
  it("hierarchy and inheritance", function()
    local g = file.headlines[3]
    eq("Grandchild", g.title)
    eq(file.headlines[2], g.parent)
    eq({ "proj", "work", "urgent", "deep" }, g:get_tags())
    eq({ "First task", "Child" }, g:outline_path())
    eq("test", g:get_category())
    ok(file.headlines[4].commented)
    ok(file.headlines[5]:is_done())
    eq(file.headlines[2], file:headline_at(14))
    eq(file.headlines[1], file:headline_at(8))
    eq(nil, file:headline_at(2))
  end)
  it("special properties", function()
    local h = file.headlines[1]
    eq("A", h:get_property("PRIORITY"))
    eq("1:00", h:get_property("effort"))
    eq("2", file.headlines[2]:get_property("LEVEL"))
  end)
end)

describe("edit", function()
  local edit = require("org.edit")
  it("builds headlines with aligned tags", function()
    local l = edit.build_headline({ level = 2, todo = "TODO", priority = "B", title = "Hello", tags = { "a", "b" } })
    eq("** TODO [#B] Hello", l:sub(1, 18))
    eq(77, vim.api.nvim_strwidth(l))
  end)
  it("sets planning and properties in a buffer", function()
    local buf = org_buffer({ "* TODO Task", "body" }, { 1, 0 })
    edit.set_planning(buf, 1, "scheduled", date.parse("<2026-09-23 Wed>"))
    eq("SCHEDULED: <2026-09-23 Wed>", buf_lines(buf)[2])
    edit.set_planning(buf, 1, "deadline", date.parse("<2026-09-25 Fri>"))
    eq("DEADLINE: <2026-09-25 Fri> SCHEDULED: <2026-09-23 Wed>", buf_lines(buf)[2])
    edit.set_property(buf, 1, "ID", "x1")
    eq({ "* TODO Task", "DEADLINE: <2026-09-25 Fri> SCHEDULED: <2026-09-23 Wed>", ":PROPERTIES:", ":ID: x1", ":END:", "body" }, buf_lines(buf))
    edit.add_log_entry(buf, 1, { "- Note" })
    eq(":LOGBOOK:", buf_lines(buf)[6])
    edit.set_property(buf, 1, "ID", nil)
    eq(":LOGBOOK:", buf_lines(buf)[3])
    edit.set_planning(buf, 1, "scheduled", nil)
    edit.set_planning(buf, 1, "deadline", nil)
    eq(":LOGBOOK:", buf_lines(buf)[2])
  end)
end)
