-- Dot-repeat (.) of org editing keys: a repeatable action registers itself
-- with Vim's redo, so "." runs it again at the cursor, with the same count
-- or a new one.
local function keys(k)
  vim.api.nvim_feedkeys(vim.keycode(k), "xt", false)
end

describe("dot-repeat", function()
  with_config({ todo_keywords = { "TODO NEXT | DONE" } })

  it("repeats a heading demotion on the next heading", function()
    local buf = org_buffer({ "* A", "** B", "** C" }, { 2, 0 })
    keys(">>")
    keys("j.")
    eq({ "* A", "*** B", "*** C" }, buf_lines(buf))
  end)

  it("repeats a TODO cycle and keeps the undo steps apart", function()
    local buf = org_buffer({ "* A", "* B", "* C" }, { 1, 0 })
    keys("cit")
    keys("j.")
    keys("j.")
    eq({ "* TODO A", "* TODO B", "* TODO C" }, buf_lines(buf))
    keys("u")
    eq({ "* TODO A", "* TODO B", "* C" }, buf_lines(buf))
  end)

  it("repeats with the original count, or the count given to .", function()
    local buf = org_buffer({ "* A", "* B", "* C", "* D" }, { 1, 0 })
    keys("2>>")
    keys("j.")
    keys("j3.")
    eq({ "*** A", "*** B", "**** C", "* D" }, buf_lines(buf))
  end)

  it("repeats a checkbox toggle", function()
    local buf = org_buffer({ "* H", "- [ ] a", "- [ ] b" }, { 2, 0 })
    keys("<C-Space>")
    keys("j.")
    eq({ "* H", "- [X] a", "- [X] b" }, buf_lines(buf))
  end)

  it("repeats moving a subtree down", function()
    local buf = org_buffer({ "* A", "* B", "* C" }, { 1, 0 })
    keys("<M-j>")
    keys(".")
    eq({ "* B", "* C", "* A" }, buf_lines(buf))
  end)

  it("works on folded subtrees and keeps the cursor where it was", function()
    local buf = org_buffer({ "* A", "text a", "* B", "text b" }, { 1, 2 })
    vim.cmd("normal! zMgg")
    vim.api.nvim_win_set_cursor(0, { 1, 2 })
    keys(">>")
    eq({ 1, 2 }, { vim.api.nvim_win_get_cursor(0)[1], vim.api.nvim_win_get_cursor(0)[2] - 1 })
    vim.api.nvim_win_set_cursor(0, { 3, 0 })
    keys(".")
    eq({ "** A", "text a", "** B", "text b" }, buf_lines(buf))
    eq(1, vim.fn.foldclosed(1))
  end)

  it("leaves . to Vim when the key fell back to its default", function()
    local buf = org_buffer({ "text", "more" }, { 1, 0 })
    vim.bo[buf].shiftwidth = 2
    keys(">>")
    keys("j.")
    eq({ "  text", "  more" }, buf_lines(buf))
  end)

  it("does not register actions that are not repeatable", function()
    local buf = org_buffer({ "* A", "** B", "* C" }, { 2, 0 })
    keys(">>")
    -- cycling visibility is not an edit: . still repeats the demotion
    keys("<Tab>")
    keys("j.")
    eq({ "* A", "*** B", "** C" }, buf_lines(buf))
  end)

  it("native change after an org key takes over .", function()
    local buf = org_buffer({ "* A", "* B", "xyz" }, { 1, 0 })
    keys("cit")
    keys("3G0x")
    keys(".")
    eq({ "* TODO A", "* B", "z" }, buf_lines(buf))
  end)
  it("org key after a native change takes over .", function()
    local buf = org_buffer({ "* A", "* B", "xyz" }, { 3, 0 })
    keys("x")
    keys("ggcit")
    keys("j.")
    eq({ "* TODO A", "* TODO B", "yz" }, buf_lines(buf))
  end)
  it("undo and redo of a repeat", function()
    local buf = org_buffer({ "* A", "* B" }, { 1, 0 })
    keys("cit")
    keys("j.")
    keys("u")
    eq({ "* TODO A", "* B" }, buf_lines(buf))
    keys("<C-r>")
    eq({ "* TODO A", "* TODO B" }, buf_lines(buf))
    keys("uu")
    eq({ "* A", "* B" }, buf_lines(buf))
  end)
  it(". inside a macro", function()
    local buf = org_buffer({ "* A", "* B", "* C", "* D" }, { 1, 0 })
    keys("cit")
    keys("qqj.q")
    keys("@q@@")
    eq({ "* TODO A", "* TODO B", "* TODO C", "* TODO D" }, buf_lines(buf))
  end)
  it("Visual-mode keys don't register", function()
    local buf = org_buffer({ "* A", "* B", "- [ ] x", "- [ ] y", "abc" }, { 1, 0 })
    keys("cit")
    keys("3GVj<C-Space><Esc>")
    eq({ "- [X] x", "- [X] y" }, vim.list_slice(buf_lines(buf), 3, 4))
    keys("2G.")
    eq("* TODO B", buf_lines(buf)[2])
  end)
  it(":Org commands don't register", function()
    local buf = org_buffer({ "* A", "* B", "* C" }, { 1, 0 })
    keys("cit")
    vim.cmd("Org demote_heading")
    keys("j.")
    eq({ "** TODO A", "* TODO B", "* C" }, buf_lines(buf))
  end)
  it("a count on . replaces the count, then sticks", function()
    local buf = org_buffer({ "* A", "* B", "* C", "* D" }, { 1, 0 })
    keys(">>")
    keys("j2.")
    keys("j.")
    keys("j1.")
    eq({ "** A", "*** B", "*** C", "** D" }, buf_lines(buf))
  end)
  it(". in another org buffer repeats there", function()
    local b1 = org_buffer({ "* A" }, { 1, 0 })
    keys("cit")
    eq({ "* TODO A" }, buf_lines(b1))
    local b2 = org_buffer({ "* X" }, { 1, 0 })
    keys(".")
    eq({ "* TODO X" }, buf_lines(b2))
  end)
  it(". in a non-org buffer falls back to the key there", function()
    org_buffer({ "* A", "* B" }, { 2, 0 })
    keys(">>")
    vim.cmd("enew!")
    vim.bo.shiftwidth = 2
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "plain" })
    keys(".")
    eq({ "  plain" }, vim.api.nvim_buf_get_lines(0, 0, -1, false))
  end)
  it(". on a line where the action doesn't apply runs the key's default", function()
    local buf = org_buffer({ "* A", "text" }, { 1, 0 })
    vim.bo[buf].shiftwidth = 2
    keys(">>")
    keys("j.")
    eq({ "** A", "  text" }, buf_lines(buf))
  end)
  it("cursor in a closed fold: same line as pressing the key", function()
    local buf = org_buffer({ "* H", "- one", "- two", "- three" }, { 2, 0 })
    keys("<S-Right>")
    keys("jzc")
    keys(".")
    eq({ "* H", "1. one", "2. two", "3. three" }, buf_lines(buf))
    eq(3, vim.api.nvim_win_get_cursor(0)[1])
  end)
  it("registration inside a closed fold keeps the cursor", function()
    org_buffer({ "* H", "- one", "- two" }, { 3, 0 })
    keys("zc")
    keys("<S-Right>")
    eq(3, vim.api.nvim_win_get_cursor(0)[1])
  end)
end)

-- A count on a key whose Emacs command takes none repeats the edit, as
-- one undo step; "." keeps the count.
describe("counts on editing keys", function()
  it("3>> indents a list item three levels, one undo step", function()
    local lines = { "- a", "  - b", "    - c", "- d" }
    local buf = org_buffer(lines, { 4, 0 })
    keys("3>>")
    eq({ "- a", "  - b", "    - c", "      - d" }, buf_lines(buf))
    keys("u")
    eq(lines, buf_lines(buf))
  end)

  it("a count past what can be done stops there", function()
    local buf = org_buffer({ "- a", "  - b" }, { 2, 0 })
    keys("5<<")
    eq({ "- a", "- b" }, buf_lines(buf))
  end)

  it("2<M-L> indents an item with its children twice", function()
    local buf = org_buffer({ "- a", "  - b", "- c", "  - c1" }, { 3, 0 })
    keys("2<M-L>")
    eq({ "- a", "  - b", "    - c", "      - c1" }, buf_lines(buf))
  end)

  it("2<M-j> moves a list item, a table row and an element twice", function()
    local buf = org_buffer({ "- a", "- b", "- c", "- d" }, { 1, 0 })
    keys("2<M-j>")
    eq({ "- b", "- c", "- a", "- d" }, buf_lines(buf))
    eq(3, vim.api.nvim_win_get_cursor(0)[1])
    keys("u")
    eq({ "- a", "- b", "- c", "- d" }, buf_lines(buf))
    buf = org_buffer({ "| 1 |", "| 2 |", "| 3 |", "| 4 |" }, { 1, 2 })
    keys("2<M-j>")
    eq({ "| 2 |", "| 3 |", "| 1 |", "| 4 |" }, buf_lines(buf))
    buf = org_buffer({ "* H", "one", "", "two", "", "three" }, { 2, 0 })
    keys("2<M-j>")
    eq({ "* H", "two", "", "three", "", "one" }, buf_lines(buf))
  end)

  it("2<M-l> moves a table column right twice", function()
    local buf = org_buffer({ "| a | b | c |" }, { 1, 2 })
    keys("2<M-l>")
    eq({ "| b | c | a |" }, buf_lines(buf))
    keys("u")
    eq({ "| a | b | c |" }, buf_lines(buf))
  end)

  it(". keeps the count of a list indent", function()
    local buf = org_buffer({ "- a", "  - b", "- c", "- d", "  - e", "- f" }, { 3, 0 })
    keys("2>>")
    eq({ "- a", "  - b", "    - c", "- d", "  - e", "- f" }, buf_lines(buf))
    vim.api.nvim_win_set_cursor(0, { 6, 0 })
    keys(".")
    eq({ "- a", "  - b", "    - c", "- d", "  - e", "    - f" }, buf_lines(buf))
  end)
end)
