-- Emacs Org keys (mappings.emacs / emacs_insert / emacs_global).
local config = require("org.config")

local function keys(k)
  vim.api.nvim_feedkeys(vim.keycode(k), "xt", false)
end

local function has_map(mode, lhs)
  return vim.fn.maparg(lhs, mode, false, true).desc ~= nil
end

describe("emacs keys", function()
  it("maps the org-mode-map keys buffer-locally", function()
    org_buffer({ "* Task" }, { 1, 0 })
    for _, lhs in ipairs({ "<C-c><C-t>", "<C-c><C-s>", "<C-c><C-d>", "<C-c><C-q>", "<C-c><C-w>", "<C-c><C-x><C-i>" }) do
      ok(has_map("n", lhs), lhs)
    end
    ok(has_map("i", "<C-CR>"), "insert <C-CR>")
    ok(has_map("n", "<C-c>a"), "global <C-c>a")
  end)
  it("<C-CR> inserts a heading after the subtree", function()
    local buf = org_buffer({ "* A", "** child", "body", "* B" }, { 1, 0 })
    keys("<C-CR>")
    vim.cmd("stopinsert")
    eq({ "* A", "** child", "body", "* ", "* B" }, buf_lines(buf))
  end)
  it("<C-CR> works in insert mode", function()
    local buf = org_buffer({ "* A" }, { 1, 0 })
    keys("A text<C-CR>")
    vim.cmd("stopinsert")
    eq({ "* A text", "* " }, buf_lines(buf))
  end)
  it("<C-S-CR> inserts a TODO heading", function()
    local buf = org_buffer({ "* A" }, { 1, 0 })
    keys("<C-S-CR>")
    vim.cmd("stopinsert")
    eq("* TODO ", buf_lines(buf)[2])
  end)
  it("<C-c>- inserts a table hline, cycles a bullet, or makes an item", function()
    local buf = org_buffer({ "| a | b |", "| c | d |" }, { 1, 2 })
    keys("<C-c>-")
    eq("|---+---|", buf_lines(buf)[2])
    buf = org_buffer({ "- item" }, { 1, 0 })
    keys("<C-c>-")
    eq("+ item", buf_lines(buf)[1])
    buf = org_buffer({ "text" }, { 1, 0 })
    keys("<C-c>-")
    eq("- text", buf_lines(buf)[1])
  end)
  it("<C-c>* toggles a heading outside tables", function()
    local buf = org_buffer({ "text" }, { 1, 0 })
    keys("<C-c>*")
    eq("* text", buf_lines(buf)[1])
  end)
  it("<C-S-Right> switches TODO keyword sets", function()
    local buf = org_buffer({ "#+TODO: TODO | DONE", "#+TODO: BUG | FIXED", "* TODO Task" }, { 3, 0 })
    keys("<C-S-Right>")
    eq("* BUG Task", buf_lines(buf)[3])
  end)
  it("<C-c><C-t> cycles when the keywords have no fast keys", function()
    local buf = org_buffer({ "#+TODO: TODO | DONE", "* Task" }, { 2, 0 })
    keys("<C-c><C-t>")
    eq("* TODO Task", buf_lines(buf)[2])
    keys("<C-c><C-t>")
    ok(buf_lines(buf)[2]:match("^%* DONE Task"))
  end)
  it("<C-c><CR> adds an hline and moves to a new row in a table", function()
    local buf = org_buffer({ "| a | b |" }, { 1, 2 })
    keys("<C-c><CR>")
    eq({ "| a | b |", "|---+---|", "|   |   |" }, buf_lines(buf))
    eq(3, vim.fn.line("."))
  end)
  it("<C-c><C-x><C-w> / <C-y> cut and paste a subtree outside tables", function()
    local buf = org_buffer({ "* A", "* B", "body" }, { 2, 0 })
    keys("<C-c><C-x><C-w>")
    eq({ "* A" }, buf_lines(buf))
    -- org-paste-subtree: at the start of a headline, before it
    keys("<C-c><C-x><C-y>")
    eq({ "* B", "body", "* A" }, buf_lines(buf))
    -- elsewhere, before the next visible headline (here the end)
    vim.api.nvim_win_set_cursor(0, { 3, 2 })
    keys("<C-c><C-x><C-y>")
    eq({ "* B", "body", "* A", "* B", "body" }, buf_lines(buf))
  end)
  it("<C-c><C-x>o toggles the ORDERED property", function()
    local buf = org_buffer({ "* Project" }, { 1, 0 })
    keys("<C-c><C-x>o")
    ok(table.concat(buf_lines(buf), "\n"):match(":ORDERED:%s+t"))
  end)
  it("can be disabled with mappings.emacs = false", function()
    local opts = vim.deepcopy(config.opts)
    require("org").setup(vim.tbl_deep_extend("force", opts, { mappings = { emacs = false } }))
    org_buffer({ "* Task" }, { 1, 0 })
    ok(not has_map("n", "<C-c><C-t>"), "no <C-c><C-t>")
    ok(has_map("n", "<C-c><C-c>"), "<C-c><C-c> is not an emacs-only key")
    require("org").setup(opts)
  end)
  -- #228: which-key showed C-c C-x as a bare "+N keymaps" past the end of its popup
  it('labels the C-c C-x, C-c C-v and C-c " groups for which-key', function()
    local function groups(overrides)
      local added = {}
      package.loaded["which-key"] = {
        add = function(spec)
          vim.list_extend(added, spec)
        end,
      }
      local opts = vim.deepcopy(config.opts)
      require("org").setup(vim.tbl_deep_extend("force", opts, overrides))
      package.loaded["which-key"] = nil
      require("org").setup(opts)
      local labels = {}
      for _, g in ipairs(added) do
        labels[g[1]] = g.group
      end
      return labels
    end
    local labels = groups({})
    ok(labels["<C-C><C-X>"]:match("^org C%-x"), "C-c C-x")
    eq("org babel (C-v)", labels["<C-C><C-V>"])
    eq("org plot", labels['<C-C>"'])
    labels = groups({ mappings = { emacs = false } })
    eq(nil, labels["<C-C><C-X>"])
    eq("narrow", labels[config.lhs_list("<prefix>n")[1]])
  end)
  it("<C-c><C-x><C-f> names a special key it doesn't take", function()
    local buf = org_buffer({ "word" }, { 1, 0 })
    local utils = require("org.utils")
    local getchar, warn, msg = utils.getchar, utils.warn, nil
    utils.getchar = function()
      return vim.keycode("<F2>")
    end
    utils.warn = function(m)
      msg = m
    end
    keys("<C-c><C-x><C-f>")
    utils.getchar, utils.warn = getchar, warn
    eq('No such emphasis marker: "<F2>"', msg)
    eq({ "word" }, buf_lines(buf))
  end)
end)
