-- Emacs Org keys (mappings.emacs / emacs_insert / emacs_global).
local config = require("org.config")

local function keys(k)
  vim.api.nvim_feedkeys(vim.keycode(k), "xt", false)
end

local function has_map(mode, lhs)
  return vim.fn.maparg(lhs, mode, false, true).desc ~= nil
end

describe("emacs keys", function()
  it("maps the org-mode-map keys buffer-locally", function()
    org_buffer({ "* Task" }, { 1, 0 })
    for _, lhs in ipairs({ "<C-c><C-t>", "<C-c><C-s>", "<C-c><C-d>", "<C-c><C-q>", "<C-c><C-w>", "<C-c><C-x><C-i>" }) do
      ok(has_map("n", lhs), lhs)
    end
    ok(has_map("i", "<C-CR>"), "insert <C-CR>")
    ok(has_map("n", "<C-c>a"), "global <C-c>a")
  end)
  it("<C-CR> inserts a heading after the subtree", function()
    local buf = org_buffer({ "* A", "** child", "body", "* B" }, { 1, 0 })
    keys("<C-CR>")
    vim.cmd("stopinsert")
    eq({ "* A", "** child", "body", "* ", "* B" }, buf_lines(buf))
  end)
  it("<C-CR> works in insert mode", function()
    local buf = org_buffer({ "* A" }, { 1, 0 })
    keys("A text<C-CR>")
    vim.cmd("stopinsert")
    eq({ "* A text", "* " }, buf_lines(buf))
  end)
  it("<C-S-CR> inserts a TODO heading", function()
    local buf = org_buffer({ "* A" }, { 1, 0 })
    keys("<C-S-CR>")
    vim.cmd("stopinsert")
    eq("* TODO ", buf_lines(buf)[2])
  end)
  it("<C-c>- inserts a table hline, cycles a bullet, or makes an item", function()
    local buf = org_buffer({ "| a | b |", "| c | d |" }, { 1, 2 })
    keys("<C-c>-")
    eq("|---+---|", buf_lines(buf)[2])
    buf = org_buffer({ "- item" }, { 1, 0 })
    keys("<C-c>-")
    eq("+ item", buf_lines(buf)[1])
    buf = org_buffer({ "text" }, { 1, 0 })
    keys("<C-c>-")
    eq("- text", buf_lines(buf)[1])
  end)
  it("<C-c>* toggles a heading outside tables", function()
    local buf = org_buffer({ "text" }, { 1, 0 })
    keys("<C-c>*")
    eq("* text", buf_lines(buf)[1])
  end)
  it("<C-S-Right> switches TODO keyword sets", function()
    local buf = org_buffer({ "#+TODO: TODO | DONE", "#+TODO: BUG | FIXED", "* TODO Task" }, { 3, 0 })
    keys("<C-S-Right>")
    eq("* BUG Task", buf_lines(buf)[3])
  end)
  it("<C-c><C-t> cycles when the keywords have no fast keys", function()
    local buf = org_buffer({ "#+TODO: TODO | DONE", "* Task" }, { 2, 0 })
    keys("<C-c><C-t>")
    eq("* TODO Task", buf_lines(buf)[2])
    keys("<C-c><C-t>")
    ok(buf_lines(buf)[2]:match("^%* DONE Task"))
  end)
  it("<C-c><CR> adds an hline and moves to a new row in a table", function()
    local buf = org_buffer({ "| a | b |" }, { 1, 2 })
    keys("<C-c><CR>")
    eq({ "| a | b |", "|---+---|", "|   |   |" }, buf_lines(buf))
    eq(3, vim.fn.line("."))
  end)
  it("<C-c><C-x><C-w> / <C-y> cut and paste a subtree outside tables", function()
    local buf = org_buffer({ "* A", "* B", "body" }, { 2, 0 })
    keys("<C-c><C-x><C-w>")
    eq({ "* A" }, buf_lines(buf))
    keys("<C-c><C-x><C-y>")
    eq({ "* A", "* B", "body" }, buf_lines(buf))
  end)
  it("<C-c><C-x>o toggles the ORDERED property", function()
    local buf = org_buffer({ "* Project" }, { 1, 0 })
    keys("<C-c><C-x>o")
    ok(table.concat(buf_lines(buf), "\n"):match(":ORDERED:%s+t"))
  end)
  it("can be disabled with mappings.emacs = false", function()
    local opts = vim.deepcopy(config.opts)
    require("org").setup(vim.tbl_deep_extend("force", opts, { mappings = { emacs = false } }))
    org_buffer({ "* Task" }, { 1, 0 })
    ok(not has_map("n", "<C-c><C-t>"), "no <C-c><C-t>")
    ok(has_map("n", "<C-c><C-c>"), "<C-c><C-c> is not an emacs-only key")
    require("org").setup(opts)
  end)
end)
