local export = require("org.export")
local ox = require("org.export.ox")
local element = require("org.export.element")
local config = require("org.config")
local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")
local sample = root .. "/fixtures/export/sample.org"
local lines = vim.fn.readfile(sample)

local function has(s, sub)
  ok(s:find(sub, 1, true), "missing: " .. sub .. "\n---\n" .. s)
end
local function hasnt(s, sub)
  ok(not s:find(sub, 1, true), "unexpected: " .. sub .. "\n---\n" .. s)
end

local function body(fmt, l, opts)
  opts = opts or {}
  return export.to_string(fmt, vim.tbl_extend("force", { lines = l, body_only = true }, opts))
end

describe("export", function()
  before_each(function()
    config.opts.babel.evaluate_on_export = false
  end)

  describe("element parser", function()
    it("parses objects like org-element", function()
      local nodes = element.parse_secondary("a *b* /c/ =d= [[x][y]] [fn:1] <2026-01-01 Thu> \\alpha $x$", "paragraph")
      local types = {}
      for _, n in ipairs(nodes) do
        if n.type ~= "plain-text" then
          types[#types + 1] = n.type
        end
      end
      eq({ "bold", "italic", "verbatim", "link", "footnote-reference", "timestamp", "entity", "latex-fragment" }, types)
    end)
    it("does not treat mid-word markers as emphasis", function()
      local nodes = element.parse_secondary("a*b*c 2*3*4", "paragraph")
      eq(1, #nodes)
    end)
    it("keeps blank lines as post-blank", function()
      local d = element.parse({ "para", "", "", "- item" }, {})
      local sec = d.contents[1]
      eq("paragraph", sec.contents[1].type)
      eq(2, sec.contents[1].post_blank)
      eq("plain-list", sec.contents[2].type)
    end)
  end)

  describe("html", function()
    local html = export.to_string("html", { lines = lines, filename = sample })
    it("has the xhtml-strict document structure", function()
      has(html, '<?xml version="1.0" encoding="utf-8"?>')
      has(html, '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"')
      has(html, '<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">')
      has(html, '<h1 class="title">Sample Document</h1>')
      has(html, 'id="table-of-contents"')
      has(html, '<span class="section-number-2">1.</span>')
      has(html, '<div id="postamble" class="status">')
      has(html, '<p class="author">Author: Jane Doe</p>')
      has(html, '<p class="date">Date: 2026-09-23</p>')
      has(html, '<meta name="generator" content="Org Mode" />')
    end)
    it("renders inline markup", function()
      has(html, "<b>bold</b>")
      has(html, "<i>italic</i>")
      has(html, "<del>strike</del>")
      has(html, "<code>verb</code>")
      has(html, '<a href="https://orgmode.org">Org</a>')
      has(html, '<a href="https://neovim.io">https://neovim.io</a>')
      has(html, "Hello, World!")
      has(html, "&alpha;")
      has(html, "H<sub>2O</sub>")
      has(html, "&ndash;")
      has(html, "&hellip;")
      has(html, "\\(a^2 + b^2\\)")
    end)
    it("renders structures", function()
      has(html, '<span class="todo TODO">TODO</span>')
      has(html, '<li class="on"><code>[X]</code> item two')
      has(html, '<ol class="org-ol">')
      has(html, "<dt>term</dt><dd>description</dd>")
      has(html, "<thead>")
      has(html, '<td class="org-right">22</td>')
      has(html, '<caption class="t-above"><span class="table-number">Table 1:</span> Numbers</caption>')
      has(html, 'class="src src-python"')
      has(html, "<blockquote>")
      has(html, '<a href="#first">the first</a>')
      has(html, "<hr />")
      has(html, '<pre class="example">\nfixed width\n</pre>')
      has(html, '<div id="footnotes">')
      has(html, "The footnote text.")
      has(html, "Deep heading")
      has(html, "MathJax")
    end)
    it("excludes noexport and COMMENT subtrees", function()
      hasnt(html, "secret")
      hasnt(html, "hidden comment")
      hasnt(html, "SCHEDULED")
    end)
  end)

  describe("markdown (ox-md)", function()
    local md = body("md", lines, { filename = sample })
    it("writes Emacs ox-md markdown", function()
      has(md, "# TODO First section")
      has(md, "**bold**")
      has(md, "*italic*")
      has(md, "`verb`")
      has(md, "[Org](https://orgmode.org)")
      has(md, "-   [X] item two")
      has(md, "<table ")
      has(md, '    print("hi")')
      has(md, "> Quoted **text**.")
      has(md, '<sup><a id="fn.1" href="#fnr.1">1</a></sup> The footnote text.')
      hasnt(md, "secret")
    end)
  end)

  describe("gfm", function()
    local md = export.to_string("gfm", { lines = lines, filename = sample })
    it("writes GitHub flavoured markdown", function()
      has(md, "# Sample Document")
      has(md, "## TODO First section")
      has(md, "- [x] item two")
      has(md, "- [ ] item three")
      has(md, "| Name | Qty |")
      has(md, "|---|---|")
      has(md, "```python")
      has(md, "> Quoted **text**.")
      has(md, "[^1]: The footnote text.")
      has(md, "[the first](#first)")
      hasnt(md, "secret")
    end)
  end)

  describe("latex", function()
    local tex = export.to_string("latex", { lines = lines, filename = sample })
    it("renders latex like ox-latex", function()
      has(tex, "\\documentclass[11pt]{article}")
      has(tex, "\\section{{\\bfseries\\sffamily TODO} First section")
      has(tex, "\\textbf{bold}")
      has(tex, "\\begin{itemize}")
      has(tex, "\\begin{tabular}{lr}")
      has(tex, "\\caption{Numbers}")
      has(tex, "\\footnote{The footnote text.}")
      has(tex, "\\begin{verbatim}")
      has(tex, "\\hypersetup{")
      has(tex, " pdfauthor={Jane Doe},")
      has(tex, "\\label{sec:org")
    end)
  end)

  describe("files", function()
    it("writes html next to the source and exports a subtree", function()
      local dir = vim.fn.tempname()
      vim.fn.mkdir(dir, "p")
      local buf = org_buffer(lines)
      vim.api.nvim_buf_set_name(buf, dir .. "/doc.org")
      local out = export.export("html", { bufnr = buf })
      eq(vim.uv.fs_realpath(dir) .. "/doc.html", vim.uv.fs_realpath(out))
      ok(vim.fn.filereadable(out) == 1)
      local sub_line
      for i, l in ipairs(lines) do
        if l == "* Second section" then
          sub_line = i
        end
      end
      -- the link to #first points outside the subtree: mark it like Emacs
      local md = export.to_string("gfm", { lines = lines, subtree_line = sub_line, ext = { with_broken_links = "mark" } })
      has(md, "# Second section")
      hasnt(md, "First section")
      local md_body = export.to_string("gfm", { lines = lines, body_only = true })
      hasnt(md_body, "# Sample Document")
      vim.bo[buf].modified = false
    end)
    it("uses EXPORT_FILE_NAME for the output file", function()
      local dir = vim.fn.tempname()
      vim.fn.mkdir(dir, "p")
      local buf = org_buffer({ "#+EXPORT_FILE_NAME: other", "text" })
      vim.api.nvim_buf_set_name(buf, dir .. "/doc.org")
      local out = export.export("gfm", { bufnr = buf })
      eq("other.md", vim.fn.fnamemodify(out, ":t"))
      vim.bo[buf].modified = false
    end)
  end)

  describe("pandoc", function()
    it("exports docx and rst via pandoc when available", function()
      if vim.fn.executable("pandoc") == 0 then
        return
      end
      local dir = vim.fn.tempname()
      vim.fn.mkdir(dir, "p")
      local buf = org_buffer({ "#+TITLE: P", "* Head", "text", "* Hidden :noexport:", "zzz" })
      vim.api.nvim_buf_set_name(buf, dir .. "/p.org")
      local out = export.export("docx", { bufnr = buf })
      ok(out and vim.fn.filereadable(out) == 1)
      local rst = export.export("rst", { bufnr = buf })
      local content = table.concat(vim.fn.readfile(rst), "\n")
      has(content, "Head")
      hasnt(content, "zzz")
      vim.bo[buf].modified = false
    end)
  end)

  describe("link abbreviations", function()
    it("expands function abbreviations", function()
      config.opts.links.abbreviations = {
        gh = function(tag)
          return "https://github.com/" .. tag
        end,
      }
      local h = body("html", { "See [[gh:neovim/neovim][nvim]]." })
      has(h, '<a href="https://github.com/neovim/neovim">nvim</a>')
      config.opts.links.abbreviations = {}
    end)
  end)

  describe("engine", function()
    it("reads #+OPTIONS values like the Elisp reader", function()
      local o = ox.parse_option_line('toc:nil H:2 d:(not "LOGBOOK") tasks:("TODO" "NEXT") ^:{} ::nil')
      eq(false, o.toc)
      eq(2, o.H)
      eq({ "LOGBOOK", negate = true }, o.d)
      eq({ "TODO", "NEXT" }, o.tasks)
      eq("{}", o["^"])
      eq(false, o[":"])
    end)
  end)
end)
