local export = require("org.export")
local ast = require("org.export.ast")
local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")
local sample = root .. "/fixtures/export/sample.org"
local lines = vim.fn.readfile(sample)

local function has(s, sub)
  ok(s:find(sub, 1, true), "missing: " .. sub .. "\n---\n" .. s)
end
local function hasnt(s, sub)
  ok(not s:find(sub, 1, true), "unexpected: " .. sub)
end

describe("export ast", function()
  it("parses inline markup", function()
    local nodes = ast.parse_inline("a *b* /c/ =d= [[x][y]] [fn:1] <2026-01-01 Thu> \\alpha $x$", {})
    local types = {}
    for _, n in ipairs(nodes) do
      if n.type ~= "text" then
        types[#types + 1] = n.type
      end
    end
    eq({ "bold", "italic", "verbatim", "link", "footnote_ref", "timestamp", "entity", "latex" }, types)
  end)
  it("does not treat mid-word markers as emphasis", function()
    local nodes = ast.parse_inline("a*b*c 2*3*4", {})
    eq(1, #nodes)
  end)
  it("builds a document", function()
    local doc = ast.parse(lines, { filename = sample })
    eq("Sample Document", doc.title)
    eq("Jane Doe", doc.author)
    eq(2, #doc.children - 1) -- preamble paragraph + 2 headlines
    eq({ 1 }, doc.children[2].number)
    eq("first", doc.children[2].id)
  end)
end)

describe("export html", function()
  local html = export.to_string("html", { lines = lines, filename = sample })
  it("has document structure", function()
    has(html, "<!DOCTYPE html>")
    has(html, '<h1 class="title">Sample Document</h1>')
    has(html, 'id="table-of-contents"')
    has(html, '<span class="section-number-2">1</span>')
  end)
  it("renders inline markup", function()
    has(html, "<b>bold</b>")
    has(html, "<i>italic</i>")
    has(html, "<del>strike</del>")
    has(html, "<code>verb</code>")
    has(html, '<a href="https://orgmode.org">Org</a>')
    has(html, '<a href="https://neovim.io">https://neovim.io</a>')
    has(html, "Hello, World!")
    has(html, "&alpha;")
    has(html, "H<sub>2O</sub>")
    has(html, "&#x2013;")
    has(html, "&#x2026;")
  end)
  it("renders structures", function()
    has(html, '<span class="todo TODO">TODO</span>')
    has(html, "<code>[X]</code>")
    has(html, '<ol class="org-ol">')
    has(html, "<dt>")
    has(html, "<thead>")
    has(html, '<td class="org-right">22</td>')
    has(html, "<caption")
    has(html, 'class="src src-python"')
    has(html, "hi</pre>")
    has(html, "<blockquote>")
    has(html, '<a href="#first">the first</a>')
    has(html, "<hr />")
    has(html, 'class="example">fixed width')
    has(html, 'id="footnotes"')
    has(html, "The footnote text.")
    has(html, "Deep heading")
    has(html, "MathJax")
  end)
  it("excludes noexport, COMMENT, and results of code-only blocks", function()
    hasnt(html, "secret")
    hasnt(html, "hidden comment")
    hasnt(html, "should-not-appear")
    hasnt(html, "SCHEDULED")
  end)
end)

describe("export markdown", function()
  local md = export.to_string("md", { lines = lines, filename = sample })
  it("renders gfm", function()
    has(md, "# Sample Document")
    has(md, "## TODO First section")
    has(md, "**bold**")
    has(md, "*italic*")
    has(md, "~~strike~~")
    has(md, "`verb`")
    has(md, "[Org](https://orgmode.org)")
    has(md, "- [x] item two")
    has(md, "- [ ] item three")
    has(md, "| Name | Qty |")
    has(md, "|---|---|")
    has(md, "```python")
    has(md, "> Quoted **text**.")
    has(md, "[^1]: The footnote text.")
    has(md, "[the first](#first)")
    hasnt(md, "secret")
  end)
end)

describe("export text", function()
  local txt = export.to_string("txt", { lines = lines, filename = sample })
  it("renders utf-8 text", function()
    has(txt, "Sample Document")
    has(txt, "1 TODO First section  :work:")
    has(txt, "═══")
    has(txt, "☑ item two")
    has(txt, "│ Name │ Qty │")
    has(txt, "[1] The footnote text.")
    hasnt(txt, "secret")
  end)
end)

describe("export latex", function()
  local tex = export.to_string("latex", { lines = lines, filename = sample })
  it("renders latex", function()
    has(tex, "\\documentclass")
    has(tex, "\\section{\\textbf{TODO} First section")
    has(tex, "\\textbf{bold}")
    has(tex, "\\begin{itemize}")
    has(tex, "\\begin{tabular}{ll}")
    has(tex, "\\footnote{The footnote text.}")
    has(tex, "\\begin{verbatim}")
  end)
end)

describe("export files", function()
  it("writes html next to the source and subtree export", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, "p")
    local buf = org_buffer(lines)
    vim.api.nvim_buf_set_name(buf, dir .. "/doc.org")
    local out = export.export("html", { bufnr = buf })
    eq(vim.uv.fs_realpath(dir) .. "/doc.html", vim.uv.fs_realpath(out))
    ok(vim.fn.filereadable(out) == 1)
    -- subtree export: second section
    local sub_line
    for i, l in ipairs(lines) do
      if l == "* Second section" then
        sub_line = i
      end
    end
    local md = export.to_string("md", { lines = lines, subtree_line = sub_line })
    has(md, "# Second section")
    hasnt(md, "First section")
    local md_body = export.to_string("md", { lines = lines, body_only = true })
    hasnt(md_body, "# Sample Document")
    vim.bo[buf].modified = false
  end)
end)

describe("export pandoc", function()
  it("exports docx and rst via pandoc when available", function()
    if vim.fn.executable("pandoc") == 0 then
      return
    end
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, "p")
    local buf = org_buffer({ "#+TITLE: P", "* Head", "text", "* Hidden :noexport:", "zzz" })
    vim.api.nvim_buf_set_name(buf, dir .. "/p.org")
    local out = export.export("docx", { bufnr = buf })
    ok(out and vim.fn.filereadable(out) == 1)
    local rst = export.export("rst", { bufnr = buf })
    local content = table.concat(vim.fn.readfile(rst), "\n")
    has(content, "Head")
    hasnt(content, "zzz")
    vim.bo[buf].modified = false
  end)
end)

describe("export: link abbreviations", function()
  it("expands function abbreviations", function()
    local config = require("org.config")
    config.opts.links.abbreviations = {
      gh = function(tag)
        return "https://github.com/" .. tag
      end,
    }
    local _, target = ast.classify_link({ settings = { link_abbrevs = {} } }, "gh:neovim/neovim")
    eq("https://github.com/neovim/neovim", target)
    config.opts.links.abbreviations = {}
  end)
end)
