local views = require("org.extensions.views_util")

describe("views_util canvas", function()
  it("tracks byte offsets of highlighted segments", function()
    local cv = views.Canvas.new()
    cv:add({ { "◆ ", "A" }, { "done", "B" } })
    cv:put(" x")
    cv:add("plain")
    eq({ "◆ done x", "plain" }, cv:strings())
    eq({ { 0, 4, "A" }, { 4, 8, "B" } }, cv.lines[1].hls)
  end)

  it("draws into a buffer with layered highlights", function()
    local buf = vim.api.nvim_create_buf(false, true)
    local ns = vim.api.nvim_create_namespace("views_util_spec")
    local cv = views.Canvas.new()
    cv:add({ { "ab", { "Low", "High" } } })
    cv:draw(buf, ns)
    eq({ "ab" }, buf_lines(buf))
    eq(false, vim.bo[buf].modifiable)
    local marks = vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, { details = true })
    eq(2, #marks)
    ok(marks[2][4].priority > marks[1][4].priority)
    vim.api.nvim_buf_delete(buf, { force = true })
  end)
end)

describe("views_util sources", function()
  with_config({ todo_keywords = { "TODO NEXT | DONE" } })

  it("follows a subtree and filters its headlines", function()
    local buf = org_buffer({
      "* TODO Before",
      "* Parent :p:",
      "** TODO One :x:",
      "** NEXT Two",
      "* TODO After",
    }, { 2, 0 })
    local src = views.resolve_source("subtree")
    eq("subtree", src.kind)
    local function titles(hls)
      return vim.tbl_map(function(h)
        return h.title
      end, hls)
    end
    eq({ "Parent", "One", "Two" }, titles(views.collect(src)))
    vim.api.nvim_buf_set_lines(buf, 0, 0, false, { "* Inserted" })
    eq({ "Parent", "One", "Two" }, titles(views.collect(src)))
    eq({ "One" }, titles(views.collect(src, { tag = "x" })))
    -- inherited tags count
    eq({ "Parent", "One", "Two" }, titles(views.collect(src, { tag = "p" })))
    eq({ "Two" }, titles(views.collect(src, { filter = '(todo "NEXT")' })))
    eq({ "One" }, titles(views.collect(src, { filter = "x" })))
    eq({ "Two" }, titles(views.collect(src, { query = "todo:NEXT" })))
    local hls, err = views.collect(src, { filter = "(nosuch" })
    eq({}, hls)
    ok(err)
    ok(views.source_label(src):find("Parent", 1, true))
  end)

  it("refuses buffer sources outside org buffers", function()
    vim.cmd("enew!")
    local src, err = views.resolve_source("buffer")
    eq(nil, src)
    ok(err)
  end)

  it("finds a headline that moved", function()
    local buf = org_buffer({ "* TODO A", "* TODO B" })
    local ref = { bufnr = buf, lnum = 2, raw = "* TODO B" }
    eq({ bufnr = buf, lnum = 2 }, views.target(ref))
    vim.api.nvim_buf_set_lines(buf, 0, 0, false, { "* New" })
    eq({ bufnr = buf, lnum = 3 }, views.target(ref))
  end)
end)

describe("views_util formatting", function()
  it("formats durations and day offsets", function()
    eq("45m", views.short_duration(45))
    eq("2h", views.short_duration(120))
    eq("1h30m", views.short_duration(90))
    eq("160h", views.short_duration(160 * 60 + 12))
    eq("today", views.relative_days(0))
    eq("tomorrow", views.relative_days(1))
    eq("in 3d", views.relative_days(3))
    eq("2d ago", views.relative_days(-2))
  end)

  it("fits and centers text", function()
    eq("ab  ", views.fit("ab", 4))
    eq("abc…", views.fit("abcdef", 4))
    eq(" ab ", views.center("ab", 4))
  end)

  it("blends colours", function()
    eq("#000000", views.blend(0x000000, 0xffffff, 0))
    eq("#808080", views.blend(0x000000, 0xffffff, 0.5))
    eq("#ffffff", views.blend(0x000000, 0xffffff, 1))
  end)

  it("picks TODO, priority and tag faces", function()
    eq("OrgTodo", views.todo_group("TODO"))
    eq("OrgDone", views.todo_group("DONE"))
    eq("OrgPriorityA", views.priority_group("A"))
    eq("OrgPriority", views.priority_group("D"))
    eq("OrgTags", views.tag_group("x"))
  end)
end)
