local fn = require("org.footnotes")
vim.g.org_test = true

describe("footnotes", function()
  it("detects kinds", function()
    org_buffer({ "Text[fn:1] and [fn::inline] and [fn:x:named]", "[fn:1] Def" }, { 1, 6 })
    eq("reference", fn.at_point().kind)
    vim.api.nvim_win_set_cursor(0, { 1, 20 })
    eq("inline", fn.at_point().kind)
    vim.api.nvim_win_set_cursor(0, { 1, 36 })
    local f = fn.at_point()
    eq("inline", f.kind)
    eq("x", f.label)
    vim.api.nvim_win_set_cursor(0, { 2, 2 })
    eq("definition", fn.at_point().kind)
    vim.api.nvim_win_set_cursor(0, { 2, 8 })
    eq(nil, fn.at_point())
  end)
  it("jumps between reference and definition", function()
    org_buffer({ "Text[fn:a] more", "", "[fn:a] Def" }, { 1, 6 })
    fn.action_at_point()
    eq(3, vim.api.nvim_win_get_cursor(0)[1])
    fn.action_at_point()
    eq({ 1, 4 }, vim.api.nvim_win_get_cursor(0))
  end)
  it("creates a Footnotes section at the end of the file", function()
    org_buffer({ "Hello", "[fn:3] old" }, { 1, 4 })
    fn.new_footnote({ no_insert = true })
    eq({ "Hello[fn:4]", "[fn:3] old", "", "* Footnotes", "[fn:4] " }, buf_lines())
    eq(5, vim.api.nvim_win_get_cursor(0)[1])
  end)
  it("uses a Footnotes section", function()
    org_buffer({ "* A", "Hello", "* Footnotes", "[fn:1] x", "", "* After" }, { 2, 4 })
    fn.new_footnote({ no_insert = true })
    eq({ "* A", "Hello[fn:2]", "* Footnotes", "[fn:1] x", "", "[fn:2] ", "", "* After" }, buf_lines())
  end)
end)
