-- End-to-end: drive real buffer-local keymaps with feedkeys.
local function keys(k)
  vim.api.nvim_feedkeys(vim.keycode(k), "xt", false)
end

describe("keymaps e2e", function()
  it("cit cycles TODO keyword", function()
    local buf = org_buffer({ "* Task" }, { 1, 0 })
    keys("cit")
    eq("* TODO Task", buf_lines(buf)[1])
    keys("cit")
    eq("* NEXT Task", buf_lines(buf)[1])
  end)
  it(">> and << promote/demote headings", function()
    local buf = org_buffer({ "* A", "** B" }, { 2, 0 })
    keys(">>")
    eq("*** B", buf_lines(buf)[2])
    keys("<<")
    eq("** B", buf_lines(buf)[2])
  end)
  it(">> falls back to indent on plain text", function()
    local buf = org_buffer({ "text" }, { 1, 0 })
    vim.bo[buf].shiftwidth = 2
    keys(">>")
    eq("  text", buf_lines(buf)[1])
  end)
  it("<C-Space> toggles checkbox", function()
    local buf = org_buffer({ "* H", "- [ ] item" }, { 2, 0 })
    keys("<C-Space>")
    eq("- [X] item", buf_lines(buf)[2])
  end)
  it("<C-a> increments the date under the cursor", function()
    local buf = org_buffer({ "* H", "<2026-09-23 Wed>" }, { 2, 9 })
    keys("<C-a>")
    eq("<2026-09-24 Thu>", buf_lines(buf)[2])
  end)
  it("<C-a> still increments numbers elsewhere", function()
    local buf = org_buffer({ "x 5" }, { 1, 0 })
    keys("<C-a>")
    eq("x 6", buf_lines(buf)[1])
  end)
  it("<S-Down>/<S-Up> removing a priority does not scroll", function()
    local lines = { "* TODO [#C] Low", "* TODO [#A] High" }
    for i = 1, 200 do
      lines[#lines + 1] = "line " .. i
    end
    local buf = org_buffer(lines, { 1, 0 })
    keys("<S-Down>")
    eq("* TODO Low", buf_lines(buf)[1])
    eq(1, vim.api.nvim_win_get_cursor(0)[1])
    eq(1, vim.fn.line("w0"))
    vim.api.nvim_win_set_cursor(0, { 2, 0 })
    keys("<S-Up>")
    eq("* TODO High", buf_lines(buf)[2])
    eq(2, vim.api.nvim_win_get_cursor(0)[1])
    eq(1, vim.fn.line("w0"))
  end)
  it("<C-c><C-c> aligns a table", function()
    local buf = org_buffer({ "|a|bb|", "|-", "|ccc|d|" }, { 1, 1 })
    keys("<C-c><C-c>")
    eq({ "| a   | bb |", "|-----+----|", "| ccc | d  |" }, buf_lines(buf))
  end)
  it("<M-CR> on a list item adds an item", function()
    vim.g.org_test = true
    local buf = org_buffer({ "- one" }, { 1, 0 })
    keys("<M-CR>")
    vim.cmd("stopinsert")
    eq("- one", buf_lines(buf)[1])
    eq("- ", buf_lines(buf)[2])
  end)
  it("<Tab> cycles heading folds", function()
    org_buffer({ "* A", "text", "** B", "more" }, { 1, 0 })
    vim.cmd("normal! zX")
    keys("<Tab>")
    ok(vim.fn.foldclosed(2) == -1 or vim.fn.foldclosed(1) ~= -1)
  end)
end)

describe("alt+arrow keys", function()
  local function keys(k)
    vim.api.nvim_feedkeys(vim.keycode(k), "xt", false)
  end
  it("<M-Right>/<M-Left> demote and promote a heading", function()
    local buf = org_buffer({ "* A", "** B :tag:" }, { 2, 0 })
    keys("<M-Right>")
    eq("*** B", buf_lines(buf)[2]:sub(1, 5))
    keys("<M-Left>")
    keys("<M-Left>")
    eq("* B", buf_lines(buf)[2]:sub(1, 3))
    ok(buf_lines(buf)[2]:match(":tag:$"), "tags stay aligned")
  end)
  it("<M-Right> indents a list item", function()
    local buf = org_buffer({ "- one", "- two" }, { 2, 0 })
    keys("<M-Right>")
    eq("  - two", buf_lines(buf)[2])
  end)
  it("<M-Right> moves a table column", function()
    local buf = org_buffer({ "| a | b |" }, { 1, 2 })
    keys("<M-Right>")
    eq("| b | a |", buf_lines(buf)[1])
  end)
end)
