-- End-to-end: drive real buffer-local keymaps with feedkeys.
local function keys(k)
  vim.api.nvim_feedkeys(vim.keycode(k), "xt", false)
end

describe("keymaps e2e", function()
  it("cit cycles TODO keyword", function()
    local buf = org_buffer({ "* Task" }, { 1, 0 })
    keys("cit")
    eq("* TODO Task", buf_lines(buf)[1])
    keys("cit")
    eq("* NEXT Task", buf_lines(buf)[1])
  end)
  it(">> and << promote/demote headings", function()
    local buf = org_buffer({ "* A", "** B" }, { 2, 0 })
    keys(">>")
    eq("*** B", buf_lines(buf)[2])
    keys("<<")
    eq("** B", buf_lines(buf)[2])
  end)
  it(">> falls back to indent on plain text", function()
    local buf = org_buffer({ "text" }, { 1, 0 })
    vim.bo[buf].shiftwidth = 2
    keys(">>")
    eq("  text", buf_lines(buf)[1])
  end)
  it("<C-Space> toggles checkbox", function()
    local buf = org_buffer({ "* H", "- [ ] item" }, { 2, 0 })
    keys("<C-Space>")
    eq("- [X] item", buf_lines(buf)[2])
  end)
  it("<C-a> increments the date under the cursor", function()
    local buf = org_buffer({ "* H", "<2026-09-23 Wed>" }, { 2, 9 })
    keys("<C-a>")
    eq("<2026-09-24 Thu>", buf_lines(buf)[2])
  end)
  it("<C-a> still increments numbers elsewhere", function()
    local buf = org_buffer({ "x 5" }, { 1, 0 })
    keys("<C-a>")
    eq("x 6", buf_lines(buf)[1])
  end)
  it("<C-c><C-c> aligns a table", function()
    local buf = org_buffer({ "|a|bb|", "|-", "|ccc|d|" }, { 1, 1 })
    keys("<C-c><C-c>")
    eq({ "| a   | bb |", "|-----+----|", "| ccc | d  |" }, buf_lines(buf))
  end)
  it("<M-CR> on a list item adds an item", function()
    vim.g.org_test = true
    local buf = org_buffer({ "- one" }, { 1, 0 })
    keys("<M-CR>")
    vim.cmd("stopinsert")
    eq("- one", buf_lines(buf)[1])
    eq("- ", buf_lines(buf)[2])
  end)
  it("<Tab> cycles heading folds", function()
    org_buffer({ "* A", "text", "** B", "more" }, { 1, 0 })
    vim.cmd("normal! zX")
    keys("<Tab>")
    ok(vim.fn.foldclosed(2) == -1 or vim.fn.foldclosed(1) ~= -1)
  end)
end)
