local links = require("org.links")
local config = require("org.config")
local utils = require("org.utils")

vim.g.org_test = true
local root = vim.fn.getcwd()
local function base_setup(extra)
  config.setup(vim.tbl_deep_extend("force", {
    org_directory = root .. "/tests/fixtures",
    agenda_files = { root .. "/tests/fixtures/*.org" },
  }, extra or {}))
end

describe("links parsing", function()
  it("finds bracket, angle and plain links", function()
    local l = links.parse_links("See [[https://a.b/c][Site]] and <mailto:x@y.z> or https://e.com/x. [[*Head]] [[#cid]] [[file:~/a.org::*H]]")
    eq(6, #l)
    eq("https://a.b/c", l[1].target)
    eq("Site", l[1].desc)
    eq("https", l[1].type)
    eq("mailto", l[2].type)
    eq("https://e.com/x", l[3].target)
    eq("heading", l[4].type)
    eq("Head", l[4].path)
    eq("custom-id", l[5].type)
    eq("file", l[6].type)
    eq("~/a.org::*H", l[6].path)
  end)
  it("handles escapes and fuzzy/plain paths", function()
    local l = links.parse_links("[[foo\\]bar]] [[./x.txt]] [[My target]]")
    eq("foo]bar", l[1].target)
    eq("file", l[2].type)
    eq("fuzzy", l[3].type)
    eq("[[a\\]b][d]]", links.format("a]b", "d"))
  end)
  it("does not treat timestamps as links", function()
    eq(0, #links.parse_links("<2026-09-23 Wed> [2026-09-23 Wed]"))
  end)
  it("expands abbreviations", function()
    base_setup({ links = { abbreviations = { gh = "https://github.com/%s", g = "https://google.com/search?q=%h", w = "https://w.org/" } } })
    eq("https://github.com/a/b", links.expand_abbrev("gh:a/b"))
    eq("https://google.com/search?q=a%20b", links.expand_abbrev("g:a b"))
    eq("https://w.org/Page", links.expand_abbrev("w:Page"))
    base_setup()
  end)
end)

describe("links at cursor and opening", function()
  before_each(function()
    base_setup()
  end)
  it("link_at_cursor", function()
    org_buffer({ "text [[*Target][go]] end" }, { 1, 8 })
    local l = links.link_at_cursor()
    ok(l)
    eq("*Target", l.target)
    vim.api.nvim_win_set_cursor(0, { 1, 0 })
    eq(nil, links.link_at_cursor())
    eq(false, links.open_at_point())
  end)
  it("follows internal links", function()
    local buf = org_buffer({
      "[[*Second]] [[#cid]] [[tgt]] [[Third]] [[/re.ex/]] radio",
      "* First",
      "* Second",
      "* Third",
      ":PROPERTIES:",
      ":CUSTOM_ID: cid",
      ":END:",
      "some <<tgt>> here",
      "<<<radio>>>",
    }, { 1, 2 })
    links.open_at_point()
    eq(3, vim.api.nvim_win_get_cursor(0)[1])
    vim.api.nvim_win_set_cursor(0, { 1, 14 })
    links.open_at_point()
    eq(4, vim.api.nvim_win_get_cursor(0)[1])
    vim.api.nvim_win_set_cursor(0, { 1, 23 })
    links.open_at_point()
    eq({ 8, 5 }, vim.api.nvim_win_get_cursor(0))
    vim.api.nvim_win_set_cursor(0, { 1, 30 })
    links.open_at_point()
    eq(4, vim.api.nvim_win_get_cursor(0)[1])
    vim.api.nvim_buf_set_lines(buf, 1, 1, false, { "a reXex match" })
    ok(links.search_in_buffer("/reX.x/"))
    eq(2, vim.api.nvim_win_get_cursor(0)[1])
    vim.api.nvim_win_set_cursor(0, { 1, 52 })
    local l = links.link_at_cursor()
    eq("radio", l.type)
  end)
  it("opens file links with search options", function()
    local p = vim.fn.tempname() .. ".org"
    utils.writefile(p, { "* A", "* Target head", "line three", "<<dt>>" })
    org_buffer({ "[[file:" .. p .. "::*Target head]]" }, { 1, 3 })
    vim.bo.modified = false
    vim.bo.bufhidden = "hide"
    links.open_at_point()
    eq(vim.uv.fs_realpath(p), vim.uv.fs_realpath(vim.api.nvim_buf_get_name(0)))
    eq(2, vim.api.nvim_win_get_cursor(0)[1])
    links.open("file:" .. p .. "::3")
    eq(3, vim.api.nvim_win_get_cursor(0)[1])
    links.open("file:" .. p .. "::dt")
    eq(4, vim.api.nvim_win_get_cursor(0)[1])
  end)
  it("custom link types", function()
    local got
    base_setup({ links = { types = { jira = function(path)
      got = path
    end } } })
    org_buffer({ "[[jira:ABC-1]]" }, { 1, 3 })
    links.open_at_point()
    eq("ABC-1", got)
  end)
end)

describe("store and ids", function()
  before_each(function()
    base_setup({ id = { locations_file = vim.fn.tempname() .. ".json" } })
    require("org.id")._reset()
  end)
  it("stores file::*heading links", function()
    local p = vim.fn.tempname() .. ".org"
    utils.writefile(p, { "* Alpha", "body" })
    vim.cmd("edit! " .. p)
    vim.api.nvim_win_set_cursor(0, { 2, 0 })
    base_setup({ links = { use_id = false } })
    local l = links.store_link()
    local path = l.link:match("^file:(.-)::%*Alpha$")
    eq(vim.uv.fs_realpath(p), vim.uv.fs_realpath(vim.fn.expand(path)))
    eq("Alpha", l.desc)
    eq(l.link, links.stored[1].link)
  end)
  it("creates and finds ids", function()
    local p = vim.fn.tempname() .. ".org"
    utils.writefile(p, { "* Alpha", "* Beta" })
    vim.cmd("edit! " .. p)
    vim.api.nvim_win_set_cursor(0, { 2, 0 })
    local l = links.store_link()
    ok(l.link:match("^id:"), l.link)
    local id = l.link:sub(4)
    eq({ "* Alpha", "* Beta", ":PROPERTIES:", ":ID:       " .. id, ":END:" }, buf_lines())
    vim.cmd("write")
    vim.cmd("enew")
    local loc = require("org.id").find(id)
    ok(loc)
    eq(2, loc.lnum)
    links.open(l.link)
    eq(2, vim.api.nvim_win_get_cursor(0)[1])
  end)
end)
