-- orgtbl-to-unicode, orgtbl-to-table.el and the radar plot type. Expected
-- output is from Org 9.8.10 (orgtbl-to-unicode, orgtbl-to-table.el and
-- org-plot/gnuplot-script with :plot-type radar).
local orgtbl = require("org.table.orgtbl")
local plot = require("org.table.plot")

local TRANSLATED = {
  ["t1 table.el"] = {
    "| Name  | Qty |",
    "+-------+-----+",
    "| apple |   3 |",
    "| kiwi  |  12 |",
  },
  ["t1 unicode"] = {
    "━━━━━━━━━━━━",
    " Name   Qty ",
    "────────────",
    " apple    3 ",
    " kiwi    12 ",
    "━━━━━━━━━━━━",
  },
  ["t1 unicode narrow"] = {
    "━━━━━━━━━━━━",
    " Name   Qty ",
    "────────────",
    " apple    3 ",
    " kiwi    12 ",
    "━━━━━━━━━━━━",
  },
  ["t1 unicode skip"] = {
    "━━━━",
    "  3 ",
    " 12 ",
    "━━━━",
  },
  ["t2 table.el"] = {
    "| a | b | c |",
    "| 1 | 2 | 3 |",
  },
  ["t2 unicode"] = {
    "━━━━━━━━━",
    " a  b  c ",
    " 1  2  3 ",
    "━━━━━━━━━",
  },
  ["t2 unicode narrow"] = {
    "━━━━━━━━━",
    " a  b  c ",
    " 1  2  3 ",
    "━━━━━━━━━",
  },
  ["t2 unicode skip"] = {
    "━━━━━━",
    " 2  3 ",
    "━━━━━━",
  },
  ["t3 table.el"] = {
    "|   x |  y |",
    "+-----+----+",
    "|   1 | 22 |",
    "+-----+----+",
    "| 333 |  4 |",
  },
  ["t3 unicode"] = {
    "━━━━━━━━━",
    "   x   y ",
    "─────────",
    "   1  22 ",
    "─────────",
    " 333   4 ",
    "━━━━━━━━━",
  },
  ["t3 unicode narrow"] = {
    "━━━━━━━━━",
    "   x   y ",
    "─────────",
    "   1  22 ",
    "─────────",
    " 333   4 ",
    "━━━━━━━━━",
  },
  ["t3 unicode skip"] = {
    "━━━━",
    " 22 ",
    "────",
    "  4 ",
    "━━━━",
  },
  ["t4 table.el"] = {
    "|     | <5>            |",
    "| h   | long text here |",
    "+-----+----------------+",
    "| *b* | /i/            |",
  },
  ["t4 unicode"] = {
    "━━━━━━━━━━━━━━━━━━━━━",
    " h    long text here ",
    "─────────────────────",
    " *b*  /i/            ",
    "━━━━━━━━━━━━━━━━━━━━━",
  },
  ["t4 unicode narrow"] = {
    "━━━━━━━━━━━━",
    " h    lon=> ",
    "────────────",
    " *b*  /i/   ",
    "━━━━━━━━━━━━",
  },
  ["t4 unicode skip"] = {
    "━━━━━━━━━━━━━━━━",
    " long text here ",
    "────────────────",
    " /i/            ",
    "━━━━━━━━━━━━━━━━",
  },
  ["t5 table.el"] = {
    "| é | ü |",
    "+---+---+",
    "| 1 |   |",
  },
  ["t5 unicode"] = {
    "━━━━━━",
    " é  ü ",
    "──────",
    " 1    ",
    "━━━━━━",
  },
  ["t5 unicode narrow"] = {
    "━━━━━━",
    " é  ü ",
    "──────",
    " 1    ",
    "━━━━━━",
  },
  ["t5 unicode skip"] = {
    "━━",
    "  ",
    "━━",
  },
  ["m table.el"] = {
    "| =v= | ~c~ | [[https://x.org][desc]] | _u_ | +s+ | a\\_b | \\alpha |",
  },
  ["m unicode"] = {
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    " `v'  `c'  [desc]  _u_  +s+  a\\_b  α ",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  },
  ["m unicode narrow"] = {
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    " `v'  `c'  [desc]  _u_  +s+  a\\_b  α ",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  },
  ["m unicode skip"] = {
    "",
  },
  ["g table.el"] = {
    "| / | < | > |",
    "| a | b | c |",
    "| 1 | 2 | 3 |",
  },
  ["g unicode"] = {
    "━━━┯━━━━━━┑",
    " a │ b  c │",
    " 1 │ 2  3 │",
    "━━━┷━━━━━━┙",
  },
  ["g unicode narrow"] = {
    "━━━┯━━━━━━┑",
    " a │ b  c │",
    " 1 │ 2  3 │",
    "━━━┷━━━━━━┙",
  },
  ["g unicode skip"] = {
    "━━━━━━",
    " b  c ",
    " 2  3 ",
    "━━━━━━",
  },
  ["mixed table.el"] = {
    "|   n | t  |",
    "+-----+----+",
    "|   1 | x  |",
    "| 2.5 | yy |",
    "| abc | 3  |",
  },
  ["mixed unicode"] = {
    "━━━━━━━━━",
    "   n  t  ",
    "─────────",
    "   1  x  ",
    " 2.5  yy ",
    " abc  3  ",
    "━━━━━━━━━",
  },
  ["mixed unicode narrow"] = {
    "━━━━━━━━━",
    "   n  t  ",
    "─────────",
    "   1  x  ",
    " 2.5  yy ",
    " abc  3  ",
    "━━━━━━━━━",
  },
  ["mixed unicode skip"] = {
    "━━━━",
    " x  ",
    " yy ",
    " 3  ",
    "━━━━",
  },
  ["special table.el"] = {
    "| x | y |",
    "| 1 | 2 |",
    "+---+---+",
    "| 3 | 4 |",
  },
  ["special unicode"] = {
    "━━━━━━",
    " 1  2 ",
    "──────",
    " 3  4 ",
    "━━━━━━",
  },
  ["special unicode narrow"] = {
    "━━━━━━",
    " 1  2 ",
    "──────",
    " 3  4 ",
    "━━━━━━",
  },
  ["special unicode skip"] = {
    "━━━",
    " 2 ",
    "───",
    " 4 ",
    "━━━",
  },
  ["cookie table.el"] = {
    "| <l> | <5> |",
    "| a   | b   |",
  },
  ["cookie unicode"] = {
    "━━━━━━━━━━",
    " a  b     ",
    "━━━━━━━━━━",
  },
  ["cookie unicode narrow"] = {
    "━━━━━━━━━━",
    " a  b     ",
    "━━━━━━━━━━",
  },
  ["cookie unicode skip"] = {
    "━━━",
    " b ",
    "━━━",
  },
  ["groups table.el"] = {
    "| / | <> | < | > |",
    "| a | b  | c | d |",
    "+---+----+---+---+",
    "| 1 | 2  | 3 | 4 |",
  },
  ["groups unicode"] = {
    "━━━┯━━━┯━━━━━━┑",
    " a │ b │ c  d │",
    "───┼───┼──────┤",
    " 1 │ 2 │ 3  4 │",
    "━━━┷━━━┷━━━━━━┙",
  },
  ["groups unicode narrow"] = {
    "━━━┯━━━┯━━━━━━┑",
    " a │ b │ c  d │",
    "───┼───┼──────┤",
    " 1 │ 2 │ 3  4 │",
    "━━━┷━━━┷━━━━━━┙",
  },
  ["groups unicode skip"] = {
    "━━━━━━━━━",
    " b  c  d ",
    "─────────",
    " 2  3  4 ",
    "━━━━━━━━━",
  },
  ["groups2 table.el"] = {
    "| / | < |   | > |",
    "| a | b | c | d |",
  },
  ["groups2 unicode"] = {
    "━━━┯━━━━━━━━━┑",
    " a │ b  c  d │",
    "━━━┷━━━━━━━━━┙",
  },
  ["groups2 unicode narrow"] = {
    "━━━┯━━━━━━━━━┑",
    " a │ b  c  d │",
    "━━━┷━━━━━━━━━┙",
  },
  ["groups2 unicode skip"] = {
    "━━━━━━━━━",
    " b  c  d ",
    "━━━━━━━━━",
  },
}
local RADAR = {
  "reset",
  "set term GNUTERM ",
  "",
  "set datafile separator \"\\t\"",
  "### spider plot/chart with gnuplot",
  "# also known as: radar chart, web chart, star chart, cobweb chart,",
  "#                radar plot,  web plot,  star plot,  cobweb plot,  etc. ...",
  "set datafile separator ' '",
  "set size square",
  "unset tics",
  "set angles degree",
  "set key bmargin center horizontal",
  "unset border",
  "",
  "# Load data and setup",
  "load \"SETUP\"",
  "",
  "# General settings",
  "DataColCount = words($Data[1])-1",
  "AxesCount = |$Data|-HeaderLines-1",
  "AngleOffset = 90",
  "Max = 1",
  "d=0.1*Max",
  "Direction = -1   # counterclockwise=1, clockwise = -1",
  "",
  "# Tic settings",
  "TicCount = 6",
  "TicOffset = 0.1",
  "TicValue(axis,i) = real(i)*(word($Settings[axis],3)-word($Settings[axis],2)) \\",
  "	  / word($Settings[axis],4)+word($Settings[axis],2)",
  "TicLabelPosX(axis,i) = PosX(axis,i/TicCount) + PosY(axis, TicOffset)",
  "TicLabelPosY(axis,i) = PosY(axis,i/TicCount) - PosX(axis, TicOffset)",
  "TicLen = 0.03",
  "TicdX(axis,i) = 0.5*TicLen*cos(alpha(axis)-90)",
  "TicdY(axis,i) = 0.5*TicLen*sin(alpha(axis)-90)",
  "",
  "# Label",
  "LabOffset = 0.10",
  "LabX(axis) = PosX(axis+1,Max+2*d) + PosY(axis, LabOffset)",
  "LabY(axis) = PosY($0+1,Max+2*d)",
  "",
  "# Functions",
  "alpha(axis) = (axis-1)*Direction*360.0/AxesCount+AngleOffset",
  "PosX(axis,R) = R*cos(alpha(axis))",
  "PosY(axis,R) = R*sin(alpha(axis))",
  "Scale(axis,value) = real(value-word($Settings[axis],2))/(word($Settings[axis],3)-word($Settings[axis],2))",
  "",
  "# Spider settings",
  "set style arrow 1 dt 1 lw 1.0 @fgal head filled size 0.06,25     # style for axes",
  "set style arrow 2 dt 2 lw 0.5 @fgal nohead   # style for weblines",
  "set style arrow 3 dt 1 lw 1 @fgal nohead     # style for axis tics",
  "set samples AxesCount",
  "set isosamples TicCount",
  "set urange[1:AxesCount]",
  "set vrange[1:TicCount]",
  "set style fill transparent solid 0.2",
  "",
  "set xrange[-Max-4*d:Max+4*d]",
  "set yrange[-Max-4*d:Max+4*d]",
  "plot \\",
  "    '+' u (0):(0):(PosX($0,Max+d)):(PosY($0,Max+d)) w vec as 1 not, \\",
  "    $Data u (LabX($0)): \\",
  "	(LabY($0)):1 every ::HeaderLines w labels center enhanced @fgt not, \\",
  "    for [i=1:DataColCount] $Data u (PosX($0+1,Scale($0+1,column(i+1)))): \\",
  "	(PosY($0+1,Scale($0+1,column(i+1)))) every ::HeaderLines w filledcurves lt i title word($Data[1],i+1), \\",
  "    '++' u (PosX($1,$2/TicCount)):(PosY($1,$2/TicCount)): \\",
  "	(PosX($1+1,$2/TicCount)-PosX($1,$2/TicCount)):  \\",
  "	(PosY($1+1,$2/TicCount)-PosY($1,$2/TicCount)) w vec as 2 not, \\",
  "    '++' u (TicLabelPosX($1,$2)):(TicLabelPosY($1,$2)): \\",
  "	(sprintf('%g',TicValue($1,$2))) w labels font ',8' @fgat not",
  "#    '++' u (PosX($1,$2/TicCount)-TicdX($1,$2/TicCount)): \\",
  "#        (PosY($1,$2/TicCount)-TicdY($1,$2/TicCount)): \\",
  "#        (2*TicdX($1,$2/TicCount)):(2*TicdY($1,$2/TicCount)) \\",
  "#        w vec as 3 not, \\",
  "### end of code",
  "",
  "=== setup",
  "# Data",
  "$Data <<HEREHAVESOMEDATA",
  "\"Skill\" \"Alice\" \"Bob\"",
  "\"Speed\" 7 4",
  "\"Power\" 3 9",
  "\"Range\" 5 6",
  "\"Wits\" 8 2",
  "\"Speed\" 7 4",
  "HEREHAVESOMEDATA",
  "HeaderLines = 1",
  "",
  "# Settings for scale and offset adjustments",
  "# axis min max tics axisLabelXoff axisLabelYoff",
  "$Settings <<EOD",
  "\"Speed\" 4.0 7.0 6",
  "\"Power\" 3.0 9.0 6",
  "\"Range\" 5.0 6.0 6",
  "\"Wits\" 2.0 8.0 6",
  "\"Speed\" 4.0 7.0 6",
  "EOD",
  "=== end",
  "reset",
  "set term GNUTERM ",
  "",
  "set datafile separator \"\\t\"",
  "### spider plot/chart with gnuplot",
  "# also known as: radar chart, web chart, star chart, cobweb chart,",
  "#                radar plot,  web plot,  star plot,  cobweb plot,  etc. ...",
  "set datafile separator ' '",
  "set size square",
  "unset tics",
  "set angles degree",
  "set key bmargin center horizontal",
  "unset border",
  "",
  "# Load data and setup",
  "load \"SETUP\"",
  "",
  "# General settings",
  "DataColCount = words($Data[1])-1",
  "AxesCount = |$Data|-HeaderLines-1",
  "AngleOffset = 90",
  "Max = 1",
  "d=0.1*Max",
  "Direction = -1   # counterclockwise=1, clockwise = -1",
  "",
  "# Tic settings",
  "TicCount = 19",
  "TicOffset = 0.1",
  "TicValue(axis,i) = real(i)*(word($Settings[axis],3)-word($Settings[axis],2)) \\",
  "	  / word($Settings[axis],4)+word($Settings[axis],2)",
  "TicLabelPosX(axis,i) = PosX(axis,i/TicCount) + PosY(axis, TicOffset)",
  "TicLabelPosY(axis,i) = PosY(axis,i/TicCount) - PosX(axis, TicOffset)",
  "TicLen = 0.03",
  "TicdX(axis,i) = 0.5*TicLen*cos(alpha(axis)-90)",
  "TicdY(axis,i) = 0.5*TicLen*sin(alpha(axis)-90)",
  "",
  "# Label",
  "LabOffset = 0.10",
  "LabX(axis) = PosX(axis+1,Max+2*d) + PosY(axis, LabOffset)",
  "LabY(axis) = PosY($0+1,Max+2*d)",
  "",
  "# Functions",
  "alpha(axis) = (axis-1)*Direction*360.0/AxesCount+AngleOffset",
  "PosX(axis,R) = R*cos(alpha(axis))",
  "PosY(axis,R) = R*sin(alpha(axis))",
  "Scale(axis,value) = real(value-word($Settings[axis],2))/(word($Settings[axis],3)-word($Settings[axis],2))",
  "",
  "# Spider settings",
  "set style arrow 1 dt 1 lw 1.0 @fgal head filled size 0.06,25     # style for axes",
  "set style arrow 2 dt 2 lw 0.5 @fgal nohead   # style for weblines",
  "set style arrow 3 dt 1 lw 1 @fgal nohead     # style for axis tics",
  "set samples AxesCount",
  "set isosamples TicCount",
  "set urange[1:AxesCount]",
  "set vrange[1:TicCount]",
  "set style fill transparent solid 0.2",
  "",
  "set xrange[-Max-4*d:Max+4*d]",
  "set yrange[-Max-4*d:Max+4*d]",
  "plot \\",
  "    '+' u (0):(0):(PosX($0,Max+d)):(PosY($0,Max+d)) w vec as 1 not, \\",
  "    $Data u (LabX($0)): \\",
  "	(LabY($0)):1 every ::HeaderLines w labels center enhanced @fgt not, \\",
  "    for [i=1:DataColCount] $Data u (PosX($0+1,Scale($0+1,column(i+1)))): \\",
  "	(PosY($0+1,Scale($0+1,column(i+1)))) every ::HeaderLines w filledcurves lt i title word($Data[1],i+1), \\",
  "    '++' u (PosX($1,$2/TicCount)):(PosY($1,$2/TicCount)): \\",
  "	(PosX($1+1,$2/TicCount)-PosX($1,$2/TicCount)):  \\",
  "	(PosY($1+1,$2/TicCount)-PosY($1,$2/TicCount)) w vec as 2 not, \\",
  "    '++' u (TicLabelPosX($1,$2)):(TicLabelPosY($1,$2)): \\",
  "	(sprintf('%g',TicValue($1,$2))) w labels font ',8' @fgat not",
  "#    '++' u (PosX($1,$2/TicCount)-TicdX($1,$2/TicCount)): \\",
  "#        (PosY($1,$2/TicCount)-TicdY($1,$2/TicCount)): \\",
  "#        (2*TicdX($1,$2/TicCount)):(2*TicdY($1,$2/TicCount)) \\",
  "#        w vec as 3 not, \\",
  "### end of code",
  "",
  "=== setup",
  "# Data",
  "$Data <<HEREHAVESOMEDATA",
  "\"Axis\" \"A\" \"B\" \"C\"",
  "\"x\" 1.5 20 3",
  "\"y\" 12 4 7.25",
  "\"z\" 100 5 55",
  "\"x\" 1.5 20 3",
  "HEREHAVESOMEDATA",
  "HeaderLines = 1",
  "",
  "# Settings for scale and offset adjustments",
  "# axis min max tics axisLabelXoff axisLabelYoff",
  "$Settings <<EOD",
  "\"x\" 1.0 20.0 19",
  "\"y\" 4.0 12.0 19",
  "\"z\" 5.0 100.0 19",
  "\"x\" 1.0 20.0 19",
  "EOD",
  "=== end",
  "reset",
  "set term GNUTERM ",
  "",
  "set title 'Skills'",
  "set datafile separator \"\\t\"",
  "### spider plot/chart with gnuplot",
  "# also known as: radar chart, web chart, star chart, cobweb chart,",
  "#                radar plot,  web plot,  star plot,  cobweb plot,  etc. ...",
  "set datafile separator ' '",
  "set size square",
  "unset tics",
  "set angles degree",
  "set key bmargin center horizontal",
  "unset border",
  "",
  "# Load data and setup",
  "load \"SETUP\"",
  "",
  "# General settings",
  "DataColCount = words($Data[1])-1",
  "AxesCount = |$Data|-HeaderLines-1",
  "AngleOffset = 90",
  "Max = 1",
  "d=0.1*Max",
  "Direction = -1   # counterclockwise=1, clockwise = -1",
  "",
  "# Tic settings",
  "TicCount = 5",
  "TicOffset = 0.1",
  "TicValue(axis,i) = real(i)*(word($Settings[axis],3)-word($Settings[axis],2)) \\",
  "	  / word($Settings[axis],4)+word($Settings[axis],2)",
  "TicLabelPosX(axis,i) = PosX(axis,i/TicCount) + PosY(axis, TicOffset)",
  "TicLabelPosY(axis,i) = PosY(axis,i/TicCount) - PosX(axis, TicOffset)",
  "TicLen = 0.03",
  "TicdX(axis,i) = 0.5*TicLen*cos(alpha(axis)-90)",
  "TicdY(axis,i) = 0.5*TicLen*sin(alpha(axis)-90)",
  "",
  "# Label",
  "LabOffset = 0.10",
  "LabX(axis) = PosX(axis+1,Max+2*d) + PosY(axis, LabOffset)",
  "LabY(axis) = PosY($0+1,Max+2*d)",
  "",
  "# Functions",
  "alpha(axis) = (axis-1)*Direction*360.0/AxesCount+AngleOffset",
  "PosX(axis,R) = R*cos(alpha(axis))",
  "PosY(axis,R) = R*sin(alpha(axis))",
  "Scale(axis,value) = real(value-word($Settings[axis],2))/(word($Settings[axis],3)-word($Settings[axis],2))",
  "",
  "# Spider settings",
  "set style arrow 1 dt 1 lw 1.0 @fgal head filled size 0.06,25     # style for axes",
  "set style arrow 2 dt 2 lw 0.5 @fgal nohead   # style for weblines",
  "set style arrow 3 dt 1 lw 1 @fgal nohead     # style for axis tics",
  "set samples AxesCount",
  "set isosamples TicCount",
  "set urange[1:AxesCount]",
  "set vrange[1:TicCount]",
  "set style fill transparent solid 0.2",
  "",
  "set xrange[-Max-4*d:Max+4*d]",
  "set yrange[-Max-4*d:Max+4*d]",
  "plot \\",
  "    '+' u (0):(0):(PosX($0,Max+d)):(PosY($0,Max+d)) w vec as 1 not, \\",
  "    $Data u (LabX($0)): \\",
  "	(LabY($0)):1 every ::HeaderLines w labels center enhanced @fgt not, \\",
  "    for [i=1:DataColCount] $Data u (PosX($0+1,Scale($0+1,column(i+1)))): \\",
  "	(PosY($0+1,Scale($0+1,column(i+1)))) every ::HeaderLines w filledcurves lt i title word($Data[1],i+1), \\",
  "    '++' u (PosX($1,$2/TicCount)):(PosY($1,$2/TicCount)): \\",
  "	(PosX($1+1,$2/TicCount)-PosX($1,$2/TicCount)):  \\",
  "	(PosY($1+1,$2/TicCount)-PosY($1,$2/TicCount)) w vec as 2 not, \\",
  "    '++' u (TicLabelPosX(1,$2)):(TicLabelPosY(1,$2)): \\",
  "	(sprintf('%g',TicValue(1,$2))) w labels font ',8' @fgat not",
  "#    '++' u (PosX($1,$2/TicCount)-TicdX($1,$2/TicCount)): \\",
  "#        (PosY($1,$2/TicCount)-TicdY($1,$2/TicCount)): \\",
  "#        (2*TicdX($1,$2/TicCount)):(2*TicdY($1,$2/TicCount)) \\",
  "#        w vec as 3 not, \\",
  "### end of code",
  "",
  "=== setup",
  "# Data",
  "$Data <<HEREHAVESOMEDATA",
  "\"Skill\" \"Alice\" \"Bob\"",
  "\"Speed\" 7 4",
  "\"Power\" 3 9",
  "\"Range\" 5 6",
  "\"Speed\" 7 4",
  "HEREHAVESOMEDATA",
  "HeaderLines = 1",
  "",
  "# Settings for scale and offset adjustments",
  "# axis min max tics axisLabelXoff axisLabelYoff",
  "$Settings <<EOD",
  "\"Speed\" 0 10 5",
  "\"Power\" 0 10 5",
  "\"Range\" 0 10 5",
  "\"Speed\" 0 10 5",
  "EOD",
  "=== end",
}

local TABLES = {
  { "t1", "| Name | Qty |\n|------+-----|\n| apple | 3 |\n| kiwi | 12 |" },
  { "t2", "| a | b | c |\n| 1 | 2 | 3 |" },
  { "t3", "| x | y |\n|---+---|\n| 1 | 22 |\n|---+---|\n| 333 | 4 |" },
  { "t4", "|  | <5> |\n| h | long text here |\n|---+---|\n| *b* | /i/ |" },
  { "t5", "| é | ü |\n|---+---|\n| 1 |  |" },
  { "m", "| =v= | ~c~ | [[https://x.org][desc]] | _u_ | +s+ | a\\_b | \\alpha |" },
  { "g", "| / | < | > |\n| a | b | c |\n| 1 | 2 | 3 |" },
  { "mixed", "| n | t |\n|---+---|\n| 1 | x |\n| 2.5 | yy |\n| abc | 3 |" },
  { "special", "| ! | x | y |\n| # | 1 | 2 |\n|---+---+---|\n| # | 3 | 4 |" },
  { "cookie", "| <l> | <5> |\n| a | b |" },
  { "groups", "| / | <> | < | > |\n| a | b | c | d |\n|---+---+---+---|\n| 1 | 2 | 3 | 4 |" },
  { "groups2", "| / | < |  | > |\n| a | b | c | d |" },
}

describe("orgtbl-to-unicode and orgtbl-to-table.el", function()
  it("translate like Emacs", function()
    local variants = {
      { "table.el", "orgtbl-to-table.el", {} },
      { "unicode", "orgtbl-to-unicode", {} },
      { "unicode narrow", "orgtbl-to-unicode", { narrow = true } },
      { "unicode skip", "orgtbl-to-unicode", ":skip 1 :skipcols (1)" },
    }
    for _, t in ipairs(TABLES) do
      local rows = orgtbl.to_lisp(vim.split(t[2], "\n"))
      for _, v in ipairs(variants) do
        local name = t[1] .. " " .. v[1]
        eq(table.concat(TRANSLATED[name], "\n"), orgtbl.translate(v[2], rows, v[3]), name)
      end
    end
  end)

  it("are radio table translators", function()
    local buf = org_buffer({
      "#+ORGTBL: SEND t orgtbl-to-unicode",
      "| a | 1 |",
      "",
      "BEGIN RECEIVE ORGTBL t",
      "END RECEIVE ORGTBL t",
    }, { 2, 2 })
    orgtbl.send_table(buf, 2)
    local expected = { "BEGIN RECEIVE ORGTBL t", "━━━━━━", " a  1 ", "━━━━━━", "END RECEIVE ORGTBL t" }
    eq(expected, vim.list_slice(buf_lines(buf), 4))
  end)
end)

describe("radar plots", function()
  it("write the gnuplot script and setup of org-plot", function()
    local cases = {
      {
        "| Skill | Alice | Bob |\n|---+---+---|\n"
          .. "| Speed | 7 | 4 |\n| Power | 3 | 9 |\n| Range | 5 | 6 |\n| Wits | 8 | 2 |",
      },
      { "| Axis | A | B | C |\n|---+---+---+---|\n| x | 1.5 | 20 | 3 |\n| y | 12 | 4 | 7.25 |\n| z | 100 | 5 | 55 |" },
      {
        "| Skill | Alice | Bob |\n|---+---+---|\n| Speed | 7 | 4 |\n| Power | 3 | 9 |\n| Range | 5 | 6 |",
        'min:0 max:10 ticks:5 title:"Skills"',
      },
    }
    local out = {}
    for _, c in ipairs(cases) do
      local lines = vim.split(c[1], "\n")
      table.insert(lines, 1, "#+PLOT: type:radar " .. (c[2] or ""))
      local buf = org_buffer(lines, { 1, 0 })
      local opts, rows, ncols = plot.collect(buf, 1)
      opts.setup_file = vim.fn.tempname()
      local script = plot.script(rows, "DATAFILE", ncols, opts)
      vim.list_extend(out, vim.split((script:gsub(vim.pesc(opts.setup_file), "SETUP")), "\n"))
      out[#out + 1] = "=== setup"
      local setup = table.concat(vim.fn.readfile(opts.setup_file), "\n")
      vim.list_extend(out, vim.split(setup, "\n"))
      out[#out + 1] = "=== end"
      os.remove(opts.setup_file)
    end
    eq(RADAR, out)
  end)
end)
