-- table.el tables (`+---+` grids). Expected conversions and exports are
-- from Emacs 31.1 with Org 9.8.10 (org-table-create-with-table.el,
-- org-table-convert, table-insert and batch exports); the HTML comment
-- naming the generator differs (Emacs writes its version there).

local el = require("org.table.el")
local export = require("org.export")

local SPANS = {
  "+-----+--+",
  "|0    |1 |",
  "+--+--+  |",
  "|2 |3 |  |",
  "|  +--+--+",
  "|  |4    |",
  "+--+-----+",
}

local LADDER = {
  "+--+--+--+",
  "|0 |1 |2 |",
  "|  +--+  |",
  "+--+3 +--+",
  "|4 +--+5 |",
  "|  |6 |  |",
  "+--+--+--+",
}

local function body(backend, lines)
  return export.to_string(backend, { lines = lines, body_only = true })
end

local function html_cell(attrs, ...)
  local out = { "    <td" .. attrs .. ' align="left" valign="top">' }
  for _, l in ipairs({ ... }) do
    out[#out + 1] = "      " .. l
  end
  out[#out + 1] = "    </td>"
  return table.concat(out, "\n")
end

local HEAD = "<!-- This HTML table template is generated by org.nvim -->\n" .. '<table border="1">\n'

describe("table.el tables", function()
  describe("detection", function()
    it("recognizes a table.el table like org-element", function()
      local lines = vim.list_extend({ "text" }, SPANS)
      eq(nil, el.bounds(lines, 1))
      for l = 2, 8 do
        eq({ 2, 8 }, { el.bounds(lines, l) })
      end
      ok(el.is_rule("  +--+---+  "))
      ok(not el.is_rule("+--++"))
      ok(not el.is_rule("+ item"))
      -- It must start and end with a full rule.
      eq(nil, el.bounds({ "+--+", "|a |" }, 2))
      eq(nil, el.bounds({ "+--+" }, 1))
      -- An Org table next to it is not part of it.
      local mixed = { "| a |", "+--+", "|b |", "+--+" }
      eq(nil, el.bounds(mixed, 1))
      eq({ 2, 4 }, { el.bounds(mixed, 3) })
    end)

    it("keeps Org table commands off table.el tables", function()
      local buf = org_buffer(vim.list_extend({ "* H" }, SPANS), { 3, 2 })
      local tbl = require("org.table")
      eq(nil, tbl.find(buf, 3))
      eq(nil, tbl.at_cursor())
      -- C-c C-c and TAB only suggest C-c ' (org-ctrl-c-ctrl-c, org-cycle).
      local msgs = {}
      local notify = require("org.utils").notify
      require("org.utils").notify = function(m)
        msgs[#msgs + 1] = m
      end
      require("org.context").context_action()
      require("org.fold").cycle()
      require("org.context").insert_tab()
      require("org.utils").notify = notify
      local hint = "Use C-c ' to edit table.el tables"
      eq({ hint, hint, hint }, msgs)
      eq(vim.list_extend({ "* H" }, SPANS), buf_lines(buf))
      -- InsertLeave realignment of Org tables leaves it alone too.
      vim.api.nvim_exec_autocmds("InsertLeave", { buffer = buf })
      eq(vim.list_extend({ "* H" }, SPANS), buf_lines(buf))
    end)

    it("highlights the borders like table lines", function()
      org_buffer(vim.list_extend({ "* H" }, SPANS))
      vim.cmd("syntax sync fromstart")
      eq("orgtable", vim.fn.synIDattr(vim.fn.synID(2, 3, 1), "name"):lower())
      eq("orgtable", vim.fn.synIDattr(vim.fn.synID(3, 3, 1), "name"):lower())
    end)

    it("is one element for the structure commands", function()
      local buf = org_buffer(vim.list_extend({ "* H", "Para" }, SPANS), { 5, 0 })
      local e = require("org.element").at(buf, 5)
      eq({ "table", 3, 9 }, { e.type, e.first, e.last })
      eq("paragraph", require("org.element").at(buf, 2).type)
      eq(2, require("org.element").at(buf, 2).last)
      local ast = require("org.export.element").parse(vim.list_extend({ "Para" }, SPANS))
      local tbl
      require("org.export.element").map(ast, "table", function(t)
        tbl = t
      end)
      eq("table.el", tbl.table_type)
    end)
  end)

  describe("C-c ~ (org-table-create-with-table.el)", function()
    local confirm
    before_each(function()
      confirm = require("org.utils").confirm
      require("org.utils").confirm = function()
        return true
      end
    end)
    after_each(function()
      require("org.utils").confirm = confirm
    end)

    it("converts an Org table to table.el after aligning it", function()
      local buf = org_buffer(
        { "* H", "text", "| a | bb |", "|---+----|", "| 1 | 22 |", "| xyz | |", "after" },
        { 3, 2 }
      )
      require("org.table").table_el()
      eq({
        "* H",
        "text",
        "+-----+----+",
        "| a   | bb |",
        "+-----+----+",
        "| 1   | 22 |",
        "+-----+----+",
        "| xyz |    |",
        "+-----+----+",
        "after",
      }, buf_lines(buf))
    end)

    it("keeps the indentation of the table", function()
      local buf = org_buffer({ "* H", "  - item", "    | a | b |", "    | c | d |" }, { 3, 5 })
      require("org.table").table_el()
      eq({
        "* H",
        "  - item",
        "    +---+---+",
        "    | a | b |",
        "    +---+---+",
        "    | c | d |",
        "    +---+---+",
      }, buf_lines(buf))
    end)

    it("converts a table.el table back by removing its borders", function()
      local buf = org_buffer(
        { "+---+----+", "|a  |bb  |", "+---+----+", "|1  |22  |", "|   |x   |", "+---+----+", "after" },
        { 2, 0 }
      )
      require("org.table").table_el()
      eq({ "|a  |bb  |", "|1  |22  |", "|   |x   |", "after" }, buf_lines(buf))
      buf = org_buffer(SPANS, { 2, 0 })
      require("org.table").table_el()
      eq({ "|0    |1 |", "|2 |3 |  |", "|  +--+--+", "|  |4    |" }, buf_lines(buf))
    end)

    it("inserts a new table elsewhere (table-insert)", function()
      local answers = { "2", "2", "3 6", "1 2" }
      local input = require("org.utils").input
      require("org.utils").input = function()
        return table.remove(answers, 1)
      end
      local buf = org_buffer({ "" }, { 1, 0 })
      require("org.table").table_el()
      require("org.utils").input = input
      eq(
        { "+---+------+", "|   |      |", "+---+------+", "|   |      |", "|   |      |", "+---+------+", "" },
        buf_lines(buf)
      )
      eq({ 2, 1 }, vim.api.nvim_win_get_cursor(0))
      eq({ "+-----+-----+", "|     |     |", "+-----+-----+" }, el.new(2, 1, { 5 }, { 1 }))
    end)
  end)

  describe("C-c ' (org-edit-table.el)", function()
    it("edits the table in a buffer and realigns it on write", function()
      local buf = org_buffer(
        { "* H", "  +---+----+", "  |a  |bb  |", "  +---+----+", "  |1  |22  |", "  +---+----+" },
        { 3, 3 }
      )
      require("org.context").edit_special()
      local ebuf = vim.api.nvim_get_current_buf()
      ok(ebuf ~= buf)
      eq({ "+---+----+", "|a  |bb  |", "+---+----+", "|1  |22  |", "+---+----+" }, buf_lines(ebuf))
      -- Text typed past a border widens the column (trailing blanks of a
      -- cell do not count); a copied line adds a line to the row.
      vim.api.nvim_buf_set_lines(ebuf, 1, 2, false, { "|alpha  |bb  |" })
      vim.api.nvim_buf_set_lines(ebuf, 3, 4, false, { "|1  |22  |", "|   |more text |" })
      vim.cmd("write")
      eq({
        "+-----+---------+",
        "|alpha|bb       |",
        "+-----+---------+",
        "|1    |22       |",
        "|     |more text|",
        "+-----+---------+",
      }, buf_lines(ebuf))
      vim.cmd("bwipeout!")
      vim.api.nvim_set_current_buf(buf)
      eq({
        "* H",
        "  +-----+---------+",
        "  |alpha|bb       |",
        "  +-----+---------+",
        "  |1    |22       |",
        "  |     |more text|",
        "  +-----+---------+",
      }, buf_lines(buf))
    end)

    it("keeps spanned cells when realigning", function()
      local edited = vim.deepcopy(SPANS)
      edited[2] = "|0 wider text    |1 |"
      edited[6] = "|  |4 and more|"
      eq({
        "+------------+--+",
        "|0 wider text|1 |",
        "+--+---------+  |",
        "|2 |3        |  |",
        "|  +---------+--+",
        "|  |4 and more  |",
        "+--+------------+",
      }, el.realign(edited, SPANS))
      eq(LADDER, el.realign(LADDER, LADDER))
      -- Removing a line of a two-line row.
      eq({ "+--+", "|a |", "+--+" }, el.realign({ "+--+", "|a |", "+--+" }, { "+--+", "|a |", "|  |", "+--+" }))
      -- `=` borders stay.
      eq(
        { "+----+", "|a   |", "+====+", "|bcde|", "+----+" },
        el.realign({ "+--+", "|a |", "+==+", "|bcde|", "+--+" }, { "+--+", "|a |", "+==+", "|b |", "+--+" })
      )
      local res, err = el.realign({ "+--+", "|a|b |", "+--+" }, { "+--+", "|a |", "+--+" })
      eq(nil, res)
      ok(err:match("broken"))
    end)

    it("realigns when leaving Insert mode, also on lines shared with borders", function()
      local buf = org_buffer(LADDER, { 4, 4 })
      require("org.special").edit_element(buf, 4)
      local ebuf = vim.api.nvim_get_current_buf()
      vim.api.nvim_buf_set_lines(ebuf, 3, 4, false, { "+--+3 long +--+" })
      vim.api.nvim_exec_autocmds("InsertLeave", { buffer = ebuf })
      eq({
        "+--+------+--+",
        "|0 |1     |2 |",
        "|  +------+  |",
        "+--+3 long+--+",
        "|4 +------+5 |",
        "|  |6     |  |",
        "+--+------+--+",
      }, buf_lines(ebuf))
      vim.cmd("bwipeout!")
    end)

    it("is refused outside a table.el table", function()
      local buf = org_buffer({ "text" }, { 1, 0 })
      local err = require("org.utils").error
      local msg
      require("org.utils").error = function(m)
        msg = m
      end
      eq(false, el.edit(buf, 1))
      require("org.utils").error = err
      eq("Not in a table.el table", msg)
    end)
  end)

  describe("export", function()
    it("generates HTML like table-generate-source", function()
      eq(
        HEAD
          .. "  <tr>\n"
          .. html_cell(' colspan="2"', "0&nbsp;&nbsp;&nbsp;&nbsp;")
          .. "\n"
          .. html_cell(' rowspan="2"', "1&nbsp;<br />", "&nbsp;&nbsp;<br />", "&nbsp;&nbsp;")
          .. "\n  </tr>\n  <tr>\n"
          .. html_cell(' rowspan="2"', "2&nbsp;<br />", "&nbsp;&nbsp;<br />", "&nbsp;&nbsp;")
          .. "\n"
          .. html_cell("", "3&nbsp;")
          .. "\n  </tr>\n  <tr>\n"
          .. html_cell(' colspan="2"', "4&nbsp;&nbsp;&nbsp;&nbsp;")
          .. "\n  </tr>\n</table>\n",
        body("html", vim.list_extend({ "#+CAPTION: Spans", "#+NAME: tbl-spans" }, vim.deepcopy(SPANS)))
      )
      -- Cell text is not escaped; spaces become &nbsp;.
      eq(
        HEAD
          .. "  <tr>\n"
          .. html_cell("", "a&nbsp;<b>&nbsp;&&nbsp;<br />", "c\\d&nbsp;#%&nbsp;&nbsp;")
          .. "\n"
          .. html_cell("", "&nbsp;$x_1<br />", "&nbsp;{~^}")
          .. "\n  </tr>\n  <tr>\n"
          .. html_cell("", "long&nbsp;&nbsp;&nbsp;&nbsp;")
          .. "\n"
          .. html_cell("", "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;")
          .. "\n  </tr>\n</table>\n",
        body("html", {
          "  +--------+-----+",
          "  |a <b> & | $x_1|",
          "  |c\\d #%  | {~^}|",
          "  +========+=====+",
          "  |long    |     |",
          "  +--------+-----+",
        })
      )
    end)

    it("follows table.el's row assignment for staggered cells", function()
      eq(
        HEAD
          .. "  <tr>\n"
          .. html_cell(' rowspan="2"', "0&nbsp;<br />", "&nbsp;&nbsp;")
          .. "\n"
          .. html_cell("", "1&nbsp;")
          .. "\n"
          .. html_cell(' rowspan="2"', "2&nbsp;<br />", "&nbsp;&nbsp;")
          .. "\n  </tr>\n  <tr>\n"
          .. html_cell(' rowspan="2"', "3&nbsp;")
          .. "\n  </tr>\n  <tr>\n"
          .. html_cell(' rowspan="2"', "4&nbsp;<br />", "&nbsp;&nbsp;")
          .. "\n"
          .. html_cell(' rowspan="2"', "5&nbsp;<br />", "&nbsp;&nbsp;")
          .. "\n  </tr>\n  <tr>\n"
          .. html_cell("", "6&nbsp;")
          .. "\n  </tr>\n</table>\n",
        body("html", LADDER)
      )
    end)

    it("uses the same HTML in Markdown", function()
      ok(body("md", SPANS):find('<td colspan="2" align="left" valign="top">', 1, true))
    end)

    it("generates a LaTeX tabular like table-generate-source", function()
      eq(
        table.concat({
          "\\begin{table}[htbp]",
          "\\caption{\\label{tab:x}Spans}",
          "\\centering",
          "\\begin{tabular}{|l|l|l|}",
          "\\hline",
          "\\multicolumn{2}{|l|}{0} & 1 \\\\",
          "\\cline{1-2}",
          "2 & 3 & \\\\",
          "\\cline{2-3}",
          " & \\multicolumn{2}{l|}{4} \\\\",
          "\\hline",
          "\\end{tabular}",
          "\\end{table}",
          "",
        }, "\n"),
        (body("latex", vim.list_extend({ "#+CAPTION: Spans", "#+NAME: t" }, vim.deepcopy(SPANS))):gsub(
          "tab:org%x+",
          "tab:x"
        ))
      )
      eq(
        table.concat({
          "\\begin{center}",
          "\\begin{tabular}{|l|l|}",
          "\\hline",
          "a $<$b$>$ \\& & \\$x\\_1 \\\\",
          "c$\\backslash$d \\#\\% & \\{\\~\\^\\} \\\\",
          "\\hline",
          "long & \\\\",
          "\\hline",
          "\\end{tabular}",
          "\\end{center}",
          "",
        }, "\n"),
        body("latex", {
          "  +--------+-----+",
          "  |a <b> & | $x_1|",
          "  |c\\d #%  | {~^}|",
          "  +========+=====+",
          "  |long    |     |",
          "  +--------+-----+",
        })
      )
      eq(
        table.concat({
          "\\begin{center}",
          "\\begin{tabular}{|l|l|l|}",
          "\\hline",
          "0 & 1 & 2 \\\\",
          "\\cline{2-2}",
          "\\cline{1-1}",
          "\\cline{3-3}",
          "\\cline{2-2}",
          " & 6 & \\\\",
          "\\hline",
          "\\end{tabular}",
          "\\end{center}",
          "",
        }, "\n"),
        body("latex", LADDER)
      )
    end)

    it("keeps the table as text in ASCII, Org and Texinfo", function()
      local lines = { "#+OPTIONS: num:nil", "* H", "#+NAME: foo", "+---+----+", "|a  |bb@ |", "+---+----+" }
      eq("H\n=\n\n  +---+----+\n  |a  |bb@ |\n  +---+----+\n", body("ascii", lines))
      ok(body("org", lines):find("#+name: foo\n+---+----+\n|a  |bb@ |\n+---+----+", 1, true))
      local texinfo = "@anchor{foo}\n@verbatim\n+---+----+\n|a  |bb@ |\n+---+----+\n@end verbatim"
      ok(body("texinfo", lines):find(texinfo, 1, true))
    end)
  end)
end)
