local tbl = require("org.table")

describe("table", function()
  it("aligns with numeric right alignment and hlines", function()
    local buf = org_buffer({ "|name|qty|", "|-", "| apple | 3|", "|banana|12|" }, { 1, 1 })
    tbl.align()
    eq({
      "| name   | qty |",
      "|--------+-----|",
      "| apple  |   3 |",
      "| banana |  12 |",
    }, buf_lines(buf))
  end)

  it("honors alignment cookies and indentation", function()
    local buf = org_buffer({ "  | <r> | <c> |", "  | a | bb |", "  | ccc | d |" }, { 2, 3 })
    tbl.align()
    eq({ "  | <r> | <c> |", "  |   a | bb  |", "  | ccc |  d  |" }, buf_lines(buf))
  end)

  it("next_field moves and creates rows", function()
    local buf = org_buffer({ "| a | b |", "|---+---|", "| c | d |" }, { 1, 2 })
    tbl.next_field()
    eq({ 1, 6 }, vim.api.nvim_win_get_cursor(0))
    tbl.next_field()
    eq({ 3, 2 }, vim.api.nvim_win_get_cursor(0))
    vim.api.nvim_win_set_cursor(0, { 3, 6 })
    tbl.next_field()
    eq(4, #buf_lines(buf))
    eq("|   |   |", buf_lines(buf)[4])
    eq({ 4, 2 }, vim.api.nvim_win_get_cursor(0))
    tbl.prev_field()
    eq({ 3, 6 }, vim.api.nvim_win_get_cursor(0))
  end)

  it("next_row inserts before hline", function()
    local buf = org_buffer({ "| a | b |", "|---+---|", "| c | d |" }, { 1, 6 })
    tbl.next_row()
    eq({ "| a | b |", "|   |   |", "|---+---|", "| c | d |" }, buf_lines(buf))
    eq({ 2, 6 }, vim.api.nvim_win_get_cursor(0))
  end)

  it("returns false outside tables", function()
    org_buffer({ "text" }, { 1, 0 })
    eq(false, tbl.next_field())
    eq(false, tbl.align())
  end)

  it("inserts/deletes/moves rows and columns", function()
    local buf = org_buffer({ "| a | b |", "| c | d |" }, { 1, 2 })
    tbl.insert_column()
    eq({ "|   | a | b |", "|   | c | d |" }, buf_lines(buf))
    tbl.delete_column()
    eq({ "| a | b |", "| c | d |" }, buf_lines(buf))
    tbl.move_column(1)
    eq({ "| b | a |", "| d | c |" }, buf_lines(buf))
    tbl.move_row(1)
    eq({ "| d | c |", "| b | a |" }, buf_lines(buf))
    tbl.insert_row(true)
    eq({ "| d | c |", "|   |   |", "| b | a |" }, buf_lines(buf))
    tbl.delete_row()
    eq({ "| d | c |", "| b | a |" }, buf_lines(buf))
    tbl.insert_hline()
    eq({ "| d | c |", "| b | a |", "|---+---|" }, buf_lines(buf))
  end)

  it("converts csv", function()
    eq({ "| a | b c |", "| 1 |  22 |" }, tbl.convert_lines({ 'a,"b c"', "1,22" }))
    eq({ "| x | y |", "| 1 | 2 |" }, tbl.convert_lines({ "x  y", "1 2" }))
  end)

  it("named tables", function()
    local buf = org_buffer({ "#+NAME: data", "| h1 | h2 |", "|----+----|", "| 1 | 2 |", "| 3 | 4 |" })
    eq({ { "1", "2" }, { "3", "4" } }, tbl.get_named_table(buf, "data"))
    eq({ { "h1", "h2" }, { "1", "2" }, { "3", "4" } }, tbl.get_named_table(buf, "data", true))
  end)
end)
