local elisp = require("org.table.elisp")

local function run(src)
  return elisp.to_string(elisp.eval(src))
end

describe("elisp formulas", function()
  it("arithmetic keeps integers and floats apart", function()
    eq(3, elisp.eval("(+ 1 2)"))
    eq(3, elisp.eval("(/ 7 2)"))
    eq(-3, elisp.eval("(/ -7 2)"))
    eq("3.5", run("(/ 7 2.0)"))
    eq("3.0", run("(* 1.5 2)"))
    eq("2.5", run("2.5"))
    eq("1000.0", run("1e3"))
    eq(-1, elisp.eval("(- 1 2)"))
    eq(-5, elisp.eval("(- 5)"))
    eq(1, elisp.eval("(% 7 3)"))
    eq(2, elisp.eval("(mod -7 3)"))
    eq(8, elisp.eval("(expt 2 3)"))
    eq("2.0", run("(sqrt 4)"))
    eq(2, elisp.eval("(round 2.5)"))
    eq(3, elisp.eval("(floor 7 2)"))
    eq(4, elisp.eval("(ceiling 3.2)"))
    eq("3.0", run("(max 1 3.0 2)"))
    eq(6, elisp.eval("(1+ 5)"))
    eq(true, elisp.eval("(< 1 2 3)"))
    eq(nil, elisp.eval("(= 1 2)"))
    ok(elisp.is_float(elisp.eval("(float 3)")))
    eq(3, elisp.tonumber(elisp.eval("(float 3)")))
  end)

  it("strings", function()
    eq("a-b", elisp.eval('(concat "a" "-" "b")'))
    eq(4, elisp.eval('(length "abcd")'))
    eq("X", elisp.eval('(upcase "x")'))
    eq("Hello World", elisp.eval('(capitalize "hello wORLD")'))
    eq("bc", elisp.eval('(substring "abcd" 1 3)'))
    eq("cd", elisp.eval('(substring "abcd" -2)'))
    eq(42, elisp.eval('(string-to-number "42")'))
    eq("3.5", run('(string-to-number "3.5")'))
    eq(0, elisp.eval('(string-to-number "abc")'))
    eq("42", elisp.eval("(number-to-string 42)"))
    eq("3.14", elisp.eval('(format "%.2f" 3.14159)'))
    eq("x=3 y=2.5 100%", elisp.eval('(format "x=%d y=%s 100%%" 3.7 2.5)'))
    eq("a,b", elisp.eval([[(mapconcat 'identity '("a" "b") ",")]]))
    eq("a b", elisp.eval([[(string-join (split-string "  a   b ") " ")]]))
    eq("(a b c)", run([[(split-string "a, b,c" "[, ]+")]]))
    eq("ab", elisp.eval('(string-trim "  ab ")'))
    eq(true, elisp.eval('(string= "a" "a")'))
    eq('say "hi"\n', elisp.eval([["say \"hi\"\n"]]))
  end)

  it("control flow and binding", function()
    eq("small", elisp.eval('(if (> 3 5) "big" "small")'))
    eq(nil, elisp.eval('(when nil "x")'))
    eq("b", elisp.eval('(cond ((= 1 2) "a") ((= 1 1) "b") (t "c"))'))
    eq(3, elisp.eval("(and 1 2 3)"))
    eq(2, elisp.eval("(or nil 2)"))
    eq(true, elisp.eval("(not nil)"))
    eq(4, elisp.eval("(let ((x 2)) (* x x))"))
    eq(6, elisp.eval("(let* ((x 2) (y (* x 3))) y)"))
    eq(3, elisp.eval("(progn 1 2 3)"))
  end)

  it("lists and higher-order functions", function()
    eq(6, elisp.eval("(apply '+ '(1 2 3))"))
    eq(10, elisp.eval("(apply '+ 1 2 '(3 4))"))
    eq("(2 4)", run("(mapcar (lambda (x) (* x 2)) '(1 2))"))
    eq("(2 4)", run("(mapcar #'1+ '(1 3))"))
    eq(5, elisp.eval("(funcall (lambda (a &optional b) (+ a (or b 0))) 5)"))
    eq("(1 2 3)", run("(list 1 2 3)"))
    eq("(2 3)", run("(cdr '(1 2 3))"))
    eq(1, elisp.eval("(car '(1 2 3))"))
    eq(3, elisp.eval("(nth 2 '(1 2 3))"))
    eq("(0 1 2)", run("(cons 0 '(1 2))"))
    eq("(1 . 2)", run("(cons 1 2)"))
    eq("(1 2 3 4)", run("(append '(1 2) '(3) '(4))"))
    eq("(3 2 1)", run("(reverse '(1 2 3))"))
    eq(3, elisp.eval("(length '(a b c))"))
    eq("(a b)", run([['("a" "b")]]))
    eq("(1 2 3)", run("(number-sequence 1 3)"))
    eq(true, elisp.eval("(equal '(1 (2)) (list 1 (list 2)))"))
  end)

  it("to_string", function()
    eq("", elisp.to_string(nil))
    eq("t", elisp.to_string(true))
    eq("abc", elisp.to_string("abc"))
    eq("12", elisp.to_string(12))
    eq("2.5", elisp.to_string(2.5))
    eq("3.0", elisp.to_string(elisp.float(3)))
    eq("0.1", elisp.to_string(elisp.float(0.1)))
    eq("1e+21", elisp.to_string(elisp.float(1e21)))
    eq("(1 nil t)", run("(list 1 nil t)"))
  end)

  it("errors", function()
    ok(not pcall(elisp.eval, "(+ 1"))
    ok(not pcall(elisp.eval, "(no-such-fn 1)"))
    ok(not pcall(elisp.eval, "(/ 1 0)"))
    ok(not pcall(elisp.eval, '(+ 1 "a")'))
    ok(not pcall(elisp.eval, "unbound-var"))
  end)

  it("looks_like", function()
    ok(elisp.looks_like("(+ 1 2)"))
    ok(elisp.looks_like('(concat "a" "b")'))
    ok(elisp.looks_like('(if (> 3 5) "big" "small")'))
    ok(elisp.looks_like("  ( apply '+ '(1 2))"))
    ok(elisp.looks_like("(list)"))
    ok(not elisp.looks_like('(string.upper("x" .. "2"))'))
    ok(not elisp.looks_like("(1 + 2)"))
    ok(not elisp.looks_like("(math.floor(2.5))"))
    ok(not elisp.looks_like('("a" .. "b")'))
    ok(not elisp.looks_like("(max(1, 2))"))
    ok(not elisp.looks_like("1 + 2"))
  end)
end)
