---@mod org.lint.data org-lint: the Emacs data the parser and checkers use

---------------------------------------------------------------------------
-- Emacs data
---------------------------------------------------------------------------

local AFFILIATED = {
  CAPTION = true,
  DATA = true,
  HEADER = true,
  HEADERS = true,
  LABEL = true,
  NAME = true,
  PLOT = true,
  RESNAME = true,
  RESULT = true,
  RESULTS = true,
  SOURCE = true,
  SRCNAME = true,
  TBLNAME = true,
}
local TRANSLATION = {
  DATA = "NAME",
  LABEL = "NAME",
  RESNAME = "NAME",
  SOURCE = "NAME",
  SRCNAME = "NAME",
  TBLNAME = "NAME",
  RESULT = "RESULTS",
  HEADERS = "HEADER",
}

-- `org-babel-header-arg-names`
local HEADER_ARG_NAMES = {
  "cache",
  "cmdline",
  "colnames",
  "comments",
  "dir",
  "eval",
  "exports",
  "epilogue",
  "file",
  "file-desc",
  "file-ext",
  "file-mode",
  "hlines",
  "mkdirp",
  "no-expand",
  "noeval",
  "noweb",
  "noweb-ref",
  "noweb-sep",
  "noweb-prefix",
  "output-dir",
  "padline",
  "post",
  "prologue",
  "results",
  "rownames",
  "sep",
  "session",
  "shebang",
  "tangle",
  "tangle-mode",
  "var",
  "wrap",
}

-- `org-babel-common-header-args-w-values`: name -> "any" | nil | list of groups.
local ANY = "any"
local COMMON_HEADER_VALUES = {
  { "cache", { { "no", "yes" } } },
  { "cmdline", ANY },
  { "colnames", { { "nil", "no", "yes" } } },
  { "comments", { { "no", "link", "yes", "org", "both", "noweb" } } },
  { "dir", ANY },
  { "eval", { { "yes", "no", "no-export", "strip-export", "never-export", "eval", "never", "query" } } },
  { "exports", { { "code", "results", "both", "none" } } },
  { "epilogue", ANY },
  { "file", ANY },
  { "file-desc", ANY },
  { "file-ext", ANY },
  { "file-mode", { { 493, 365, 292, ANY } } },
  { "hlines", { { "no", "yes" } } },
  { "mkdirp", { { "yes", "no" } } },
  { "no-expand", false },
  { "noeval", false },
  { "noweb", { { "yes", "no", "tangle", "strip-tangle", "no-export", "strip-export" } } },
  { "noweb-ref", ANY },
  { "noweb-sep", ANY },
  { "noweb-prefix", { { "no", "yes" } } },
  { "output-dir", ANY },
  { "padline", { { "yes", "no" } } },
  { "post", ANY },
  { "prologue", ANY },
  {
    "results",
    {
      { "file", "list", "vector", "table", "scalar", "verbatim" },
      { "raw", "html", "latex", "org", "code", "pp", "drawer", "link", "graphics" },
      { "replace", "silent", "none", "discard", "append", "prepend" },
      { "output", "value" },
    },
  },
  { "rownames", { { "no", "yes" } } },
  { "sep", ANY },
  { "session", ANY },
  { "shebang", ANY },
  { "tangle", { { "tangle", "yes", "no", ANY } } },
  { "tangle-mode", { { 493, 365, 292, ANY } } },
  { "var", ANY },
  { "wrap", ANY },
}

-- `org-babel-header-args:LANG` of the languages shipped with Org.
local LANG_HEADER_ARGS = {
  ["emacs-lisp"] = { { "lexical", ANY } },
  python = { { "return", ANY }, { "python", ANY }, { "async", { { "yes", "no" } } } },
  shell = { { "async", { { "yes", "no" } } } },
  sh = { { "async", { { "yes", "no" } } } },
  bash = { { "async", { { "yes", "no" } } } },
  zsh = { { "async", { { "yes", "no" } } } },
  C = {
    { "includes", ANY },
    { "defines", ANY },
    { "main", ANY },
    { "flags", ANY },
    { "cmdline", ANY },
    { "libs", ANY },
  },
  ["C++"] = {
    { "namespaces", ANY },
    { "includes", ANY },
    { "defines", ANY },
    { "main", ANY },
    { "flags", ANY },
    { "cmdline", ANY },
    { "libs", ANY },
  },
  sqlite = {
    { "db", ANY },
    { "header", ANY },
    { "echo", ANY },
    { "bail", ANY },
    { "csv", ANY },
    { "column", ANY },
    { "html", ANY },
    { "line", ANY },
    { "list", ANY },
    { "separator", ANY },
    { "nullvalue", ANY },
    { "readonly", { { "yes", "no" } } },
  },
  java = {
    { "dir", ANY },
    { "classname", ANY },
    { "imports", ANY },
    { "cmpflag", ANY },
    { "cmdline", ANY },
    { "cmdarg", ANY },
  },
  haskell = { { "compile", ANY } },
  clojure = {
    { "ns", ANY },
    { "package", ANY },
    { "backend", { { "inf-clojure", "cider", "slime", "babashka", "nbb" } } },
  },
  lisp = { { "package", ANY } },
  scheme = { { "host", ANY }, { "port", ANY } },
}
-- Languages whose header arguments are accepted in #+CALL lines
-- (`org-babel-load-languages`).
local LOADED_LANGUAGES = { "emacs-lisp" }

-- Items of `org-export-options-alist` and the registered backends.
local OPTIONS_ITEMS = {
  "H",
  "\\n",
  "num",
  "timestamp",
  "arch",
  "author",
  "expand-links",
  "broken-links",
  "c",
  "creator",
  "date",
  "d",
  "email",
  "*",
  "e",
  ":",
  "f",
  "inline",
  "tex",
  "p",
  "pri",
  "prop",
  "'",
  "-",
  "stat",
  "^",
  "toc",
  "|",
  "tags",
  "tasks",
  "<",
  "title",
  "todo",
  "latex-use-sans",
  "html5-fancy",
  "html-link-use-abs-url",
  "html-postamble",
  "html-preamble",
  "html-style",
  "html-scripts",
  "html-self-link-headlines",
}

-- Export keywords of `org-export-options-alist`.
local COMMON_OPTION_KEYWORDS = {
  "CITE_EXPORT",
  "CREATOR",
  "EXCLUDE_TAGS",
  "SELECT_TAGS",
  "LANGUAGE",
  "EMAIL",
  "AUTHOR",
  "DATE",
  "TITLE",
}
-- Export keywords of the registered backends: keyword -> backends.
local BACKEND_OPTION_KEYWORDS = {
  { "LATEX_CLASS", { "latex", "beamer" } },
  { "COLUMNS", { "beamer" } },
  { "BEAMER_THEME", { "beamer" } },
  { "BEAMER_COLOR_THEME", { "beamer" } },
  { "BEAMER_FONT_THEME", { "beamer" } },
  { "BEAMER_INNER_THEME", { "beamer" } },
  { "BEAMER_OUTER_THEME", { "beamer" } },
  { "BEAMER_HEADER", { "beamer" } },
  { "ODT_STYLES_FILE", { "odt" } },
  { "DESCRIPTION", { "html", "latex", "odt" } },
  { "KEYWORDS", { "html", "latex", "odt" } },
  { "SUBTITLE", { "ascii", "html", "latex", "odt" } },
  { "LATEX_HEADER", { "html", "latex", "odt" } },
  { "LATEX_CLASS_OPTIONS", { "latex" } },
  { "LATEX_HEADER_EXTRA", { "latex" } },
  { "LATEX_CLASS_PRE", { "latex" } },
  { "LATEX_FOOTNOTE_COMMAND", { "latex" } },
  { "LATEX_ENGRAVED_THEME", { "latex" } },
  { "LATEX_COMPILER", { "latex" } },
  { "DATE", { "latex" } },
  { "ICALENDAR_EXCLUDE_TAGS", { "icalendar" } },
  { "ICAL-TTL", { "icalendar" } },
  { "HTML_DOCTYPE", { "html" } },
  { "HTML_CONTAINER", { "html" } },
  { "HTML_CONTENT_CLASS", { "html" } },
  { "HTML_LINK_HOME", { "html" } },
  { "HTML_LINK_UP", { "html" } },
  { "HTML_MATHJAX", { "html" } },
  { "HTML_EQUATION_REFERENCE_FORMAT", { "html" } },
  { "HTML_HEAD", { "html" } },
  { "HTML_HEAD_EXTRA", { "html" } },
  { "INFOJS_OPT", { "html" } },
  { "CREATOR", { "html" } },
}

-- `org-default-properties`
local DEFAULT_PROPERTIES = {
  "ARCHIVE",
  "CATEGORY",
  "SUMMARY",
  "DESCRIPTION",
  "CUSTOM_ID",
  "LOCATION",
  "LOGGING",
  "COLUMNS",
  "VISIBILITY",
  "TABLE_EXPORT_FORMAT",
  "TABLE_EXPORT_FILE",
  "EXPORT_OPTIONS",
  "EXPORT_TEXT",
  "EXPORT_FILE_NAME",
  "EXPORT_TITLE",
  "EXPORT_AUTHOR",
  "EXPORT_DATE",
  "UNNUMBERED",
  "ORDERED",
  "NOBLOCKING",
  "COOKIE_DATA",
  "LOG_INTO_DRAWER",
  "REPEAT_TO_STATE",
  "CLOCK_MODELINE_TOTAL",
  "STYLE",
  "HTML_CONTAINER_CLASS",
  "ORG-IMAGE-ACTUAL-WIDTH",
}

-- `org-special-properties`
local SPECIAL_PROPERTIES = {
  "ALLTAGS",
  "BLOCKED",
  "CLOCKSUM",
  "CLOCKSUM_T",
  "CLOSED",
  "DEADLINE",
  "FILE",
  "ITEM",
  "PRIORITY",
  "SCHEDULED",
  "TAGS",
  "TIMESTAMP",
  "TIMESTAMP_IA",
  "TODO",
}

-- Link types known to Org (`org-link-types`).
local LINK_TYPES = {
  "eww",
  "rmail",
  "mhe",
  "irc",
  "info",
  "gnus",
  "docview",
  "bibtex",
  "bbdb",
  "w3m",
  "doi",
  "attachment",
  "id",
  "file+sys",
  "file+emacs",
  "shell",
  "news",
  "mailto",
  "https",
  "http",
  "ftp",
  "shortdoc",
  "help",
  "file",
  "elisp",
}

-- Citation processors (`org-cite-try-load-processor` finds them).
local CITE_PROCESSORS = { basic = true, biblatex = true, bibtex = true, csl = true, natbib = true }

local BEAMER_FRAME_ENVIRONMENT = "orgframe"

return {
  AFFILIATED = AFFILIATED,
  TRANSLATION = TRANSLATION,
  HEADER_ARG_NAMES = HEADER_ARG_NAMES,
  ANY = ANY,
  COMMON_HEADER_VALUES = COMMON_HEADER_VALUES,
  LANG_HEADER_ARGS = LANG_HEADER_ARGS,
  LOADED_LANGUAGES = LOADED_LANGUAGES,
  OPTIONS_ITEMS = OPTIONS_ITEMS,
  COMMON_OPTION_KEYWORDS = COMMON_OPTION_KEYWORDS,
  BACKEND_OPTION_KEYWORDS = BACKEND_OPTION_KEYWORDS,
  DEFAULT_PROPERTIES = DEFAULT_PROPERTIES,
  SPECIAL_PROPERTIES = SPECIAL_PROPERTIES,
  LINK_TYPES = LINK_TYPES,
  CITE_PROCESSORS = CITE_PROCESSORS,
  BEAMER_FRAME_ENVIRONMENT = BEAMER_FRAME_ENVIRONMENT,
}
