-- Generated from Emacs Org 9.8.10 ox-latex.el / org.el. Do not edit.
local M = {}
-- { options, package, snippet, compilers }
M.default_packages = { { "", "amsmath", true, { "lualatex", "xelatex" } }, { "", "fontspec", true, { "lualatex", "xelatex" } }, { "AUTO", "inputenc", true, { "pdflatex" } }, { "T1", "fontenc", true, { "pdflatex" } }, { "", "graphicx", true }, { "", "longtable", false }, { "", "wrapfig", false }, { "", "rotating", false }, { "normalem", "ulem", true }, { "", "amsmath", true, { "pdflatex" } }, { "", "amssymb", true, { "pdflatex" } }, { "", "capt-of", false }, { "", "hyperref", false } }
-- { name, header, sections... } ; a section is { numbered, unnumbered } or { open, close[, open*, close*] }
M.classes = {
  { "beamer", "\\documentclass[presentation]{beamer}", { "\\section{%s}", "\\section*{%s}" }, { "\\subsection{%s}", "\\subsection*{%s}" }, { "\\subsubsection{%s}", "\\subsubsection*{%s}" } },
  { "article", "\\documentclass[11pt]{article}", { "\\section{%s}", "\\section*{%s}" }, { "\\subsection{%s}", "\\subsection*{%s}" }, { "\\subsubsection{%s}", "\\subsubsection*{%s}" }, { "\\paragraph{%s}", "\\paragraph*{%s}" }, { "\\subparagraph{%s}", "\\subparagraph*{%s}" } },
  { "report", "\\documentclass[11pt]{report}", { "\\part{%s}", "\\part*{%s}" }, { "\\chapter{%s}", "\\chapter*{%s}" }, { "\\section{%s}", "\\section*{%s}" }, { "\\subsection{%s}", "\\subsection*{%s}" }, { "\\subsubsection{%s}", "\\subsubsection*{%s}" } },
  { "book", "\\documentclass[11pt]{book}", { "\\part{%s}", "\\part*{%s}" }, { "\\chapter{%s}", "\\chapter*{%s}" }, { "\\section{%s}", "\\section*{%s}" }, { "\\subsection{%s}", "\\subsection*{%s}" }, { "\\subsubsection{%s}", "\\subsubsection*{%s}" } },
}
M.languages = {
  ["af"] = { ["babel"] = "afrikaans", ["polyglossia"] = "afrikaans", ["lang_name"] = "Afrikaans", ["script"] = "latin", ["script_tag"] = "latn", },
  ["am"] = { ["babel_ini_only"] = "amharic", ["polyglossia"] = "amharic", ["lang_name"] = "Amharic", ["script"] = "ethiopic", ["script_tag"] = "ethi", },
  ["ar"] = { ["babel_ini_only"] = "arabic", ["polyglossia"] = "arabic", ["lang_name"] = "Arabic", ["script"] = "arabic", ["script_tag"] = "arab", },
  ["ast"] = { ["babel_ini_only"] = "asturian", ["polyglossia"] = "asturian", ["lang_name"] = "Asturian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["bg"] = { ["babel"] = "bulgarian", ["polyglossia"] = "bulgarian", ["lang_name"] = "Bulgarian", ["script"] = "cyrillic", ["script_tag"] = "cyrl", },
  ["bn"] = { ["babel_ini_only"] = "bengali", ["polyglossia"] = "bengali", ["lang_name"] = "Bengali", ["script"] = "bengali", ["script_tag:"] = "beng", },
  ["bo"] = { ["babel_ini_only"] = "tibetan", ["polyglossia"] = "tibetan", ["lang_name"] = "Tibetan", ["script"] = "tibetan", ["script_tag"] = "tib", },
  ["br"] = { ["babel"] = "breton", ["polyglossia"] = "breton", ["lang_name"] = "Breton", ["script"] = "latin", ["script_tag"] = "latn", },
  ["ca"] = { ["babel"] = "catalan", ["polyglossia"] = "catalan", ["lang_name"] = "Catalan", ["script"] = "latin", ["script_tag"] = "latn", },
  ["cop"] = { ["babel_ini_only"] = "coptic", ["polyglossia"] = "coptic", ["lang_name"] = "Coptic", ["script"] = "coptic", ["script_tag"] = "copt", },
  ["cs"] = { ["babel"] = "czech", ["polyglossia"] = "czech", ["lang_name"] = "Czech", ["script"] = "latin", ["script_tag"] = "latn", },
  ["cy"] = { ["babel"] = "welsh", ["polyglossia"] = "welsh", ["lang_name"] = "Welsh", ["script"] = "latin", ["script_tag"] = "latn", },
  ["da"] = { ["babel"] = "danish", ["polyglossia"] = "danish", ["lang_name"] = "Danish", ["script"] = "latin", ["script_tag"] = "latn", },
  ["de"] = { ["babel"] = "ngerman", ["babel_ini_alt"] = "german", ["polyglossia"] = "german", ["polyglossia_variant"] = "german", ["lang_name"] = "German", ["script"] = "latin", ["script_tag"] = "latn", },
  ["de-de"] = { ["babel"] = "ngerman", ["babel_ini_alt"] = "german", ["polyglossia"] = "german", ["polyglossia_variant"] = "german", ["lang_name"] = "German", ["script"] = "latin", ["script_tag"] = "latn", },
  ["de-at"] = { ["babel"] = "naustrian", ["babel_ini_alt"] = "german-austria", ["polyglossia"] = "german", ["polyglossia_variant"] = "austrian", ["lang_name"] = "German", ["script"] = "latin", ["script_tag"] = "latn", },
  ["dsb"] = { ["babel"] = "lowersorbian", ["babel_ini_alt"] = "lsorbian", ["polyglossia"] = "sorbian", ["polyglossia_variant"] = "lower", ["lang_name"] = "Lower Sorbian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["dv"] = { ["polyglossia"] = "divehi", ["lang_name"] = "Dhivehi", ["script"] = "latin", ["script_tag"] = "latn", },
  ["el"] = { ["babel"] = "greek", ["polyglossia"] = "greek", ["lang_name"] = "Greek", ["script"] = "greek", ["script_tag"] = "grek", },
  ["el-polyton"] = { ["babel"] = "polutonikogreek", ["babel_ini_alt"] = "polytonicgreek", ["polyglossia"] = "greek", ["polyglossia_variant"] = "polytonic", ["lang_name"] = "Polytonic Greek", ["script"] = "greek", ["script_tag"] = "grek", },
  ["grc"] = { ["babel"] = "greek.ancient", ["babel_ini_alt"] = "ancientgreek", ["polyglossia"] = "greek", ["polyglossia_variant"] = "ancient", ["lang_name"] = "Ancient Greek", ["script"] = "greek", ["script_tag"] = "grek", },
  ["en"] = { ["babel"] = "english", ["polyglossia"] = "english", ["polyglossia_variant"] = "usmax", ["lang_name"] = "English", ["script"] = "latin", ["script_tag"] = "latn", },
  ["en-au"] = { ["babel"] = "australian", ["polyglossia"] = "english", ["polyglossia_variant"] = "australian", ["lang_name"] = "English", ["script"] = "latin", ["script_tag"] = "latn", },
  ["en-ca"] = { ["babel"] = "canadian", ["polyglossia"] = "english", ["polyglossia_variant"] = "canadian", ["lang_name"] = "English", ["script"] = "latin", ["script_tag"] = "latn", },
  ["en-gb"] = { ["babel"] = "british", ["polyglossia"] = "english", ["polyglossia_variant"] = "uk", ["lang_name"] = "English", ["script"] = "latin", ["script_tag"] = "latn", },
  ["en-nz"] = { ["babel"] = "newzealand", ["polyglossia"] = "english", ["polyglossia_variant"] = "newzealand", ["lang_name"] = "English", ["script"] = "latin", ["script_tag"] = "latn", },
  ["en-us"] = { ["babel"] = "american", ["polyglossia"] = "english", ["polyglossia_variant"] = "usmax", ["lang_name"] = "English", ["script"] = "latin", ["script_tag"] = "latn", },
  ["eo"] = { ["babel"] = "esperanto", ["polyglossia"] = "esperanto", ["lang_name"] = "Esperanto", ["script"] = "latin", ["script_tag"] = "latn", },
  ["es"] = { ["babel"] = "spanish", ["polyglossia"] = "spanish", ["lang_name"] = "Spanish", ["script"] = "latin", ["script_tag"] = "latn", },
  ["es-mx"] = { ["babel"] = "spanishmx", ["polyglossia"] = "spanish", ["polyglossia_variant"] = "mexican", ["lang_name"] = "Spanish", ["script"] = "latin", ["script_tag"] = "latn", },
  ["et"] = { ["babel"] = "estonian", ["polyglossia"] = "estonian", ["lang_name"] = "Estonian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["eu"] = { ["babel"] = "basque", ["polyglossia"] = "basque", ["lang_name"] = "Basque", ["script"] = "latin", ["script_tag"] = "latn", },
  ["fa"] = { ["babel"] = "persian", ["polyglossia"] = "persian", ["lang_name"] = "Persian", ["script"] = "arabic", ["script_tag"] = "arab", },
  ["fi"] = { ["babel"] = "finnish", ["polyglossia"] = "finnish", ["lang_name"] = "Finnish", ["script"] = "latin", ["script_tag"] = "latn", },
  ["fr"] = { ["babel"] = "french", ["polyglossia"] = "french", ["lang_name"] = "French", ["script"] = "latin", ["script_tag"] = "latn", },
  ["fr-ca"] = { ["babel"] = "canadien", ["babel_ini_alt"] = "canadian", ["polyglossia"] = "french", ["polyglossia_variant"] = "canadian", ["lang_name"] = "French", ["script"] = "latin", ["script_tag"] = "latn", },
  ["fur"] = { ["babel"] = "friulian", ["polyglossia"] = "friulian", ["lang_name"] = "Friulian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["ga"] = { ["babel"] = "irish", ["polyglossia"] = "gaelic", ["polyglossia_variant"] = "irish", ["lang_name"] = "Irish Gaelic", ["script"] = "latin", ["script_tag"] = "latn", },
  ["gd"] = { ["babel"] = "scottish", ["polyglossia"] = "gaelic", ["polyglossia_variant"] = "scottish", ["lang_name"] = "Scottish Gaelic", ["script"] = "latin", ["script_tag"] = "latn", },
  ["gl"] = { ["babel"] = "galician", ["polyglossia"] = "galician", ["lang_name"] = "Galician", ["script"] = "latin", ["script_tag"] = "latn", },
  ["he"] = { ["babel"] = "hebrew", ["polyglossia"] = "hebrew", ["lang_name"] = "Hebrew", ["script"] = "hebrew", ["script_tag"] = "hebr", },
  ["hi"] = { ["babel"] = "hindi", ["polyglossia"] = "hindi", ["lang_name"] = "Hindi", ["script"] = "devanagari", ["script_tag"] = "deva", },
  ["hr"] = { ["babel"] = "croatian", ["polyglossia"] = "croatian", ["lang_name"] = "Croatian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["hsb"] = { ["babel"] = "uppersorbian", ["polyglossia"] = "sorbian", ["polyglossia_variant"] = "upper", ["lang_name"] = "Upper Sorbian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["hu"] = { ["babel"] = "magyar", ["polyglossia"] = "magyar", ["lang_name"] = "Magyar", ["script"] = "latin", ["script_tag"] = "latn", },
  ["hy"] = { ["babel_ini_only"] = "armenian", ["polyglossia"] = "armenian", ["lang_name"] = "Armenian", ["script"] = "armenian", ["script_tag"] = "armn", },
  ["ia"] = { ["babel"] = "interlingua", ["polyglossia"] = "interlingua", ["lang_name"] = "Interlingua", ["script"] = "latin", ["script_tag"] = "latn", },
  ["id"] = { ["babel"] = "indonesian", ["polyglossia"] = "malay", ["polyglossia_variant"] = "indonesian", ["lang_name"] = "Indonesian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["is"] = { ["babel"] = "icelandic", ["polyglossia"] = "icelandic", ["lang_name"] = "Icelandic", ["script"] = "latin", ["script_tag"] = "latn", },
  ["it"] = { ["babel"] = "italian", ["polyglossia"] = "italian", ["lang_name"] = "Italian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["kn"] = { ["babel_ini_only"] = "kannada", ["polyglossia"] = "kannada", ["lang_name"] = "Kannada", ["script"] = "kannada", ["script_tag"] = "knda", },
  ["la"] = { ["babel"] = "latin", ["polyglossia"] = "latin", ["lang_name"] = "Latin", ["script"] = "latin", ["script_tag"] = "latn", },
  ["la-classic"] = { ["babel"] = "classiclatin", ["polyglossia"] = "latin", ["polyglossia_variant"] = "classic", ["lang_name"] = "Classic Latin", ["script"] = "latin", ["script_tag"] = "latn", },
  ["la-medieval"] = { ["babel"] = "medievallatin", ["polyglossia"] = "latin", ["polyglossia_variant"] = "medieval", ["lang_name"] = "Medieval Latin", ["script"] = "latin", ["script_tag"] = "latn", },
  ["la-ecclesiastic"] = { ["babel"] = "ecclesiasticlatin", ["polyglossia"] = "latin", ["polyglossia_variant"] = "ecclesiastic", ["lang_name"] = "Ecclesiastic Latin", ["script"] = "latin", ["script_tag"] = "latn", },
  ["lo"] = { ["babel_ini_only"] = "lao", ["polyglossia"] = "lao", ["lang_name"] = "Lao", ["script"] = "lao", ["script_tag"] = "lao", },
  ["lt"] = { ["babel"] = "lithuanian", ["polyglossia"] = "lithuanian", ["lang_name"] = "Lithuanian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["lv"] = { ["babel"] = "latvian", ["polyglossia"] = "latvian", ["lang_name"] = "Latvian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["ml"] = { ["babel_ini_only"] = "malayalam", ["polyglossia"] = "malayalam", ["lang_name"] = "Malayalam", ["script"] = "malayalam", ["script_tag"] = "mlym", },
  ["mr"] = { ["babel_ini_only"] = "marathi", ["polyglossia"] = "marathi", ["lang_name"] = "Marathi", ["script"] = "devanagari", ["script_tag"] = "deva", },
  ["ms"] = { ["babel"] = "malay", ["polyglossia"] = "malay", ["polyglossia_variant"] = "malaysian", ["lang_name"] = "Malay", ["script"] = "latin", ["script_tag"] = "latn", },
  ["nb"] = { ["babel"] = "norsk", ["polyglossia"] = "norwegian", ["polyglossia_variant"] = "bokmal", ["lang_name"] = "Norwegian Bokmål", ["script"] = "latin", ["script_tag"] = "latn", },
  ["nl"] = { ["babel"] = "dutch", ["polyglossia"] = "dutch", ["lang_name"] = "Dutch", ["script"] = "latin", ["script_tag"] = "latn", },
  ["nn"] = { ["babel"] = "nynorsk", ["polyglossia"] = "norwegian", ["polyglossia_variant"] = "nynorsk", ["lang_name"] = "Norwegian Nynorsk", ["script"] = "latin", ["script_tag"] = "latn", },
  ["no"] = { ["babel"] = "norsk", ["polyglossia"] = "norsk", ["lang_name"] = "Norwegian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["oc"] = { ["babel"] = "occitan", ["polyglossia"] = "occitan", ["lang_name"] = "Occitan", ["script"] = "latin", ["script_tag"] = "latn", },
  ["pl"] = { ["babel"] = "polish", ["polyglossia"] = "polish", ["lang_name"] = "Polish", ["script"] = "latin", ["script_tag"] = "latn", },
  ["pms"] = { ["babel"] = "piedmontese", ["polyglossia"] = "piedmontese", ["lang_name"] = "Piedmontese", ["script"] = "latin", ["script_tag"] = "latn", },
  ["pt"] = { ["babel"] = "portuges", ["polyglossia"] = "portuges", ["lang_name"] = "Portuges", ["script"] = "latin", ["script_tag"] = "latn", },
  ["pt-br"] = { ["babel"] = "brazilian", ["polyglossia"] = "brazilian", ["lang_name"] = "Portuges", ["script"] = "latin", ["script_tag"] = "latn", },
  ["rm"] = { ["babel_ini_only"] = "romansh", ["polyglossia"] = "romansh", ["lang_name"] = "Romansh", ["script"] = "latin", ["script_tag"] = "latn", },
  ["ro"] = { ["babel"] = "romanian", ["polyglossia"] = "romanian", ["lang_name"] = "Romanian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["ru"] = { ["babel"] = "russian", ["polyglossia"] = "russian", ["lang_name"] = "Russian", ["script"] = "cyrillic", ["script_tag"] = "cyrl", },
  ["sa"] = { ["babel_ini_only"] = "sanskrit", ["polyglossia"] = "sanskrit", ["lang_name"] = "Sanskrit", ["script"] = "devanagari", ["script_tag"] = "deva", },
  ["sk"] = { ["babel"] = "slovak", ["polyglossia"] = "slovak", ["lang_name"] = "Slovak", ["script"] = "latin", ["script_tag"] = "latn", },
  ["sl"] = { ["babel"] = "slovene", ["polyglossia"] = "slovene", ["lang_name"] = "Slovene", ["script"] = "latin", ["script_tag"] = "latn", },
  ["sq"] = { ["babel"] = "albanian", ["polyglossia"] = "albanian", ["lang_name"] = "Albanian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["sr"] = { ["babel"] = "serbian", ["polyglossia"] = "serbian", ["lang_name"] = "Serbian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["sr-cyrl"] = { ["babel_ini_only"] = "serbian-cyrl", ["polyglossia"] = "serbian", ["lang_name"] = "Serbian", ["script"] = "cyrillic", ["script_tag"] = "cyrl", },
  ["sr-latn"] = { ["babel_ini_only"] = "serbian-latin", ["polyglossia"] = "serbian", ["lang_name"] = "Serbian", ["script"] = "latin", ["script_tag"] = "latn", },
  ["sv"] = { ["babel"] = "swedish", ["polyglossia"] = "swedish", ["lang_name"] = "Swedish", ["script"] = "latin", ["script_tag"] = "latn", },
  ["syr"] = { ["babel_ini_only"] = "syriac", ["polyglossia"] = "syriac", ["lang_name"] = "Syriac", ["script"] = "syriac", ["script_tag"] = "syrc", },
  ["ta"] = { ["babel_ini_only"] = "tamil", ["polyglossia"] = "tamil", ["lang_name"] = "Tamil", ["script"] = "tamil", ["script_tag"] = "taml", },
  ["te"] = { ["babel_ini_only"] = "telugu", ["polyglossia"] = "telugu", ["lang_name"] = "Telugu", ["script"] = "telugu", ["script_tag"] = "telu", },
  ["th"] = { ["babel"] = "thai", ["polyglossia"] = "thai", ["lang_name"] = "Thai", ["script"] = "thai", ["script_tag"] = "thai", },
  ["tk"] = { ["babel"] = "turkmen", ["polyglossia"] = "turkmen", ["lang_name"] = "Turkmen", ["script"] = "latin", ["script_tag"] = "latn", },
  ["tr"] = { ["babel"] = "turkish", ["polyglossia"] = "turkish", ["lang_name"] = "Turkish", ["script"] = "latin", ["script_tag"] = "latn", },
  ["uk"] = { ["babel"] = "ukrainian", ["polyglossia"] = "ukrainian", ["lang_name"] = "Ukrainian", ["script"] = "cyrillic", ["script_tag"] = "cyrl", },
  ["ur"] = { ["babel_ini_only"] = "urdu", ["polyglossia"] = "urdu", ["lang_name"] = "Urdu", ["script"] = "arabic", ["script_tag"] = "arab", },
  ["vi"] = { ["babel"] = "vietnamese", ["polyglossia"] = "vietnamese", ["lang_name"] = "Vietnamese", ["script"] = "latin", ["script_tag"] = "latn", },
  ["zh"] = { ["babel_ini_only"] = "chinese", ["polyglossia"] = "chinese", ["polyglossia_variant"] = "simplified", ["lang_name"] = "Chinese Simplified", ["script"] = "hans", ["script_tag"] = "hans", },
  ["zh-cn"] = { ["babel_ini_only"] = "chinese", ["polyglossia"] = "chinese", ["polyglossia_variant"] = "simplified", ["lang_name"] = "Chinese Simplified", ["script"] = "hans", ["script_tag"] = "hans", },
  ["zh-tw"] = { ["babel_ini_only"] = "chinese-traditional", ["polyglossia"] = "chinese", ["polyglossia_variant"] = "traditional", ["lang_name"] = "Chinese Traditional", ["script"] = "hant", ["script_tag"] = "hant", },
}
M.logfiles_extensions = { "aux", "bcf", "blg", "fdb_latexmk", "fls", "figlist", "idx", "log", "nav", "out", "ptc", "run.xml", "snm", "toc", "vrb", "xdv" }
M.known_warnings = {
  { "Reference.*?undefined", "[undefined reference]" },
  { "Runaway argument", "[runaway argument]" },
  { "Underfull \\hbox", "[underfull hbox]" },
  { "Overfull \\hbox", "[overfull hbox]" },
  { "Citation.*?undefined", "[undefined citation]" },
  { "^!.+Unicode character", "[unicode character(s) not supported by pdflatex. Set org-latex-compiler to lualatex or xelatex instead]" },
  { "Missing character: There is no", "[Missing character(s): please load an appropriate font with the fontspec package]" },
  { "Undefined control sequence", "[undefined control sequence]" },
}
M.engraved_preamble = "\\usepackage{fvextra}\n\n[FVEXTRA-SETUP]\n\n% Make line numbers smaller and grey.\n\\renewcommand\\theFancyVerbLine{\\footnotesize\\color{black!40!white}\\arabic{FancyVerbLine}}\n\n\\usepackage{xcolor}\n\n% In case engrave-faces-latex-gen-preamble has not been run.\n\\providecolor{EfD}{HTML}{f7f7f7}\n\\providecolor{EFD}{HTML}{28292e}\n\n% Define a Code environment to prettily wrap the fontified code.\n\\usepackage[breakable,xparse]{tcolorbox}\n\\DeclareTColorBox[]{Code}{o}%\n{colback=EfD!98!EFD, colframe=EfD!95!EFD,\n  fontupper=\\footnotesize\\setlength{\\fboxsep}{0pt},\n  colupper=EFD,\n  IfNoValueTF={#1}%\n  {boxsep=2pt, arc=2.5pt, outer arc=2.5pt,\n    boxrule=0.5pt, left=2pt}%\n  {boxsep=2.5pt, arc=0pt, outer arc=0pt,\n    boxrule=0pt, leftrule=1.5pt, left=0.5pt},\n  right=2pt, top=1pt, bottom=0.5pt,\n  breakable}\n\n[LISTINGS-SETUP]"
M.hyperref_template = "\\hypersetup{\n pdfauthor={%a},\n pdftitle={%t},\n pdfkeywords={%k},\n pdfsubject={%d},\n pdfcreator={%c},\n pdflang={%L}}\n"
M.listings_langs = { { "emacs-lisp", "Lisp" }, { "lisp", "Lisp" }, { "clojure", "Lisp" }, { "c", "C" }, { "cc", "C++" }, { "fortran", "fortran" }, { "perl", "Perl" }, { "cperl", "Perl" }, { "python", "Python" }, { "ruby", "Ruby" }, { "html", "HTML" }, { "xml", "XML" }, { "tex", "TeX" }, { "latex", "[LaTeX]TeX" }, { "shell-script", "bash" }, { "gnuplot", "Gnuplot" }, { "ocaml", "[Objective]Caml" }, { "caml", "Caml" }, { "sql", "SQL" }, { "sqlite", "sql" }, { "makefile", "make" }, { "R", "r" } }
M.minted_langs = { { "emacs-lisp", "common-lisp" }, { "cc", "c++" }, { "cperl", "perl" }, { "shell-script", "bash" }, { "caml", "ocaml" } }
return M
